### PR TITLE
Propagate all kwargs on to assertEqual

### PR DESCRIPTION
**Pull request by ezyang**
Needed for https://github.com/pytorch/pytorch/pull/33825

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Hmm, I f'ed up the patch format.

**Comment by ailzhang** [comment]
@ezyang I made a minor change to keep the keyword arguments outside `kwargs`. We have tests calling `prec` as a positional argument so those are still helpful.

**Comment by ezyang** [comment]
Yeah, SGTM. I'd like to make these kwarg only but that involves a bit of fixing.

**Comment by ailzhang** [comment]
@ezyang We can probably merge this now as tests are passing. Do you want to hold it for more changes? ;)

**Pull request merged**
