### PR TITLE
Test fix for Bernoulli

### PR DESCRIPTION
**Pull request by ezyang**
Companion to https://github.com/pytorch/pytorch/pull/87573

Signed-off-by: Edward Z. Yang <ezyangfb.com>

### CODE REVIEW

**Comment by JackCaoG** [comment]
It seems like for the Bernoulli + scalar, we only lower the in place version. Let me 
https://github.com/pytorch/xla/blob/8332ac9072832c67b2680509bb1ef1abc5813c6a/torch_xla/csrc/aten_xla_type.cpp#L823

Might be easier if we remove all `bernoulli_` and lower the `bernoulli.p`, I think @bdhirsh setup something to generate kernel for inplave and out of plave.

**Comment by ezyang** [comment]
OK. This fixes a major bug in PyTorch core, so I'd like to land it sooner rather than later. My XLA copy is busted right now (anyone know how to fix untracked MLIR errors in bazel?) or I'd offer to try a fix.

**Comment by JackCaoG** [comment]
oh, for the MLIR one, you just need to clean the bazel cache.
```
bazel clean --expunge
```
under `third_party/tensorflow/` should work. Note that you need to apply the tf patches we had using
```
./scripts/apply_patches.sh
```

If this doesn't help let me know, I will work on the fix.

**Comment by ezyang** [comment]
Even with these two commands I still an unable to build

**Comment by JackCaoG** [comment]
Let me take over then

**Comment by bdhirsh** [comment]
Agreed with Jack - when `bernoulli.p` was "broken", it would decompose and XLA would always see `bernoulli_.float`. But with your change, XLA is properly seeing `bernoulli.p` as a primitive. So we should just kill the `bernoulli_.float` lowering and add one for `bernoulli.p`.

**Comment by JackCaoG** [comment]
sg, shouldn't be too difficult. I just kicked of my local build, will work on this after lunch

**Comment by JackCaoG** [comment]
ok I manually verified all cppTest passed, let's wait for CI to confirm

**Review by JackCaoG — APPROVED** [review]

**Pull request merged**
