### PR TITLE
Hot fix nccl_archive v2.16.2-1.tar.gz checksum hash issue

### PR DESCRIPTION
**Pull request by yeounoh**
Temporary work around, while waiting for https://github.com/orgs/community/discussions/45830 to be addressed, to unblock our build. Addresses #4535

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but please add `xla` back to pull (it's in unstable now)

**Review by JackCaoG — APPROVED** [review]

**Comment by yeounoh** [comment]
> LGTM, but please also add `xla` back to pull.yml in pytorch/pytorch (it's in unstable now)

Thanks @malfet will send out the PR to add back `xla` for review.

**Comment by yeounoh** [comment]
There were other archieval failures, but I couldn't reproduce the error locally. Maybe GitHub fixed it already? Rerunning the pipeline.

**Comment by yeounoh** [comment]
Ok, the build is now asking for the old checksums (the reason why the new workflow run is failing). This is a good sign, and I was able to build locally without the patch. Closing the PR.

**Pull request closed without merging**
