### PR TITLE
Add OpenXLA patch at 08/09 for shape check

### PR DESCRIPTION
**Pull request by ManfeiBai**
Apply patch at 08/09 from OpenXLA for shape check: https://github.com/openxla/xla/commit/87b697b657735c50ff15742719999d4ecde674f4 @Moerafaat

### CODE REVIEW

**Comment by JackCaoG** [comment]
can you also update https://github.com/pytorch/xla/blob/master/WORKSPACE#L41

**Comment by ManfeiBai** [comment]
> can you also update https://github.com/pytorch/xla/blob/master/WORKSPACE#L41

thanks for pointing, updated

**Comment by ManfeiBai** [comment]
since the current test running, will bring back fsdp tests after the current GPU tests passed

**Comment by wonjoolee95** [comment]
Thanks, @ManfeiBai. Change looks good, let's just wait for the CI to verify the merge.

**Comment by vanbasten23** [comment]
It seems it's still failing in the CI ([log](https://pipelines.actions.githubusercontent.com/serviceHosts/4af947c0-21d8-4649-a7c2-932feec4798b/_apis/pipelines/1/runs/3830/signedlogcontent/24?urlExpires=2023-08-28T21%3A06%3A57.7566399Z&urlSigningMethod=HMACV1&urlSignature=hjKzju4DX2MzbGdEg0SiRjI9A6e3LH1szK1VRFuSfWM%3D)) but with a different error message. The failing test is `python test/test_train_mp_imagenet_fsdp.py --fake_data --use_nested_fsdp --use_small_fake_sample --num_epochs=1`, same as before, but with a different error message (used to be shape mismatch. but it becomes OOM now).

@ManfeiBai , would you mind rebase your pr on master and trigger the CI again?

**Comment by ManfeiBai** [comment]
add mnist test before fsdp test to confirm whether the env or ci or code of fsdp made the OOM

**Comment by alanwaketan** [comment]
This will be picked up by the pin update this week (hopefully). I guess we don't need to patch it manually now.

**Pull request closed without merging**
