### PR TITLE
Update OpenXLA pin as of 07172024

### PR DESCRIPTION
**Pull request by wonjoolee95**
Update OpenXLA pin as of 07172024

Fixes
- Rename ToPjRtDeviceAttributeMap to ToPjRtAttributeMap (https://github.com/openxla/xla/commit/dd77329b26c1d2e5986b6a733b07a527099aa765)

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Local build succeeds, let me verify the speed via resnet.

**Comment by wonjoolee95** [comment]
Resnet fake data seeing ~1800 rate as expected, I'll let CI to verify the rest.

Full command output: https://gist.github.com/wonjoolee95/22f313eaaf32ed26052f76df736adcb2

**Comment by JackCaoG** [comment]
can you verify the pallas test locally? TPUCI is not configured

**Comment by wonjoolee95** [comment]
Sure thing, looks okay on my v4-8:
```
root@t1v-n-4989e8c7-w-0:~/pytorch/xla# pip show libtpu-nightly
Name: libtpu-nightly
Version: 0.1.dev20240718+default
Summary: Wrapper for the libtpu library.
Home-page: 
Author: Google, Inc.
Author-email: 
License: 
Location: /usr/local/lib/python3.10/site-packages
Requires: 
Required-by: 
root@t1v-n-4989e8c7-w-0:~/pytorch/xla# python test/test_pallas
test_pallas.py       test_pallas_spmd.py  
root@t1v-n-4989e8c7-w-0:~/pytorch/xla# python test/test_pallas
test_pallas.py       test_pallas_spmd.py  
root@t1v-n-4989e8c7-w-0:~/pytorch/xla# python test/test_pallas.py 
INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda': 
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
.......................
----------------------------------------------------------------------
Ran 23 tests in 14.773s

OK
root@t1v-n-4989e8c7-w-0:~/pytorch/xla# 
```

**Review by JackCaoG — APPROVED** [review]

**Review by ManfeiBai — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
