### PR TITLE
updating tf to latest

### PR DESCRIPTION
**Pull request by JackCaoG**
This is to bring in https://github.com/tensorflow/tensorflow/commit/3c5b4a1637a5452d52d088e0b1c064322efc03e4 for tpuvm pod setup.

### CODE REVIEW

**Review by jysohn23 — APPROVED** [review]
Just to clarify, we're doing this instead of patching TF? Or are we patching TF for 1.8 separately?

**Comment by JackCaoG** [comment]
> Just to clarify, we're doing this instead of patching TF? Or are we patching TF for 1.8 separately?

I am planning to update it for nightly and patch for 1.8

**Comment by JackCaoG** [comment]
Build failed with log
```
ERROR: /tmp/pytorch/xla/third_party/tensorflow/tensorflow/core/kernels/BUILD:357:18: C++ compilation of rule '//tensorflow/core/kernels:fill_functor_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/fill_functor_gpu/fill_functor.cu.pic.d ... (remaining 173 argument(s) skipped)
```

Weird that the build passed locally for me. I will restart the build on circleCI and on my vm.

**Comment by JackCaoG** [comment]
Build pass fine locally, did a bit a research and the problem seems to be related to cuda version + gcc verion + vm image native tooling(https://github.com/tensorflow/tensorflow/issues/22372#issuecomment-678405937).  I updated the tf again and hope this problem has somehow been noticed and fixed.

**Comment by JackCaoG** [comment]
Failure log
```
ERROR: /tmp/pytorch/xla/third_party/tensorflow/tensorflow/core/kernels/BUILD:4000:18: C++ compilation of rule '//tensorflow/core/kernels:softsign_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/softsign_op_gpu/softsign_op_gpu.cu.pic.d ... (remaining 299 argument(s) skipped)
external/com_google_absl/absl/functional/function_ref.h:100:29: error: parameter packs not expanded with '...':
   template <typename F, typename = EnableIfCompatible<const F&>>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                        
external/com_google_absl/absl/functional/function_ref.h:100:29: note:         'Args'
external/com_google_absl/absl/functional/function_ref.h:114:13: error: parameter packs not expanded with '...':
       typename F, typename = EnableIfCompatible<F*>,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                        
external/com_google_absl/absl/functional/function_ref.h:114:13: note:         'Args'
Target //tensorflow/compiler/xla/xla_client:libxla_computation_client.so failed to build
```

**Comment by JackCaoG** [comment]
Chatted with frank, this is most likley due to some commit introduce something `nvcc` doesn't like hence break the gpu build. I will try to bisect and narrow down the pr that breaks it.

**Comment by JackCaoG** [comment]
Last attempt to update the tf to latest. If this still doesn't work, I will start bisecting the tf commit.

**Comment by JackCaoG** [comment]
last working commit if from 03/01/21, will start bisecting.

**Comment by JackCaoG** [comment]
This commit includes LookupStream change we need, merge it for now

**Pull request merged**
