### PR TITLE
Make the topology fetch API do not require the XRT computation client…

### PR DESCRIPTION
**Pull request by dlibenzi**
… to be setup.

Use a single init for TPU mesh setup.

### CODE REVIEW

**Comment by dlibenzi** [comment]
> Have we tested this works on a pod slice?

I did on Borg.

**Comment by jysohn23** [comment]
> > Have we tested this works on a pod slice?
> 
> I did on Borg.

Bad news, I get the error message:
```
2019-09-06 04:18:22.859156: E tensorflow/compiler/xla/xla_client/xla_util.cc:72] The TPU system has not been initialized.
```

Full client-side logs: https://gist.github.com/jysohn23/d6631b3cde065500ebf9a4d462492ef4.

Have you tried testing with a slice that hadn't already been initialized previously? With a previously initialized (N^2 inits) TPU slice, trying this single init way had worked for me previously which was misleading. Would you mind reproing the failure on a fresh slice? (not that it matters, but I tried on v3-32 and v3-512).

**Comment by dlibenzi** [comment]
Yes, freshly handed out by Borg.
I pushed the CL this afternoon, are you sure it has been picked up by
nightly?

**Comment by jysohn23** [comment]
> Yes, freshly handed out by Borg. I pushed the CL this afternoon, are you sure it has been picked up by nightly?

Yes, I triggered an on-demand nightly after your PR was merged and verified `pip freeze` and we don't see the manual configs one by one on each worker.

**Comment by dlibenzi** [comment]
PR?
You meant CL?
There need to be the TF mesh CL in the TFRC servers on the TPU VMs.

**Comment by jysohn23** [comment]
> PR? You meant CL? There need to be the TF mesh CL in the TFRC servers on the TPU VMs.

Oh, yes you are right, thanks for reminding me; I forgot about the TFRC update of course..! I'll try this tomorrow.

**Pull request merged**
