### PR TITLE
add codegen for masked_fill

### PR DESCRIPTION
**Pull request by zpcore**
Use codegen for `masked_fill` xla op inclusing `masked_fill.Scalar` and `masked_fill.Tensor`.

In addition, a new test case for `masked_fill` is added when the input dimension is smaller than the mask dimension to test the broadcasting.

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Nice! Could you also paste the generated `XLANativeFunctions.cpp` and `LazyIr.h` files in the PR summary just for info (ex. https://github.com/pytorch/xla/pull/3564)?

**Comment by zpcore** [comment]
> XLANativeFunctions

**Comment by zpcore** [comment]
> Nice! Could you also paste the generated `XLANativeFunctions.cpp` and `LazyIr.h` files in the PR summary just for info (ex. #3564)?

Sure, here are the auto generated functions' signature in `XlaNativeFunctions.cpp`:
```
    at::Tensor XLANativeFunctions::masked_fill(const at::Tensor & self, const at::Tensor & mask, const at::Scalar & value) {
        
        TORCH_LAZY_FN_COUNTER("xla::");
        auto common_device = torch_xla::bridge::GetXlaDevice(self, mask);
        TORCH_INTERNAL_ASSERT(common_device);
        
        torch_xla::XLATensorPtr lazy_self = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(self, *common_device);
        torch_xla::XLATensorPtr lazy_mask = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(mask, *common_device);
        auto node_value = torch::lazy::LazyGraphExecutor::Get()->
                            GetIrValueForScalarFromCodegen(value, *common_device);
        torch::lazy::NodePtr node = torch::lazy::ReuseNode<MaskedFillScalar>(lazy_self->GetIrValue(), lazy_mask->GetIrValue(), node_value);
      if (!node) {
          
          node = torch::lazy::MakeNode<MaskedFillScalar>(lazy_self->GetIrValue(), lazy_mask->GetIrValue(), node_value);
          CacheNode(node);
      }
      
        auto result = torch_xla::bridge::AtenFromXlaTensor(
                torch_xla::XLATensor::Create(std::move(node), *common_device));
        return result;
    }

    at::Tensor XLANativeFunctions::masked_fill(const at::Tensor & self, const at::Tensor & mask, const at::Tensor & value) {
        
        TORCH_LAZY_FN_COUNTER("xla::");
        auto common_device = torch_xla::bridge::GetXlaDevice(self, mask, value);
        TORCH_INTERNAL_ASSERT(common_device);
        
        torch_xla::XLATensorPtr lazy_self = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(self, *common_device);
        torch_xla::XLATensorPtr lazy_mask = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(mask, *common_device);
        torch_xla::XLATensorPtr lazy_value = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(value, *common_device);
        torch::lazy::NodePtr node = torch::lazy::ReuseNode<MaskedFillTensor>(lazy_self->GetIrValue(), lazy_mask->GetIrValue(), lazy_value->GetIrValue());
      if (!node) {
          
          node = torch::lazy::MakeNode<MaskedFillTensor>(lazy_self->GetIrValue(), lazy_mask->GetIrValue(), lazy_value->GetIrValue());
          CacheNode(node);
      }
      
        auto result = torch_xla::bridge::AtenFromXlaTensor(
                torch_xla::XLATensor::Create(std::move(node), *common_device));
        return result;
    }
```

And this is for LazyIr.h:
```
class MaskedFillScalar : public TsNode {
 public:
  static torch::lazy::OpKind ClassOpKind() {
    return torch::lazy::OpKind(at::aten::masked_fill);
  }

  MaskedFillScalar(const torch::lazy::Value& self, const torch::lazy::Value& mask, const torch::lazy::Value& value, std::vector<torch::lazy::Shape>&& shapes)
      : TsNode(
              MaskedFillScalar::ClassOpKind(),
              OpList{self, mask, value},
              std::move(shapes),
              /* num_outputs */ 1,
              torch::lazy::MHash())
  {  }

  std::string ToString() const override {
    std::stringstream ss;
    ss << TsNode::ToString();
    return ss.str();
  }

  bool CanBeReused(const torch::lazy::Value& self, const torch::lazy::Value& mask, const torch::lazy::Value& value) const {
    size_t i = 0;
    return (operand(i++) == self &&
        operand(i++) == mask &&
        operand(i++) == value);
  }

  torch::lazy::TSOpVector Lower(
      std::shared_ptr<torch::jit::GraphFunction> function,
      torch::lazy::TSLoweringContext* loctx) const override {
        std::vector<torch::jit::NamedValue> arguments;
    std::vector<torch::jit::NamedValue> kwarguments;
    arguments.reserve(3);
    kwarguments.reserve(0);
    size_t i = 0;
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    torch::lazy::TSOpVector masked_fill_out = torch::lazy::LowerTSBuiltin(function, op().op, arguments, kwarguments);
    TORCH_CHECK_EQ(masked_fill_out.size(), 1);
    return masked_fill_out;
  }
};

class MaskedFillTensor : public TsNode {
 public:
  static torch::lazy::OpKind ClassOpKind() {
    return torch::lazy::OpKind(at::aten::masked_fill);
  }

  MaskedFillTensor(const torch::lazy::Value& self, const torch::lazy::Value& mask, const torch::lazy::Value& value, std::vector<torch::lazy::Shape>&& shapes)
      : TsNode(
              MaskedFillTensor::ClassOpKind(),
              OpList{self, mask, value},
              std::move(shapes),
              /* num_outputs */ 1,
              torch::lazy::MHash())
  { }

  std::string ToString() const override {
    std::stringstream ss;
    ss << TsNode::ToString();
    return ss.str();
  }

  bool CanBeReused(const torch::lazy::Value& self, const torch::lazy::Value& mask, const torch::lazy::Value& value) const {
    size_t i = 0;
    return (operand(i++) == self &&
        operand(i++) == mask &&
        operand(i++) == value);
  }

  torch::lazy::TSOpVector Lower(
      std::shared_ptr<torch::jit::GraphFunction> function,
      torch::lazy::TSLoweringContext* loctx) const override {
        std::vector<torch::jit::NamedValue> arguments;
    std::vector<torch::jit::NamedValue> kwarguments;
    arguments.reserve(3);
    kwarguments.reserve(0);
    size_t i = 0;
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    torch::lazy::TSOpVector masked_fill_out = torch::lazy::LowerTSBuiltin(function, op().op, arguments, kwarguments);
    TORCH_CHECK_EQ(masked_fill_out.size(), 1);
    return masked_fill_out;
  }
};
```

**Review by wonjoolee95 — APPROVED** [review]
LGTM

**Pull request merged**
