### PR TITLE
XRT branch cherry-pick 07/10

### PR DESCRIPTION
**Pull request by JackCaoG**
two commit I skipped are PJRT/OpenXLA related
1. https://github.com/pytorch/xla/pull/5275 build file
2. https://github.com/pytorch/xla/pull/5233 StableHLO Pjrt
3. https://github.com/pytorch/xla/pull/5269 Suppress debug symbols in OpenXLA code

The last pr I cherry-picked is [avoid copy proto in PrepareOutputShardingPropagation (](https://github.com/pytorch/xla/commit/54e2bb6919fe91a45ad529681c5b4e97732a0b31) at J07/07

### CODE REVIEW

**Comment by will-cromar** [comment]
Are you sure we should cherry-pick `Suppress debug symbols in OpenXLA code`?

**Comment by JackCaoG** [comment]
lol good catch.. let me revert that

**Comment by mateuszlewko** [comment]
LGTM changes in /infra/...

**Comment by JackCaoG** [comment]
error is 
```
ERROR: /tmp/pytorch/xla/torch_xla/csrc/runtime/BUILD:534:10: Linking torch_xla/csrc/runtime/libxla_computation_client.so failed: missing input file '//torch_xla/csrc/runtime:tf_exported_symbols.lds'
ERROR: /tmp/pytorch/xla/torch_xla/csrc/runtime/BUILD:534:10: Linking torch_xla/csrc/runtime/libxla_computation_client.so failed: missing input file '//torch_xla/csrc/runtime:tf_version_script.lds
```
I think they are being deleted as one of the commit, I can add them back

**Comment by JackCaoG** [comment]
@will-cromar test is green, can you take another look at this pr? After it is approved, I think we should turn on the `rebae and merge`, merge this pr, then maybe turn it off again.

**Review by will-cromar — APPROVED** [review]
LGTM. It's up to you how you want to merge it. I'm fine with squashing.

**Comment by JackCaoG** [comment]
I enabled the `allow rebase and merge` in the setting but it is still grey here. I will give it a day to see if it is just config take times to propragate.

**Comment by JackCaoG** [comment]
rebase and merge still grey, I am just gonna squash.

**Pull request merged**
