### PR TITLE
Skip rand tests due to as_strided.

### PR DESCRIPTION
**Pull request by ailzhang**
https://github.com/pytorch/pytorch/pull/35585

### CODE REVIEW

**Comment by dlibenzi** [comment]
I don't think it is due to as-strided, is it?
AFAICT it is resetting the seed.

**Comment by ailzhang** [comment]
@dlibenzi seed is one, also it's calling into `rand_out` which calls resize_ inside...

**Comment by JackCaoG** [comment]
> I don't think it is due to as-strided, is it?
> AFAICT it is resetting the seed.

Haven't looked at test_rand, but for test_randn, it is using randn_out and that calls as_stride
```
(Pdb) res5
tensor([100., 100.], device='xla:0')
(Pdb) torch.randn(SIZE, SIZE, out=res5)
tensor([[ 1.3755, -2.1590,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='xla:0')
```
ir graph of this tensor is
```
(Pdb) print(torch_xla._XLAC._get_xla_tensors_text([res5]))
IR {
  %0 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %1 = f32[100,100]{1,0} aten::expand(%0), location=<module>@<stdin>:1, size=(100, 100)
  %2 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %3 = f32[100,100]{1,0} aten::expand(%2), location=<module>@<stdin>:1, size=(100, 100)
  %4 = f32[100,100]{1,0} aten::normal(%3, %1), location=<module>@<stdin>:1, seed=15277467711799785322
  %5 = f32[2]{0} aten::resize(%4), location=get_summarized_data@_tensor_str.py:239, size=(2)
  %6 = f32[2]{0} xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %7 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %8 = f32[2]{0} aten::expand(%7), location=<module>@<stdin>:1, size=(2)
  %9 = f32[2]{0} xla::as_strided_view_update(%8, %6), location=__init__@_tensor_str.py:88, size=(2), stride=(1), storage_offset=0
  %10 = f32[2]{0} xla::as_strided_view_update(%9, %5), location=get_summarized_data@_tensor_str.py:239, size=(2), stride=(1), storage_offset=0
  %11 = f32[2]{0} aten::as_strided(%10), location=<module>@<stdin>:1, size=(2), stride=(1), storage_offset=0
  %12 = f32[100,100]{1,0} aten::resize(%11), location=<module>@<stdin>:1, size=(100, 100), ROOT=0
}
```

test won't pass at first place because we don't support manual seed. However, even if we fix the seed problem we will still fail because of this as_stride issue hence I leave the above comments.

**Comment by dlibenzi** [comment]
The as-strided calls there looks OK AFAICT.
We have *many* as-strided calls from PT, and we support the vast majority 😉

**Pull request merged**
