### PR TITLE
Remove log softmax

### PR DESCRIPTION
**Pull request by JackCaoG**
This is to fix https://github.com/pytorch/pytorch/pull/76489

### CODE REVIEW

**Review by wonjoolee95 — APPROVED** [review]

**Comment by JackCaoG** [comment]
for some reason this breaks autocast.. looking

**Comment by JackCaoG** [comment]
For somre eason casting input from f16->f32 and perform the `logsoftmax` gives different result
```
(Pdb) getattr(module, op)(*cast(args, run_as_type), **add_kwargs)
tensor([-1.1602, -2.5987, -1.2842, -2.5159, -2.0767, -2.8957, -3.7666, -2.9796],
       device='xla:0')
(Pdb) getattr(module, op)(*args, run_as_type, **add_kwargs)
tensor([-1.1602, -2.5977, -1.2842, -2.5156, -2.0762, -2.8945, -3.7656, -2.9805],
       device='xla:0')
(Pdb) args
self = <__main__.TestAutocast testMethod=test_autocast_torch_fp32>
op = 'log_softmax'
args = (tensor([ 1.8496,  0.4111,  1.7256,  0.4939,  0.9331,  0.1141, -0.7568,  0.0302],
       device='xla:0', dtype=torch.float16), 0)
run_as_type = torch.float32
out_type = torch.float32
```

precision difference is minor, I will disable the test for now.

**Comment by JackCaoG** [comment]
not able to repro the error, retrigger the test

**Comment by JackCaoG** [comment]
Hmm I exported `export TORCH_SHOW_CPP_STACKTRACES=1` but still can't see the C++ stack trace @bdhirsh @Chillee

```
======================================================================
ERROR: test_ctc_loss_xla (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 808, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/tmp/pytorch/xla/test/../../test/test_nn.py", line 18777, in test_ctc_loss
    gradcheck(ctc_after_softmax, [x])
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 3004, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1409, in gradcheck
    return _gradcheck_helper(**args)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1426, in _gradcheck_helper
    check_undefined_grad=check_undefined_grad)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1071, in _gradcheck_real_imag
    rtol, atol, check_grad_dtypes, nondet_tol)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1298, in _fast_gradcheck
    _check_no_differentiable_outputs_fast(func, func_out, inputs, inp_tensors_idx, all_u, eps, nondet_tol)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 706, in _check_no_differentiable_outputs_fast
    raise GradcheckError('Numerical gradient for function expected to be zero')
torch.autograd.gradcheck.GradcheckError: Numerical gradient for function expected to be zero

======================================================================
ERROR: test_nll_loss_byte_target_matches_long_xla (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/tmp/pytorch/xla/test/../../test/test_nn.py", line 19420, in test_nll_loss_byte_target_matches_long
    result_long, grad_long = compute_result_and_gradient(reduction, torch.long)
  File "/tmp/pytorch/xla/test/../../test/test_nn.py", line 19415, in compute_result_and_gradient
    result.sum().backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

======================================================================
ERROR: test_softmax_results_xla_float32 (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/tmp/pytorch/xla/test/../../test/test_nn.py", line 16699, in test_softmax_results
    grad_input, = torch.autograd.grad(output, input, grad_outputs=(grad_output), create_graph=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 278, in grad
    allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

anything else I should try?

**Comment by JackCaoG** [comment]
same test also passed on TPU, I guess I can try to pull the CPU CI docker image and run that to see if I can repo the erorr locally..

**Comment by JackCaoG** [comment]
I am able to repo the issue using CI Docker 
```
======================================================================
ERROR: test_softmax_results_xla_float32 (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "test/test_nn.py", line 16699, in test_softmax_results
    grad_input, = torch.autograd.grad(output, input, grad_outputs=(grad_output), create_graph=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 278, in grad
    allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

----------------------------------------------------------------------
Ran 1 test in 48.810s
```

looking.

**Comment by JackCaoG** [comment]
Here is the step to repo locally using docker
1.  sudo docker pull gcr.io/tpu-pytorch/xla_base:latest-15fdb3c2e324a15f660091f377541f9534cf9bf8
2. sudo docker run  -it -d gcr.io/tpu-pytorch/xla_base:latest-15fdb3c2e324a15f660091f377541f9534cf9bf8
3. sudo docker exec --privileged -it $(docker id) /bin/bash

within docker
```
    2  export 'XRT_DEVICE_MAP=CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0'
    3  export PYTORCH_TESTING_DEVICE_ONLY_FOR=xla
    4  export 'XRT_WORKERS=localservice:0;grpc://localhost:40995'
    5  export TORCH_TEST_DEVICES=/tmp/pytorch/xla/test/pytorch_test_base.py
    6  cd /tmp/pytorch
    7  export TORCH_SHOW_CPP_STACKTRACES=1
    8  python test/test_nn.py TestNNDeviceTypeXLA.test_softmax_results_xla_float32
```

failure looks like
```
(base) jenkins@f655ec34ff20:/tmp/pytorch$ python test/test_nn.py TestNNDeviceTypeXLA.test_softmax_results_xla_float32
2022-05-06 20:57:22.521295: W      45 tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-05-06 20:57:22.521364: W      45 tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
E
======================================================================
ERROR: test_softmax_results_xla_float32 (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "test/test_nn.py", line 16699, in test_softmax_results
    grad_input, = torch.autograd.grad(output, input, grad_outputs=(grad_output), create_graph=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 278, in grad
    allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

----------------------------------------------------------------------
Ran 1 test in 92.631s

FAILED (errors=1)
```

**Pull request closed without merging**
