### PR TITLE
run the new tests under `test/nn`

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/pull/84165#discussion_r956693153

Ref: https://github.com/pytorch/pytorch/pull/84165

### CODE REVIEW

**Comment by JackCaoG** [comment]
Thanks! Can you add the torch pin similar to https://github.com/pytorch/xla/pull/3913/files#diff-e71f55b9deb410fad9d5945c4c30878a93369434520520987ac03c59bfa5280d . The content of the pin is your pytorch pr number. This will force ci to checkout your branch when building pyotrch in this pr.

**Comment by JackCaoG** [comment]
I think you need to rebase your pytorch pr too.

**Comment by kshitij12345** [comment]
It's weird, there is one xfail test which is passing.

https://app.circleci.com/pipelines/github/pytorch/xla/13016/workflows/6c882825-1ada-4565-90d5-add82c0b550c/jobs/29211?invite=true#step-107-1857

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
I think we can just merge pytorch pr first and then merge this pr later. PyTorch/xla will lost the test coverage for `test_drop_out` for one day(until pin is updated) but I think it is OK.

**Comment by kshitij12345** [comment]
Thanks! Have started the merge process on that PR

**Pull request merged**
