### PR TITLE
Update 1.5 patch.

### PR DESCRIPTION
**Pull request by ailzhang**

### CODE REVIEW

**Comment by dlibenzi** [comment]
Is there an upgrade, or this is for the pytorch 1.5.1 cherry-pick?

**Comment by ailzhang** [comment]
This is for 1.5 cherry-pick https://github.com/pytorch/pytorch/pull/39153. 
CI on the PR above failed since our patch is outdated, so it was blocking the cherry-pick to be merged.

**Comment by ailzhang** [comment]
Ehh looks like `torch_patch/.torch_pin` doesn't work with non-master branch. Since I've applied this patch locally, I will go ahead and merge this. And fix the `torch_pin` issue in CI later.

**Comment by ailzhang** [comment]
FYI `torch_pin` didn't work in `r.15` because we added later than 1.5 release. This should work in the future release branches...

**Pull request merged**
