### PR TITLE
Throw when trying to access storage of an XLA tensor

### PR DESCRIPTION
**Pull request by asuhan**

### CODE REVIEW

**Comment by asuhan** [comment]
Yes, as opposed to crash. `OpaqueTensorImpl` already does this: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/OpaqueTensorImpl.h#L72.

**Comment by asuhan** [comment]
Would it be better to override `has_storage` then?

**Comment by dlibenzi** [comment]
Should we ping harder Gregory to see what he thinks about it?
He was the one pushing for this new tensor impl ... with our older version we'd have likely been fine.

**Comment by asuhan** [comment]
I've added a test and an override for `has_storage` as well. I'd say we should also ping Gregory about this and `torch.save`, but still not leave this segfault to happen.

**Pull request merged**
