### PR TITLE
use in-tree public codegen API.

### PR DESCRIPTION
**Pull request by bdhirsh**
This PR updates the build process to use in-tree pytorch codegen, which is getting merged here: https://github.com/pytorch/pytorch/pull/56601 (more details on the codegen are in that PR). Doing so requires a new yaml file, `xla_native_functions.yaml`.

I also updated the docs to reflect the codegen change. I'm going to save deleting the existing codegen logic for a future PR

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
LGTM! Thanks @bdhirsh !

**Comment by JackCaoG** [comment]
@bdhirsh I have a question regarding ops that has different signatures. for example in https://github.com/pytorch/xla/pull/2900, `clamp` has two different signatures that takes `min` and `max` as `scalar` or `tensor`. If I only want to lower one of the variants, how should I do that?

**Comment by JackCaoG** [comment]
Could you also update https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md to reflect this new yaml file?

**Comment by bdhirsh** [comment]
@JackCaoG 
>  have a question regarding ops that has different signatures. for example in #2900, clamp has two different signatures that takes min and max as scalar or tensor. If I only want to lower one of the variants, how should I do that?

The operator names (both in `xla_native_functions.yaml`, and in the in-tree `native_functions.yaml`) follow a convention of being named as `<name>.<overload_name>`, in order to make them unique without needing schema. In the example you linked with `clamp`, there's a corresponding change in `native_functions.yaml` that adds the new clamp overload [here](https://github.com/pytorch/pytorch/pull/52695/files#r603292006) (the new operator there is named `clamp.Tensor`).

In general you can look at `native_functions.yaml` in-tree to see what the full names of the operators are, when you need to figure out the name of the operator to add the the yaml. There are already a bunch in the `xla_native_functions.yaml` file included in this PR (just search for `.out` or `.Tensor` in that file).

> Could you also update https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md to reflect this new yaml file?

Yep! I'll let you know when I've updated it so you can take a look at the changes

**Comment by bdhirsh** [comment]
updated the docs

**Review by JackCaoG — APPROVED** [review]
Thanks @bdhirsh ! This looks great. Could you wait for https://github.com/pytorch/xla/pull/2891 to land first (I chatted with @mruberry and the upstream pytorch pr should merge pretty soon) and update your pr? 

I can take care of the rest of the pending op lowering pr and rebase those prs.

**Pull request merged**
