### PR TITLE
Migrate to upstream tensor_util classes and functions

### PR DESCRIPTION
**Pull request by wonjoolee95**
Migrate to upstream tensor_util classes and functions

TODO
- ~Remove replaced functions in PTXLA~ Done

### CODE REVIEW

**Comment by wonjoolee95** [comment]
CircleCI GPU test failure:
```
test (__main__.TestParallelTensorMNIST) ... Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
```

**Comment by wonjoolee95** [comment]
> CircleCI GPU test failure:
> 
> ```
> test (__main__.TestParallelTensorMNIST) ... Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
> ```

This seems to be a bug in GLIBC (that happens frequently in CircleCI specifically) -- https://github.com/puppeteer/puppeteer/issues/2207. Fortunately for us, retrying the CircleCI succeeded.

**Review by JackCaoG — COMMENTED** [review]
Should we also delete `OptionalOr` definition? I didn't check the upstream functions but I assume they are identical to the pytorch/xla one?

**Comment by wonjoolee95** [comment]
> Should we also delete `OptionalOr` definition? I didn't check the upstream functions but I assume they are identical to the pytorch/xla one?

Yep, updated!

**Review by JackCaoG — APPROVED** [review]
Thanks @wonjoolee95, please merge if all test passed.

**Comment by wonjoolee95** [comment]
Merging this as all CI tests have passed.

**Comment by wonjoolee95** [comment]
My apologies, didn't add you as a reviewer to this one. I'll add to PRs going on forward, @miladm.

**Pull request merged**
