### PR TITLE
Configure Terrafrom to build all required artifacts in the new GCP project for releases

### PR DESCRIPTION
**Pull request by mateuszlewko**
This PR adds Terraform configuration for the new tpu-pytorch-release GCP project and existing tpu-pytorch.

1. Terraform config is now split into reusable modules (`terraform_modules`).
2. Each GCP project setup is in a separate directory.
3. Build triggers are configured for all pytorch and pytorch/xla artifacts.
4. Admins IAMs for tpu-pytorch-release and Remote Build IAMs for tpu-pytorch.

After this PR is pushed, we can delete previous (`*-staging`) resources and the /docker/experimental/terraform directory.

### CODE REVIEW

**Comment by mateuszlewko** [comment]
Added admins IAMs for tpu-pytorch-release and Remote Build IAMs for tpu-pytorch.

If there are no objections I can merge this PR soon.

**Comment by JackCaoG** [comment]
Hey @mateuszlewko This pr seems to break ci-tpu-test-trigger, can you take a look?

**Comment by JackCaoG** [comment]
You can check error log in https://github.com/pytorch/xla/runs/12748787904. There are some tests only runs on commit merged, but you can manually trigger the test.

**Comment by mateuszlewko** [comment]
Looks like I deleted some experimental files that shouldn't be deleted. Reverted them in https://github.com/pytorch/xla/pull/4884.

**Comment by JackCaoG** [comment]
@mateuszlewko It is Friday at your time so I will revert it for now. Let's circle back to this next week.

**Comment by mateuszlewko** [comment]
SGTM

**Pull request merged**
