### PR TITLE
Support building for different Operating Systems, from your scripts

### PR DESCRIPTION
**Pull request by SamuelMarks**
Your README.md contains no guide on how to build xla. So I have begun retrofitting your CircleCI scripts to support running outside a CircleCI environment… and whilst I'm there, added support for other OSs and Linux distributions.

Various Linux distributions and macOS should be straightforward. BSDs probably don't matter due to their lack of good graphics support. Windows—BSD, and macOS for that matter—doesn't actually support TPUs AFAIK, so guess that doesn't matter either for the shell scripts.

Want me to update the CircleCI config to build for other OSs?

The latest commit works fine on macOS, just run `build.sh` and it'll mostly succeed. I'm currently—as of 810e255—stuck on this one error, at the last `python setup.py install` of `build.sh` (got to the same point on Debian with f3f8fbc):
```
/tmp/pytorch/xla /tmp/pytorch ~/repos/xla
Building torch_xla version: 1.6
XLA Commit ID: aa084dee304d6217a2bf0e18e2db48c0c37b5a98
PyTorch Commit ID: 502ec8f7f76619e6cbb1efb0e23eb8c5438daed2
/private/tmp/pytorch/xla/scripts/gen.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(default_values, collections.Mapping):
Extracted 1398 functions (0 errors) from /private/tmp/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
352 function overrides in /private/tmp/pytorch/xla/scripts/../torch_xla/csrc/aten_xla_type.h
Generated 1398 wrappers for /private/tmp/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
/private/tmp/pytorch/xla
cp: cannot create directory '/private/tmp/pytorch/xla/third_party/tensorflow/tensorflow/compiler/xla/': No such file or directory
Failed to build external libraries: ['/private/tmp/pytorch/xla/build_torch_xla_libs.sh', 'install']
```

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@dlibenzi Okay, forget other OSs. Just Linux then. I want to be able to automatically configure and build XLA on my TPU pods, whether they're running Debian, Ubuntu, [or in the future, something else].

Now just limiting to Debian-based distributions, still shows a limitation in pytorch/xla—namely: lack of documentation on how to configure and build.

With these scripts of yours I've edited, you can just direct people to run `.circleci/build.sh` and expect it to succeed for them.

**Comment by SamuelMarks** [comment]
@dlibenzi Okay, forget other OSs. Just Linux then. I want to be able to automatically configure and build XLA on my gcloud compute boxes linking to TPU pods, whether they're running Debian, Ubuntu, [or in the future, something else].

Now just limiting to Debian-based distributions, still shows a limitation in pytorch/xla—namely: lack of documentation on how to configure and build.

With these scripts of yours I've edited, you can just direct people to run `.circleci/build.sh` and expect it to succeed for them.

**Comment by dlibenzi** [comment]
Sorry but this adds complexity in a part of the code base nobody likes to touch.
Every time we have issues with the build scripts it's pretty time consuming, and rather boring task, which nobody is willing to take.
Without business reason, or large user request, I'd rather not add the complexity.

The code also seems to imply one can use same package names across a variety of package managers, which is not true.

Also note that the files you changed are only used in FB CircleCI.
We use `scripts/build_torch_wheels.sh` internally.
Also, our CONTRIBUTING guide explains that:

https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md

**Comment by SamuelMarks** [comment]
Actually, not it doesn't. I use different package names here:
https://github.com/SamuelMarks/xla/blob/aa084de/.circleci/install_deps.sh#L11-L12

In terms of how to handle this at scale, I would probably use repology (or similar).

I also updated these scripts with a better shebang line, improved quoting of variables and fixed-strings, and increased the level of strictness across all the shell scripts with `set -euo pipefail`.

Your README.md calls for people to use your prebuilt VM or Docker images. What if people want to deploy it themselves, on a simpler base-image? - E.g., if they want to support multiple frameworks, and build them all themselves?

(hint: I do)

What's the harm in merging this PR? - The extra maintenance burden seems extremely minimal. - Especially with the CI setup. - Hell, you can just tag me if maintenance becomes an issue, and I'll make change the relevant 3 lines.

**Pull request closed without merging**
