### PR TITLE
Parallel tests

### PR DESCRIPTION
**Pull request by stgpetrovic**
This speeds up the tests on CPU by 30%.

* Improve coverage config

* Rearrange tests to speed them up.

* Run TPU and GPU tests serially.

* Automate sharding

Before:
```
NFO: Elapsed time: 172.362s, Critical Path: 168.15s

//test/cpp:main                                                          PASSED in 167.4s
```

After: 
```
INFO: Elapsed time: 118.346s, Critical Path: 117.29s

//test/cpp:test_aten_xla_tensor_1                                        PASSED in 64.1s
//test/cpp:test_aten_xla_tensor_2                                        PASSED in 41.5s
//test/cpp:test_aten_xla_tensor_3                                        PASSED in 91.3s
//test/cpp:test_aten_xla_tensor_4                                        PASSED in 79.5s
//test/cpp:test_aten_xla_tensor_5                                        PASSED in 85.0s
//test/cpp:test_aten_xla_tensor_6                                        PASSED in 117.3s
//test/cpp:test_ir                                                       PASSED in 0.9s
//test/cpp:test_lazy                                                     PASSED in 0.7s
//test/cpp:test_op_by_op_executor                                        PASSED in 0.5s
//test/cpp:test_replication                                              PASSED in 0.7s
//test/cpp:test_tensor                                                   PASSED in 97.2s
//test/cpp:test_xla_backend_intf                                         PASSED in 0.7s
//test/cpp:test_xla_sharding                                             PASSED in 0.7s
```

`AtenXlaTensorTest.TestTransposedConv3DBackward` is the [slowest](https://source.cloud.google.com/results/invocations/5e15347f-0e43-47a0-8c35-8ec7930b6e17/targets/%2F%2Ftest%2Fcpp:test_aten_xla_tensor_6/log) test, defining the critical path, if that could be improved it would be good.

### CODE REVIEW

**Review by yeounoh — APPROVED** [review]
LGTM, thanks

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by JackCaoG** [comment]
Let's give this pr another try :D

**Comment by will-cromar** [comment]
The CI is broken on master after this PR, e.g. https://app.circleci.com/pipelines/github/pytorch/xla/19158/workflows/12ec08aa-6cf3-4534-8a16-dae38c64beee/jobs/47342

**Pull request merged**
