### PR TITLE
Remove stack dump for compiler failure which can happen often

### PR DESCRIPTION
**Pull request by jeffhataws**
When there's a compilation error, the compiler message is lost among lots of dump messages. This change reduces the amount of dump message so that the compiler message can be more prominent.

For example, the following stack trace (mostly useless) will be removed when there compilation error:

```
E     RuntimeError: torch_xla/csrc/xla_graph_executor.cpp:649 : Check failed: tensor_data                                                                                                            
E     *** Begin stack trace ***                                                                                                                                                                   
E       tsl::CurrentStackTrace()                                                                                                                                                                      
E       torch_xla::XLAGraphExecutor::CollectSyncTensors(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c
10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&)                 
E       torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::alloc
ator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230802::Span<std::string const>, torch::lazy::LazyGraphExecuto
r::SyncTensorsConfig const&, bool)                                                                                                                                                                    
E       torch_xla::XLAGraphExecutor::SyncTensorsGraph(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10
::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230802::Span<std::string const>, bool, bool, bool)                    
E       torch_xla::XLAGraphExecutor::SyncLiveTensorsGraph(torch::lazy::BackendDevice const*, c10::ArrayRef<std::string>, bool)                                                                        
E                                                
E                                                
E                                                
E                                                
E       _PyObject_MakeTpCall                     
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyObject_FastCallDictTstate             
E       _PyObject_Call_Prepend                   
E                                                
E       _PyObject_MakeTpCall                     
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyObject_FastCallDictTstate             
E       _PyObject_Call_Prepend                   
E                                                
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyObject_FastCallDictTstate             
E       _PyObject_Call_Prepend                   
E                                                
E       _PyObject_MakeTpCall                     
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyObject_FastCallDictTstate             
E       _PyObject_Call_Prepend                   
E                                                
E       _PyObject_MakeTpCall                     
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       PyObject_Call                            
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyObject_FastCallDictTstate             
E       _PyObject_Call_Prepend                   
E                                                
E       _PyObject_MakeTpCall                     
E       _PyEval_EvalFrameDefault                 
E       _PyFunction_Vectorcall                   
E       _PyEval_EvalFrameDefault                 
E                                                
E       PyEval_EvalCode                          
E                                                
E                                                
E                                                
E       _PyRun_SimpleFileObject                  
E       _PyRun_AnyFileObject                     
E       Py_RunMain                               
E       Py_BytesMain                             
E       __libc_start_main                        
E       _start                                   
E     *** End stack trace ***                    
                                        
```

### CODE REVIEW

**Review by JackCaoG — COMMENTED** [review]
LGTM, @jeffhataws if you can attach a compilation error message after your change I think we are ready to merge this one.

**Comment by JackCaoG** [comment]
I will merge this one now so it can be part of the release. Please attach an example error log later.

**Review by JackCaoG — APPROVED** [review]

**Comment by jeffhataws** [comment]
I fixed the error dump in https://github.com/pytorch/xla/pull/7207#issue-2337350629 (previously it was for another error in GSPMD).

Strange, I was able to see https://github.com/pytorch/xla/pull/7207#issue-2337350629 with torch-xla 2.2 when there's an internal compiler error, but I don't see it with torch-xla 2.3 anymore. Let me do some sanity checks. Maybe we didn't need this change after all in TOT.

**Comment by jeffhataws** [comment]
Ok with fresh installation of public torch-xla 2.3 (without this change), I only see the following error without the stack dump, 
```
RuntimeError: Bad StatusOr access: INTERNAL: RunNeuronCCImpl: error condition error != 0: <class 'subprocess.CalledProcessError'>: Command '' died with <Signals.SIGHUP: 1>.
```
So likely this change is not needed at least for torch-xla 2.3.

If you have a test case that triggers the CPU compilation error, let me know and I can retest with TOT.

**Comment by jeffhataws** [comment]
I found that @will-cromar  has a cleaner fix here already for 2.3 https://github.com/pytorch/xla/pull/6707 . That explains why I don't see the stack trace for torch-xla 2.3. So this change is not needed. @JackCaoG  let me know if you can revert it.

**Pull request merged**
