### PR TITLE
Scope test

### PR DESCRIPTION
**Pull request by JackCaoG**
Upstream https://github.com/pytorch/pytorch/pull/87005

### CODE REVIEW

**Review by alanwaketan — COMMENTED** [review]
The test case itself looks good to me.

However, any chances we can have this test case in the upstream? It seems weird that we have the implementation and test case in different places.

**Review by alanwaketan — APPROVED** [review]

**Comment by JackCaoG** [comment]
> The test case itself looks good to me.
> 
> However, any chances we can have this test case in the upstream? It seems weird that we have the implementation and test case in different places.

I didn't find where python lazy test is. I also don't know if upstream has equivalant of `xp.trace`.

**Comment by alanwaketan** [comment]
LTC has its python test here: https://github.com/pytorch/pytorch/blob/master/test/lazy/test_reuse_ir.py#L1. I don't think it has profiler though...

**Comment by JackCaoG** [comment]
alternative solution is to write a CPP test for LTC

**Comment by alanwaketan** [comment]
If it's too hard, then I will say just forgo it.

**Pull request merged**
