### PR TITLE
Add resnet50-weight-quant colab notebook

### PR DESCRIPTION
**Pull request by lsy323**
Colab Notebook is also at: https://colab.sandbox.google.com/drive/1CuJvVGDmp22kIFnk2uLvLZ-Vy_voiwVd#scrollTo=Ef7SRB11dFYD

This is an notebook with an example of applying weight-only quantization on the fully-connected layer of a pre-trained ResNet50 model. The quantization result is verified on a dog image, for demo purpose.

### CODE REVIEW

**Comment by lsy323** [comment]
Seems Jupyter notebook is not viewable in "File changed" tab, please see the notebook at: https://github.com/pytorch/xla/blob/lsiyuan/resnet50-weight-only-quant-guide/contrib/colab/resnet50-weight-quant.ipynb

or https://colab.sandbox.google.com/drive/1CuJvVGDmp22kIFnk2uLvLZ-Vy_voiwVd#scrollTo=Ef7SRB11dFYD

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Review by miladm — APPROVED** [review]
LGTM. Thanks! 

@ManfeiBai @wonjoolee95 does this PR qualify to cherrypicking into 2.1 release?

**Comment by ManfeiBai** [comment]
> https://colab.sandbox.google.com/drive/1CuJvVGDmp22kIFnk2uLvLZ-Vy_voiwVd#scrollTo=Ef7SRB11dFYD

thanks, has reviewed the `Colab Notebook`, do we need any other PRs need to be cherrypicked into 2.1 release to enable this Notebook?

cc @lsy323

**Comment by wonjoolee95** [comment]
This only touches the `colab` notebook, so in terms of regression, there is no concern with cherry-picking onto the 2.1 branch.

**Comment by miladm** [comment]
I find this document a valuable artifact around our quantization story in this release. It has the potential to offer an additional update to our release note for those looking to gain access to quant support in torch_xla. I'd vote to include this PR in the release. Wdyt @wonjoolee95?

**Comment by wonjoolee95** [comment]
> I find this document a valuable artifact around our quantization story in this release. It has the potential to offer an additional update to our release note for those looking to gain access to quant support in torch_xla. I'd vote to include this PR in the release. Wdyt @wonjoolee95?

Makes sense. Sg, I agree with merging this in. @lsy323, can we merge this PR to master first?

**Pull request merged**
