### PR TITLE
Remove old TPU CI

### PR DESCRIPTION
**Pull request by will-cromar**
We have a much better solution now thanks to @mbzomowski!

Terraform plan:

<details>

```
Terraform will perform the following actions:

  # module.v4_arc_cluster.google_container_cluster.arc_v4_cluster will be updated in-place
  ~ resource "google_container_cluster" "arc_v4_cluster" {
        id                                       = "projects/tpu-pytorch/locations/us-central2/clusters/tpu-ci"
        name                                     = "tpu-ci"
        # (29 unchanged attributes hidden)

        # (19 unchanged blocks hidden)
    }

  # module.v4_arc_cluster.helm_release.arc will be updated in-place
  ~ resource "helm_release" "arc" {
        id                         = "actions-runner-controller"
        name                       = "actions-runner-controller"
        # (26 unchanged attributes hidden)
    }

  # module.v4_arc_cluster.helm_release.arc_runner_set will be updated in-place
  ~ resource "helm_release" "arc_runner_set" {
        id                         = "v4-runner-set"
        name                       = "v4-runner-set"
        # (27 unchanged attributes hidden)
    }

  # module.tpu_e2e_tests.module.cloud_build.google_cloudbuild_trigger.trigger will be destroyed
  # (because google_cloudbuild_trigger.trigger is not in configuration)
  - resource "google_cloudbuild_trigger" "trigger" {
      - create_time        = "2023-04-20T11:18:07.966860879Z" -> null
      - description        = "Run e2e TPU tests on an image built from master branch. Trigger managed by Terraform setup in infra/tpu-pytorch/test_triggers.tf." -> null
      - disabled           = false -> null
      - id                 = "projects/tpu-pytorch/triggers/8e11b2bb-f1f1-4d48-ac05-315f16d15c5d" -> null
      - ignored_files      = [] -> null
      - include_build_logs = "INCLUDE_BUILD_LOGS_WITH_STATUS" -> null
      - included_files     = [] -> null
      - location           = "global" -> null
      - name               = "ci-tpu-test-trigger" -> null
      - project            = "tpu-pytorch" -> null
      - substitutions      = {
          - "_CLUSTER_NAME" = "tpu-cluster"
          - "_CLUSTER_ZONE" = "europe-west4-a"
        } -> null
      - tags               = [] -> null
      - trigger_id         = "8e11b2bb-f1f1-4d48-ac05-315f16d15c5d" -> null

      - approval_config {
          - approval_required = false -> null
        }

      - build {
          - images        = [] -> null
          - substitutions = {} -> null
          - tags          = [] -> null
          - timeout       = "14400s" -> null

          - options {
              - disk_size_gb           = 0 -> null
              - dynamic_substitutions  = true -> null
              - env                    = [] -> null
              - secret_env             = [] -> null
              - source_provenance_hash = [] -> null
              - substitution_option    = "ALLOW_LOOSE" -> null
              - worker_pool            = "projects/tpu-pytorch/locations/us-central1/workerPools/main" -> null
            }

          - step {
              - allow_exit_codes = [] -> null
              - allow_failure    = false -> null
              - args             = [
                  - "fetch",
                  - "--unshallow",
                ] -> null
              - env              = [] -> null
              - id               = "git_fetch" -> null
              - name             = "gcr.io/cloud-builders/git" -> null
              - secret_env       = [] -> null
              - wait_for         = [] -> null
            }
          - step {
              - allow_exit_codes = [] -> null
              - allow_failure    = false -> null
              - args             = [
                  - "checkout",
                  - "$COMMIT_SHA",
                ] -> null
              - env              = [] -> null
              - id               = "git_checkout" -> null
              - name             = "gcr.io/cloud-builders/git" -> null
              - secret_env       = [] -> null
              - wait_for         = [] -> null
            }
          - step {
              - allow_exit_codes = [] -> null
              - allow_failure    = false -> null
              - args             = [
                  - "-c",
                  - "docker build --progress=plain --network=cloudbuild -f=e2e_tests.Dockerfile . --build-arg=python_version=3.10 --build-arg=ansible_vars='{\"accelerator\":\"tpu\",\"arch\":\"amd64\",\"pytorch_git_rev\":\"main\",\"xla_git_rev\":\"$COMMIT_SHA\"}' -t=\"us-central1-docker.pkg.dev/tpu-pytorch/docker/pytorch-xla-test:$(echo $BUILD_ID)\" -t=local_image",
                ] -> null
              - dir              = "infra/ansible" -> null
              - entrypoint       = "bash" -> null
              - env              = [] -> null
              - id               = "build_pytorch-xla-test_docker_image" -> null
              - name             = "gcr.io/cloud-builders/docker" -> null
              - secret_env       = [] -> null
              - wait_for         = [] -> null
            }
          - step {
              - allow_exit_codes = [] -> null
              - allow_failure    = false -> null
              - args             = [
                  - "-c",
                  - "docker push --all-tags us-central1-docker.pkg.dev/tpu-pytorch/docker/pytorch-xla-test",
                ] -> null
              - entrypoint       = "bash" -> null
              - env              = [] -> null
              - id               = "push_pytorch-xla-test_docker_image" -> null
              - name             = "gcr.io/cloud-builders/docker" -> null
              - secret_env       = [] -> null
              - wait_for         = [] -> null
            }
          - step {
              - allow_exit_codes = [] -> null
              - allow_failure    = false -> null
              - args             = [
                  - "-c",
                  - <<-EOT
                        set -u # Fail if any variables are unset.
                                  set -e # Exit immediately if any command fails.
                                  set -x # Print executed commands.
                        
                                  apt-get update
                                  apt-get -y install gettext
                        
                                  gcloud container clusters get-credentials $_CLUSTER_NAME --zone $_CLUSTER_ZONE
                        
                                  # Export variables to shell environment so that we can pass them into the
                                  # k8s deployment using envsubst
                                  export IMAGE=us-central1-docker.pkg.dev/tpu-pytorch/docker/pytorch-xla-test:$BUILD_ID
                                  export PROJECT_ID=$PROJECT_ID
                        
                                  # Launch k8s deployment, wait for completion, print logs
                                  pod_name=$(envsubst < test/tpu/xla_test_job.yaml | kubectl create -f - -o name)
                                  pod_name=$(kubectl wait --for condition=ready --timeout=60m $pod_name -o name)
                                  kubectl logs -f $pod_name --container=xla-test
                        
                                  exit $(kubectl get $pod_name -o jsonpath='{.status.containerStatuses[?(@.name=="xla-test")].state.terminated.exitCode}')
                    EOT,
                ] -> null
              - entrypoint       = "bash" -> null
              - env              = [] -> null
              - id               = "run_e2e_tests" -> null
              - name             = "google/cloud-sdk" -> null
              - secret_env       = [] -> null
              - wait_for         = [] -> null
            }
        }

      - github {
          - name  = "xla" -> null
          - owner = "pytorch" -> null

          - push {
              - branch       = "^master$" -> null
              - invert_regex = false -> null
            }
        }
    }

Plan: 0 to add, 3 to change, 1 to destroy.
```
</details>

I'm 90% sure the 3 "changed" resources are no-ops. @mbzomowski can you confirm?

### CODE REVIEW

**Comment by JackCaoG** [comment]
Does GKE has any v2 or v3s? Colab will move to TPUVM soon but I am not sure if they will get newer versions of TPUVMs. I want to at least have some coverages for them. 

For example we didn;t know pallas doesn't work on v2 and v3 until we see the TPU CI failed.

**Comment by will-cromar** [comment]
The old TPUs are not listed in the public documentation: https://cloud.google.com/tpu/docs/tpus-in-gke#tpu-machine-types

The best we can do is "simulate" them by modifying the topology on v4, e.g. `TPU_PROCESS_BOUNDS=1,1,1 TPU_CHIPS_PER_PROCESS_BOUNDS=2,2,1`. This is what I do on my TPU v4 dev machine.

**Comment by will-cromar** [comment]
Added a multithreaded v4 test to see if it catches the current error

**Comment by will-cromar** [comment]
Unfortunately(?) the new CI config I added did pass, so it's not representative of TPU v3 in this case.

**Comment by mbzomowski** [comment]
@will-cromar yeah those look like no-ops to me. Should be fine

**Comment by will-cromar** [comment]
The TPU tests now build on a CPU machine, so it shows up in the `build_and_test` workflow.

My last comment was wrong -- I just had a condition backward. My threading hack does catch the current error.

**Pull request closed without merging**
