### PR TITLE
Handle view updates which are simple reshapes.

### PR DESCRIPTION
**Pull request by dlibenzi**
This fixes the issues with the transpose PR.

### CODE REVIEW

**Comment by asuhan** [comment]
Which PR is that?

**Comment by dlibenzi** [comment]
> Which PR is that?

Yours.

**Comment by asuhan** [comment]
Ok, I assume you mean https://github.com/pytorch/xla/compare/asuhan/permute_view_fix and that this addresses view followed by in-place squeeze. Let me have a look.

**Comment by dlibenzi** [comment]
> Ok, I assume you mean https://github.com/pytorch/xla/compare/asuhan/permute_view_fix and that this addresses view followed by in-place squeeze. Let me have a look.

Yes, you can drop all the custom "squeeze" handling in tensor.cpp and view.*

**Comment by dlibenzi** [comment]
> Looks good. This should work with unsqueeze as well, right?

Better be :)

**Pull request merged**
