### PR TITLE
Use reduce-scatter coalescing for FSDP

### PR DESCRIPTION
**Pull request by jeffhataws**
This PR uses [reduce-scatter coalescence](https://github.com/pytorch/xla/pull/5956) in FSDP in addition to reduce-scatter's scale param. This PR is companion to https://github.com/pytorch/xla/pull/5950 and https://github.com/pytorch/xla/pull/5956 and to be used in conjunction with openxla https://github.com/openxla/xla/pull/5740 .

This is a revival of https://github.com/pytorch/xla/pull/4145.

### CODE REVIEW

**Comment by alanwaketan** [comment]
I guess we need to rebase to the master once the dependent PR is landed?

**Comment by jeffhataws** [comment]
> I guess we need to rebase to the master once the dependent PR is landed?

I had rebased over the dependent PR https://github.com/pytorch/xla/pull/5956

**Review by alanwaketan — COMMENTED** [review]
The change makes a lot of sense to support coalescing reduce-scatter. Just one question, what if I don't need this feature and want to preserve the initial behavior where  the reduce-scatter is fired immediately?

I wish I have the resources to perform through-out performance tests in TPU but...

Therefore, will it be possible to add this as an optional feature?

**Comment by alanwaketan** [comment]
Let me know when it's ready for review?

**Comment by JackCaoG** [comment]
@alanwaketan can you take a look at this one?

**Pull request merged**
