### PR TITLE
Migrate to upstream torch::lazy OpKind, Node, Value, and Output

### PR DESCRIPTION
**Pull request by wonjoolee95**
[WIP] Migrate to upstream torch::lazy OpKind, Node, Value, and Output.

This PR has gotten a bit big due to `torch::lazy::OpKind` migration that was required for the IR related classes. The most important changes are in the `ir.h` file, specifically the new `Node`, `Value` and `Output` classes.

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Builds succeeds on cloudtop but fails on CircleCI:
```
FAILED: /tmp/pytorch/xla/build/temp.linux-x86_64-3.7/torch_xla/csrc/ir.o 
clang++-8 -MMD -MF /tmp/pytorch/xla/build/temp.linux-x86_64-3.7/torch_xla/csrc/ir.o.d -Wsign-compare -DNDEBUG -g 
...
/tmp/pytorch/xla/torch_xla/csrc/ir.cpp:104:7: error: no matching constructor for initialization of 'torch::lazy::Node'
    : torch::lazy::Node(op, num_outputs, hash_seed),
```

Seems like there is a change in PyTorch. Trying to pull the latest in PyTorch and rebuild on cloudtop.

**Comment by wonjoolee95** [comment]
Builds successfully but currently CPU and GPU tests failing with:
```
+ python3 /tmp/pytorch/xla/test/../../test/test_view_ops.py -v TestViewOpsXLA
Traceback (most recent call last):
  File "/tmp/pytorch/xla/test/../../test/test_view_ops.py", line 16, in <module>
    from torch.testing._internal.common_device_type import \
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 560, in <module>
    mod = runpy.run_path(path, init_globals=globals())  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/pytorch/xla/test/pytorch_test_base.py", line 8, in <module>
    import torch_xla
  File "/opt/conda/lib/python3.7/site-packages/torch_xla-1.11-py3.7-linux-x86_64.egg/torch_xla/__init__.py", line 102, in <module>
    import _XLAC
ImportError: /opt/conda/lib/python3.7/site-packages/torch_xla-1.11-py3.7-linux-x86_64.egg/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK9torch_xla2ir6Output6HasherclERKS1_
```

**Comment by wonjoolee95** [comment]
Can reproduce the issue locally while trying to import `torch_xla`:
```
>>> import torch_xla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/wonjoo/anaconda3/lib/python3.8/site-packages/torch_xla-1.11-py3.8-linux-x86_64.egg/torch_xla/__init__.py", line 104, in <module>
    import _XLAC
ImportError: /usr/local/google/home/wonjoo/anaconda3/lib/python3.8/site-packages/torch_xla-1.11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK9torch_xla2ir6Output6HasherclERKS1_
```

Seems caused by this PR, as running with `master` branch works fine locally. Looking more into it.

**Comment by JackCaoG** [comment]
> Builds successfully but currently CPU and GPU tests failing with:
> 
> ```
> + python3 /tmp/pytorch/xla/test/../../test/test_view_ops.py -v TestViewOpsXLA
> Traceback (most recent call last):
>   File "/tmp/pytorch/xla/test/../../test/test_view_ops.py", line 16, in <module>
>     from torch.testing._internal.common_device_type import \
>   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 560, in <module>
>     mod = runpy.run_path(path, init_globals=globals())  # type: ignore[func-returns-value]
>   File "/opt/conda/lib/python3.7/runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/tmp/pytorch/xla/test/pytorch_test_base.py", line 8, in <module>
>     import torch_xla
>   File "/opt/conda/lib/python3.7/site-packages/torch_xla-1.11-py3.7-linux-x86_64.egg/torch_xla/__init__.py", line 102, in <module>
>     import _XLAC
> ImportError: /opt/conda/lib/python3.7/site-packages/torch_xla-1.11-py3.7-linux-x86_64.egg/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK9torch_xla2ir6Output6HasherclERKS1_
> ```

This usually means you have this function defined in the header but it couldn't find the implementation. Search for `torch_xla2ir6Output6Hasher`

**Comment by JackCaoG** [comment]
I think we don't need this pr anymore

**Pull request closed without merging**
