### PR TITLE
Codegen Rsqrt

### PR DESCRIPTION
**Pull request by vanbasten23**
Generated LazyIr.h
```
class Rsqrt : public XlaNode {
 public:
  static torch::lazy::OpKind ClassOpKind() {
    return torch::lazy::OpKind(at::aten::rsqrt);
  }

  Rsqrt(const torch::lazy::Value& self, std::vector<torch::lazy::Shape>&& shapes)
      : XlaNode(torch::lazy::OpKind(at::aten::rsqrt),
              {self}, std::move(shapes),
              [&]() { return RsqrtOutputShape(self); },
              /* num_outputs */ 1,
              torch::lazy::MHash())
  {
    
  }

  std::string ToString() const override {
    std::stringstream ss;
    ss << XlaNode::ToString();
    
    return ss.str();
  }

  

  bool CanBeReused(const torch::lazy::Value& self) const {
    return false;
    }

  torch_xla::XlaOpVector Lower(LoweringContext* loctx) const override;

};
```

Generate XLANativeFunctions.cpp
```
    at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self) {
        
        XLA_FN_COUNTER("xla::");
        auto common_device = torch_xla::bridge::GetXlaDevice(self);
        TORCH_INTERNAL_ASSERT(common_device);
        
        torch_xla::XLATensorPtr lazy_self = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(self, *common_device);
        torch::lazy::NodePtr node = torch::lazy::ReuseNode<Rsqrt>(lazy_self->GetIrValue());
        if (!node) {
                    auto self_meta = to_meta(self);
        auto out_meta = at::meta::rsqrt(self_meta);
        
std::vector<torch::lazy::Shape> shapes{torch::lazy::Shape(out_meta.scalar_type(), out_meta.sizes().vec())};
            TORCH_INTERNAL_ASSERT(shapes.size() == 1);
            if(torch::lazy::symbolicShapeEnabled()){
                std::vector<torch::jit::IValue> inputs = { self };
                const char* schema_str = "aten::rsqrt(Tensor self) -> Tensor";
                applySymbolicShapesOnLT(schema_str, inputs, shapes);
            }
        
            node = torch::lazy::MakeNode<Rsqrt>(lazy_self->GetIrValue(), std::move(shapes));
            CacheNode(node);
        }
        
        auto result = torch_xla::bridge::AtenFromXlaTensor(
                torch_xla::XLATensor::Create(std::move(node), *common_device));
        return result;
    };
```

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Thanks! Looks good, I'll let the CI do the rest.

**Review by yeounoh — APPROVED** [review]
LGTM

**Comment by vanbasten23** [comment]
@yeounoh and @wonjoolee95 , just want to check with you some quick questions:
1. For the function `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` generated in  XLANativeFunctions.cpp, who is the caller of this function?
2. For the class `class Rsqrt : public XlaNode` generated in LazyIr.h, I guess the caller who instantiate this class is `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` from XLANativeFunctions.cpp via 
`torch::lazy::NodePtr node = torch::lazy::ReuseNode<Rsqrt>(lazy_self->GetIrValue());`. Is that correct?
3. Is there a way to print something (cout) from the generated files such as XLANativeFunctions.cpp?

**Comment by JackCaoG** [comment]
> @yeounoh and @wonjoolee95 , just want to check with you some quick questions:
> 
> 1. For the function `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` generated in  XLANativeFunctions.cpp, who is the caller of this function?
Pytorch core calls it when corresponding python function is being called and at least one of the input tensor is on xla device. You can use a gdb and set break point on this function then manully run a python script with this command to verify.

> 2. For the class `class Rsqrt : public XlaNode` generated in LazyIr.h, I guess the caller who instantiate this class is `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` from XLANativeFunctions.cpp via
>    `torch::lazy::NodePtr node = torch::lazy::ReuseNode<Rsqrt>(lazy_self->GetIrValue());`. Is that correct?
yes

> 3. Is there a way to print something (cout) from the generated files such as XLANativeFunctions.cpp?
commented out https://github.com/pytorch/xla/blob/master/setup.py#L249 so setup script won't try to regerenate this file. Then you can add whatever print you want.

**Comment by vanbasten23** [comment]
> > @yeounoh and @wonjoolee95 , just want to check with you some quick questions:
> > 
> > 1. For the function `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` generated in  XLANativeFunctions.cpp, who is the caller of this function?
> 
> Pytorch core calls it when corresponding python function is being called and at least one of the input tensor is on xla device. You can use a gdb and set break point on this function then manully run a python script with this command to verify.
> 
> > 2. For the class `class Rsqrt : public XlaNode` generated in LazyIr.h, I guess the caller who instantiate this class is `at::Tensor XLANativeFunctions::rsqrt(const at::Tensor & self)` from XLANativeFunctions.cpp via
> >    `torch::lazy::NodePtr node = torch::lazy::ReuseNode<Rsqrt>(lazy_self->GetIrValue());`. Is that correct?
> 
> It is `node = torch::lazy::MakeNode<Rsqrt>(lazy_self->GetIrValue(), std::move(shapes));` actually. I don't think we support ReuseNode yet.
> 
> > 3. Is there a way to print something (cout) from the generated files such as XLANativeFunctions.cpp?
> 
> commented out https://github.com/pytorch/xla/blob/master/setup.py#L249 so setup script won't try to regerenate this file. Then you can add whatever print you want.

Thanks, Jack!

**Pull request merged**
