### PR TITLE
Choose optimal TPU layout for all ranks for which makes sense.

### PR DESCRIPTION
**Pull request by dlibenzi**

### CODE REVIEW

**Comment by dlibenzi** [comment]
> I'm not sure this is going to work well for 4-D tensors. We could easily end with spatial dimensions being most minor, pretty sure this would happen for ResNet-50 inputs -- spatial dimensions are bigger than both batch size and channels. I'd rather preserve the current logic for 4-D tensors at least.

I have actually tested this with resnet50 explicitly.

**Comment by dlibenzi** [comment]
> > I'm not sure this is going to work well for 4-D tensors. We could easily end with spatial dimensions being most minor, pretty sure this would happen for ResNet-50 inputs -- spatial dimensions are bigger than both batch size and channels. I'd rather preserve the current logic for 4-D tensors at least.
> 
> I have actually tested this with resnet50 explicitly.

But I do see more logic going in, in that area. This is why I created a new file for it.

**Comment by asuhan** [comment]
So what happens with ResNet-50? The spatial dimensions become most minor, right? This will lead to layout adjusting copies, which can't be good.

**Comment by dlibenzi** [comment]
> So what happens with ResNet-50? The spatial dimensions become most minor, right? This will lead to layout adjusting copies, which can't be good.

Performance was same if not higher. But claiming higher is a bit of a stretch with the variance we have seen.
```
[xla:4](80) Loss=0.67050 Rate=508.40
[xla:2](100) Loss=0.36499 Rate=518.22
[xla:5](100) Loss=0.36741 Rate=517.12
[xla:7](100) Loss=0.36131 Rate=518.29
[xla:3](100) Loss=0.35726 Rate=518.64
[xla:8](100) Loss=0.36066 Rate=518.11
[xla:6](100) Loss=0.35844 Rate=517.97
[xla:4](100) Loss=0.36575 Rate=517.50
[xla:1](100) Loss=0.35794 Rate=518.16
[xla:6](120) Loss=0.23224 Rate=511.47
[xla:5](120) Loss=0.23840 Rate=510.88
[xla:4](120) Loss=0.23726 Rate=512.01
[xla:1](120) Loss=0.23190 Rate=511.23
[xla:3](120) Loss=0.23144 Rate=510.72
[xla:2](120) Loss=0.23674 Rate=512.16
[xla:8](120) Loss=0.23377 Rate=511.79
[xla:7](120) Loss=0.23422 Rate=511.00
[xla:4](140) Loss=0.17205 Rate=522.59
[xla:1](140) Loss=0.16803 Rate=523.29
[xla:6](140) Loss=0.16829 Rate=522.77
[xla:3](140) Loss=0.16768 Rate=524.09
[xla:7](140) Loss=0.16977 Rate=523.34
[xla:5](140) Loss=0.17290 Rate=522.88
[xla:2](140) Loss=0.17166 Rate=523.53
[xla:8](140) Loss=0.16943 Rate=522.90
```

**Comment by asuhan** [comment]
Are these numbers with real tensors transferred all the way from the host or fake data? Going by my previous experience with smarter layout heuristics for rank-4 tensors, I'm not 100% comfortable with this.

**Comment by dlibenzi** [comment]
> Are these numbers with real tensors transferred all the way from the host or fake data? Going by my previous experience with smarter layout heuristics for rank-4 tensors, I'm not 100% comfortable with this.

Compared apples-to-apples. Not sending data to device, which puts even more in evidence the core TPU exec time.

**Comment by asuhan** [comment]
This is not uniformly better in terms of padding either. If batches are 128 x 3 x 229 x 229, we would have a bunch of padding we wouldn't have with the current approach.

**Comment by dlibenzi** [comment]
> This is not uniformly better in terms of padding either. If batches are 128 x 3 x 229 x 229, we would have a bunch of padding we wouldn't have with the current approach.

Sure. I can play the game all day long showing how many cases the current blind-folded layout picker can fall into :)

**Comment by dlibenzi** [comment]
> But 4-D tensors _are_ special for image networks, which we've focused on so far. We know we're going to have batch, feature and spatial dimensions for inputs to such networks. Letting spatial dimensions be most minor worries me quite a bit. We'll see how this goes, at least it's reasonably easy to undo the heuristic change if we need to.

As I said, I think that file will grow a bit, to have a better heuristic.
We can improve heuristic, and also allow user overrides via environment.

**Pull request merged**
