### PR TITLE
Pull latest changes for TensorFlow

### PR DESCRIPTION
**Pull request by wonjoolee95**

### CODE REVIEW

**Comment by JackCaoG** [comment]
@wonjoolee95 You should delete https://github.com/pytorch/xla/blob/master/tf_patches/multi_load_libtpu.diff after tf update

**Comment by wonjoolee95** [comment]
Seems like `xla` int types (such as `xla::int64`) were removed and replaced with `_t` int types on [XLA's side with this commit](https://github.com/tensorflow/tensorflow/commit/3be1930b0b1f5704f02e6aa9a65e91c0c9b646c3#diff-2635eb77ab721a419df5481a972b36814fe7ba036218dc60cd9bf12a5844197a). As a result of this change, we (PyTorch/XLA) who consume them in `third_party/tensorflow` saw build failures and had to update all our usages of `xla` int types.

**Comment by miladm** [comment]
Just had a chat with Blake. TF changes are here to stay and these data types are to be replaced with `std::X_t`.

**Comment by wonjoolee95** [comment]
Opened new PR -- https://github.com/pytorch/xla/pull/3298.

**Pull request closed without merging**
