### PR TITLE
Update notebooks with version changing capability

### PR DESCRIPTION
**Pull request by jysohn23**
Only changes the first installation cell which will look like the following dropdown and change both client and server-side installations on Colab:
Screen Shot 2019-11-19 at 10 38 25 AM

`torch_xla==0.5` not included as MP API with spawn patches didn't make it.

### CODE REVIEW

**Comment by jysohn23** [comment]
Looks like `X10-serialization.diff` patch is failing to apply. Looking whether upstream actually changed.

**Comment by jysohn23** [comment]
> Does it makes any sense to confine this common code in a module, and re-use it?
> Might reduce the clutter at the beginning of the Colab?

We *could* do that but then the question would be where do we place that module? We can't place that module within `torch_xla` since we'd need to install it before we can run the module which doesn't make sense. Maybe Colab built-in? But that'd need some more future discussion with the Colab team, so I think as is makes sense for now? WDYT?

**Comment by dlibenzi** [comment]
> > Does it makes any sense to confine this common code in a module, and re-use it?
> > Might reduce the clutter at the beginning of the Colab?
> 
> We _could_ do that but then the question would be where do we place that module? We can't place that module within `torch_xla` since we'd need to install it before we can run the module which doesn't make sense. Maybe Colab built-in? But that'd need some more future discussion with the Colab team, so I think as is makes sense for now? WDYT?

No idea. Does Colab provide support for re-usable modules?
Ask Ami?
I am going to ACK this PR, but it'd be nice if you could follow up with Colab folks about whether this is possible.

**Comment by jysohn23** [comment]
> No idea. Does Colab provide support for re-usable modules?
> Ask Ami?
> I am going to ACK this PR, but it'd be nice if you could follow up with Colab folks about whether this is possible.

Will follow up on general `torch_xla` integration with them since I agree the setup is getting unwieldy.

**Pull request merged**
