### PR TITLE
Bazel build issue patch

### PR DESCRIPTION
**Pull request by yeounoh**
Address #3569 , `bazel==5.1.1` introduced this error where bazel build corrupts build cache (both local and remote) during external builds (e.g., llvm). The issue seems to be confined to only `clang` `clang++` uses [issue](https://github.com/bazelbuild/bazel/issues/15359), but I was able to resolve with the (pre-release) `bazel==5.2.0`. Until `tensorflow` bumps up the bazel requirement, this patch should serve us to avoid build speed regression. 

Also, I had to unset `CC` and `CXX` for tensorflow build. This is still related to the bazel's `clang` `clang++` issue.

Bazel 5.2.0 will release after 5/23/22.

### CODE REVIEW

**Comment by yeounoh** [comment]
Tested in the [upstream](https://github.com/pytorch/pytorch/runs/6458151391?check_suite_focus=true) and passed.

**Review by will-cromar — APPROVED** [review]

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by yeounoh** [comment]
I actually saw a failure again in the upstream, let me investigate further before merging.

**Comment by yeounoh** [comment]
Ok, it passed both downstream & upstream CI tests, and builds much faster on Cloud TPU VM, I don't see much improvement on circleci build, though -- re-enabling cloud cache before merging.

**Comment by JackCaoG** [comment]
@yeounoh Is this pr ready to merge?

**Comment by yeounoh** [comment]
> @yeounoh Is this pr ready to merge?

@JackCaoG  not yet, we need to land this PyTorch [PR](https://github.com/pytorch/pytorch/pull/77729) first, disabling the build cache in the upstream. I will ping Eli tomorrow morning to land that, and land this afterwards.

**Comment by yeounoh** [comment]
This also addressed [github/pytorch#77286](https://github.com/pytorch/pytorch/issues/77286)

**Pull request merged**
