### PR TITLE
[SPMD] Fix reduce_scatter for TPUv2

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
Fix reduce_scatter test for TPUv2

Test Plan:
python test/spmd/test_xla_sharding.py -v -k test_spmd_reduce_scatter

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Comment by alanwaketan** [comment]
Things still don't work. Not sure why... I will just skip that...

**Comment by JackCaoG** [comment]
hmm it still failed
```
Step #4 - "run_e2e_tests": ======================================================================
Step #4 - "run_e2e_tests": FAIL: test_spmd_reduce_scatter_canonical_index (__main__.BasicXlaShardingTest)
Step #4 - "run_e2e_tests": ----------------------------------------------------------------------
Step #4 - "run_e2e_tests": Traceback (most recent call last):
Step #4 - "run_e2e_tests":   File "/src/pytorch/xla/test/spmd/test_xla_sharding.py", line 1256, in test_spmd_reduce_scatter_canonical_index
Step #4 - "run_e2e_tests":     self.assertTrue(torch.allclose(x.cpu(), expected_x))
Step #4 - "run_e2e_tests": AssertionError: False is not true
Step #4 - "run_e2e_tests": 
Step #4 - "run_e2e_tests": ----------------------------------------------------------------------
Step #4 - "run_e2e_tests": Ran 63 tests in 3.981s
Step #4 - "run_e2e_tests": 
Step #4 - "run_e2e_tests": FAILED (failures=2, skipped=2)
Step #4 - "run_e2e_tests": ++ kubectl get pod/xla-test-job-4jx6c -o 'jsonpath={.status.containerStatuses[?(@.name=="xla-test")].state.terminated.exitCode}'
Step #4 - "run_e2e_tests": + exit 1
Finished Step #4 - "run_e2e_tests"```

**Comment by alanwaketan** [comment]
Added some debug prints and let's see...

**Comment by alanwaketan** [comment]
The error doesn't seem to be related. Let me rebase.

**Comment by alanwaketan** [comment]
Okay, TPU CI pass. Let me land this direclty with a small update.

**Pull request merged**
