### PR TITLE
Rename torch_xla::ir Node to XlaNode and Value to XlaValue

### PR DESCRIPTION
**Pull request by wonjoolee95**
As brought up in a previous PR, this PR renames `torch_xla::ir::Node` to `XlaNode` and `torch_xla::ir::Value` to `XlaValue` to avoid confusion with upstream `torch::lazy` `Node` and `Value`.

### CODE REVIEW

**Comment by JackCaoG** [comment]
@wonjoolee95 thanks, give me a ping when this pr is ready to be reviewed

**Review by JackCaoG — APPROVED** [review]
LGTM. Thanks @wonjoolee95 !

After this one merged, can you also try to get rid of the `torch_xla::ir` and `torch_xla::ir::ops` namespace? It is related to https://github.com/pytorch/xla/issues/3472#issuecomment-1110442107

**Comment by wonjoolee95** [comment]
> LGTM. Thanks @wonjoolee95 !
> 
> After this one merged, can you also try to get rid of the `torch_xla::ir` and `torch_xla::ir::ops` namespace? It is related to [#3472 (comment)](https://github.com/pytorch/xla/issues/3472#issuecomment-1110442107)

Thanks! Will merge once CI is all green.

Sure thing, I can work on that. Quick question @JackCaoG, so for our existing `torch_xla::ir::Node` and other classes, should we directly define them at `torch_xla` namespace?

**Comment by JackCaoG** [comment]
> > LGTM. Thanks @wonjoolee95 !
> > After this one merged, can you also try to get rid of the `torch_xla::ir` and `torch_xla::ir::ops` namespace? It is related to [#3472 (comment)](https://github.com/pytorch/xla/issues/3472#issuecomment-1110442107)
> 
> Thanks! Will merge once CI is all green.
> 
> Sure thing, I can work on that. Quick question @JackCaoG, so for our existing `torch_xla::ir::Node` and other classes, should we directly define them at `torch_xla` namespace?

let's move everything to `torch_xla` namespace for now

**Pull request merged**
