### PR TITLE
Verify if abs support dynamism.

### PR DESCRIPTION
**Pull request by vanbasten23**

### CODE REVIEW

**Review by miladm — COMMENTED** [review]
Wdyt about creating `test/dynamic_shape` to store op-level dynamism tests? we can move all dynamic shape relates script there.

**Comment by vanbasten23** [comment]
> Wdyt about creating `test/dynamic_shape` to store op-level dynamism tests? we can move all dynamic shape relates script there.

Do you mean creating a separate folder dynamic_shape under `test/`?

**Review by alanwaketan — APPROVED** [review]
LGTM. But please also address Milad's comment.

Another option, you can have another test suite within the same file.

**Comment by vanbasten23** [comment]
> > Wdyt about creating `test/dynamic_shape` to store op-level dynamism tests? we can move all dynamic shape relates script there.
> 
> Do you mean creating a separate folder dynamic_shape under `test/`?

Let me do it. Will address it in a follow-up PR.

**Comment by vanbasten23** [comment]
Thanks for the review.

**Comment by vanbasten23** [comment]
> > > Wdyt about creating `test/dynamic_shape` to store op-level dynamism tests? we can move all dynamic shape relates script there.
> > 
> > 
> > Do you mean creating a separate folder dynamic_shape under `test/`?
> 
> Let me do it. Will address it in a follow-up PR.

Created a PR https://github.com/pytorch/xla/pull/4866

**Pull request merged**
