### PR TITLE
Support S32/U32 indices for BWD embedding and index ops & Neuron implicit downcast

### PR DESCRIPTION
**Pull request by rpsilva-aws**
In this PR, we extend tensor operations to allow S32 indices. This follows suits with other operations, in order to add flexibility and potentially performance benefits for accelerator backends. Reference for embedding dense bwd: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/Embedding.cpp#L117

I re-structure a good portion of the tests to validate both types.

In addition, we also re-introduce the implicit downcasting for Neuron S64/U64 types, since the Neuron compiler does not support 64 bits.

### CODE REVIEW

**Comment by miladm** [comment]
is this PR ready for review @rpsilva-aws?

**Comment by rpsilva-aws** [comment]
@miladm Yes, but there seem to be some issues with the test infra - I need to validate with the TPU docker. I can ping once done/fixed.

**Comment by tengyifei** [comment]
Can just ping me again when the "Build and test" has passed

**Comment by rpsilva-aws** [comment]
Unfortunately, part of this PR has a dependency on https://github.com/pytorch/pytorch/pull/142160.

Instead, creating 2 PRs:
- https://github.com/pytorch/xla/pull/8462 (no dependency, partially Neuron-specific)
- https://github.com/pytorch/xla/pull/8463 (PT dependency)

**Pull request closed without merging**
