### PR TITLE
[1/N] Use std::string_view

### PR DESCRIPTION
**Pull request by cyyever**
Another attempt to use STL.

### CODE REVIEW

**Comment by JackCaoG** [comment]
build failures seem real
```

2024-06-16T14:30:11.6423560Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:240:26: error: no matching function for call to 'Hash(std::basic_string_view<char>&)'
2024-06-16T14:30:11.6425004Z       240 |   return HashCombine(Hash(value), MHash(Fargs...));
2024-06-16T14:30:11.6425646Z           |                      ~~~~^~~~~~~
2024-06-16T14:30:11.6427673Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:66:8: note: candidate: 'template<class T, typename std::enable_if<std::is_arithmetic<_Tp>::value>::type* <anonymous> > torch::lazy::hash_t torch::lazy::Hash(const T&)'
2024-06-16T14:30:11.6429447Z        66 | hash_t Hash(const T& value) ***
2024-06-16T14:30:11.6429925Z           |        ^~~~
2024-06-16T14:30:11.6431094Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:66:8: note:   template argument deduction/substitution failed:
2024-06-16T14:30:11.6433071Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:65:68: error: no type named 'type' in 'struct std::enable_if<false, void>'
2024-06-16T14:30:11.6434434Z        65 |     typename std::enable_if<std::is_arithmetic<T>::value>::type* = nullptr>
2024-06-16T14:30:11.6435173Z           |                                                                    ^~~~~~~
2024-06-16T14:30:11.6436671Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:72:18: note: candidate: 'torch::lazy::hash_t torch::lazy::Hash(const std::vector<bool>&)'
2024-06-16T14:30:11.6438023Z        72 | hash_t TORCH_API Hash(const std::vector<bool>& value);
2024-06-16T14:30:11.6438590Z           |                  ^~~~
2024-06-16T14:30:11.6440121Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:72:48: note:   no known conversion for argument 1 from 'std::basic_string_view<char>' to 'const std::vector<bool>&'
2024-06-16T14:30:11.6441585Z        72 | hash_t TORCH_API Hash(const std::vector<bool>& value);
2024-06-16T14:30:11.6442201Z           |                       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
2024-06-16T14:30:11.6443666Z     bazel-out/k8-opt/bin/external/torch/_virtual_includes/headers/torch/csrc/lazy/core/hash.h:75:22: note: candidate: 'torch::lazy::hash_t torch::lazy::Hash(const c10::ScalarType&)'
2024-06-16T14:30:11.6445028Z        75 | static inline hash_t Hash(const c10::ScalarType& value) ***
```

**Comment by cyyever** [comment]
@JackCaoG I have to patch upstream first.

**Comment by cyyever** [comment]
@JackCaoG Upstream changes have been merged.

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
seems OK but the CI was run 2 weeks ago so I am a bit concern about if there will be conflicts etc. @tengyifei can you merge this on Monday and monitor the CI at head?

**Comment by tengyifei** [comment]
Not sure what's going on -- I'm getting build failures but can't find where's the error.

@cyyever is this blocking something (e.g. upstream migration to std types)? I'm a bit worried merging something with test errors could break HEAD when we're about cut a 2.6 release.

**Comment by cyyever** [comment]
@tengyifei Can skip this until I find a way to fix the build problem.

**Comment by tengyifei** [comment]
@cyyever I think the issue is not specific to your PR. All commits today failed to build in CI: https://github.com/pytorch/xla/commits/master/

**Comment by JackCaoG** [comment]
```
2024-12-10T00:53:09.5925030Z     Extracting Bazel installation...
2024-12-10T00:53:09.5925485Z     Starting local Bazel server and connecting to it...
2024-12-10T00:53:09.5926128Z     INFO: Invocation ID: d450b0c2-7eab-4ee3-a334-190a433b1f86
2024-12-10T00:53:09.5926844Z     ERROR: Failed to query remote execution capabilities: UNAVAILABLE: Credentials failed to obtain metadata
2024-12-10T00:53:09.5927845Z     INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/d450b0c2-7eab-4ee3-a334-190a433b1f86
2024-12-10T00:53:09.5928669Z     error: command '/usr/local/bin/bazel' failed with exit code 34
```

**Comment by JackCaoG** [comment]
I think in CI we uses a credentcial to connect to the internal bazel cache, that credentcial might expired.

**Comment by cyyever** [comment]
@JackCaoG @tengyifei Thank you. We can recheck this PR once the connection problem is fixed.

**Pull request merged**
