### PR TITLE
Keep the memory used for sending tensors to device under control, to …

### PR DESCRIPTION
**Pull request by dlibenzi**
…avoid tripping over the ProtocolBuffer 2GB time bomb.

### CODE REVIEW

**Comment by dlibenzi** [comment]
> Thanks Davide! did you test with the repro in the referenced issue?

Not with that test, but I run a test by reducing the max memory size, and checking the batched sizes.

**Comment by taylanbil** [comment]
ah ok, I'll test it now then.

**Comment by dlibenzi** [comment]
Reducing the max device prefetch argument of the parallel loader should work as well.

**Comment by taylanbil** [comment]
added a print as follows:

```diff
diff --git a/torch_xla/distributed/parallel_loader.py b/torch_xla/distributed/parallel_loader.py
index 0bd9ce5e..5df530be 100644
--- a/torch_xla/distributed/parallel_loader.py
+++ b/torch_xla/distributed/parallel_loader.py
@@ -11,6 +11,7 @@ import torch_xla.core.xla_model as xm


 def _get_input_size(data):
+  print('GOT INPUT SIZE', flush=True)
   obj = xu.Object({'size': 0})

   def fn(v):
```

and ran the repro script
```
> ./actualrunme.sh
num_params: 1215978320
GOT INPUT SIZE
GOT INPUT SIZE
E0214 01:33:19.597505411   19893 proto_buffer_writer.h:83]   assertion failed: byte_count_ < total_size_
./actualrunme.sh: line 12: 19893 Aborted                 python actualrepro.py --num-embed 50000 --embed-dim 1536 --num-layers 30
```

Then I tried w/ `device_prefetch_size=1` but that also errored in exactly the same way.

**Comment by dlibenzi** [comment]
This does not work if you have a single tensor that blows the limits, of course.

**Comment by shz0116** [comment]
> This does not work if you have a single tensor that blows the limits, of course.

So XLA can not handle this single tensor problem ( 2GB limitation due to protobuf) ?

**Pull request merged**
