### PR TITLE
Respect default dtype

### PR DESCRIPTION
**Pull request by peterbell10**
Prior to pytorch/pytorch#82241, the python API never actually passed nullopt
and so the `OrFloat` path was never tested.

### CODE REVIEW

**Comment by peterbell10** [comment]
@JackCaoG ping

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by JackCaoG** [comment]
@peterbell10 Test seems to be passing, I guess I can directly merge this pr?

**Comment by peterbell10** [comment]
Yes this makes change sense on its own. I was only using the pin to test that it fixed the xla problems in the main pytorch PR.

**Pull request merged**
