### PR TITLE
Install Huggingface Transformers on our images

### PR DESCRIPTION
**Pull request by jysohn23**
This will be used to test our nightly tests

### CODE REVIEW

**Comment by dlibenzi** [comment]
Can't the test install it's own dependencies instead of adding all of them for every test?

**Comment by jysohn23** [comment]
> Can't the test install its own dependencies instead of adding all of them for every test?

Yeah we could for testing, but it's also so that users can directly run stuff from our images. We currently do this in all our PT/TF tutorials where we give users images with all dependencies and source pre-installed.

**Comment by dlibenzi** [comment]
> > Can't the test install its own dependencies instead of adding all of them for every test?
> 
> Yeah we could for testing, but it's also so that users can directly run stuff from our images. We currently do this in all our PT/TF tutorials where we give users images with all dependencies and source pre-installed.

I don't think it is right to stuff all possible user/test packages into the base Docker image.

**Comment by jysohn23** [comment]
Sure we can do it that way.

**Comment by dlibenzi** [comment]
In Docker terms, we could just use base image and add layer(s) on top.
But honestly I think that if the test script does one extra git-pull, is not too terrible.

**Comment by jysohn23** [comment]
> In Docker terms, we could just use base image and add layer(s) on top.
> But honestly I think that if the test script does one extra git-pull, is not too terrible.

Sounds good. We'll also have to have extra `git-pull` from tutorials, which might not be too bad.

**Pull request closed without merging**
