### PR TITLE
[cherry-pick] [Fori_loop|While_loop] Create fori_loop.md (#6942)

### PR DESCRIPTION
**Pull request by ManfeiBai**
Add doc for fori_loop/while_loop and add simple user guide for simple test case

### CODE REVIEW

**Review by yeounoh — APPROVED** [review]
LGTM

**Comment by yeounoh** [comment]
If not all the fori_loop PRs are in r2.3, then maybe we shouldn't back-port this... I will leave it up to you and Siyuan. @ManfeiBai @lsy323

**Comment by JackCaoG** [comment]
If user tried to run the code in the doc with 2.3 whl, would it work? if not we should not backport.

**Comment by ManfeiBai** [comment]
> If user tried to run the code in the doc with 2.3 whl, would it work? if not we should not backport.

we have `while_loop` and `fori_loop` in this PR at the same time, and we only include PR for while_loop in 2.3, so I could update this PR to only include `while_loop` version and push local change to this branch again

**Review by qihqi — APPROVED** [review]

**Comment by ManfeiBai** [comment]
> If user tried to run the code in the doc with 2.3 whl, would it work? if not we should not backport.

Thanks, tried with 2.3RC12 wheel(torch and torch_xla) and passed test case mentioned in md file, also passed tests in `test/test_fori_loop_with_while_loop_simple_add_dispatch_in_torch.py`

**Comment by ManfeiBai** [comment]
> If not all the fori_loop PRs are in r2.3, then maybe we shouldn't back-port this... I will leave it up to you and Siyuan. @ManfeiBai @lsy323

Thanks, @lsy323, I updated the doc to only mention feature included in 2.3, do we wanna backport this doc change?

**Comment by lsy323** [comment]
@ManfeiBai Backport docs sounds good to me.

**Review by lsy323 — APPROVED** [review]

**Pull request merged**
