### PR TITLE
fix type annotation for 3.8

### PR DESCRIPTION
**Pull request by JackCaoG**

### CODE REVIEW

**Comment by JackCaoG** [comment]
upstream update is green https://github.com/pytorch/pytorch/pull/130896, this one is ready for review.

**Review by qihqi — APPROVED** [review]

**Review by zpcore — APPROVED** [review]
Thanks for the fix!

Nit: We can use `from typing import OrderedDict` to be consistent with other typings.

**Comment by JackCaoG** [comment]
> Thanks for the fix!
> 
> Nit: We can use `from typing import OrderedDict` to be consistent with other typings.

There is a naming conflict I believe, because we also do
```
from collections import OrderedDict
```

**Review by will-cromar — APPROVED** [review]
Thanks!

**Pull request merged**
