### PR TITLE
Update amax/amin/norm signatures with int[*]? dim 

### PR DESCRIPTION
**Pull request by wonjoolee95**
Fixes https://github.com/pytorch/pytorch/pull/83300

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Build succeeding locally but failing in the CI. Need to rebase upstream PyTorch PR with master.

**Comment by wonjoolee95** [comment]
Locally, unit tests `Amax`, `Amin`, and `Norm` cpp tests are now passing.

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by JackCaoG** [comment]
@wonjoolee95 let's rebase and merge this one.

**Comment by wonjoolee95** [comment]
The CI was green previously except for the GPU DDP (which is already merged on master https://github.com/pytorch/xla/pull/4050).

**Comment by wonjoolee95** [comment]
Rebased, now will merge.

**Pull request merged**
