### PR TITLE
[OpenXLA] Delete `"@org_tensorflow//tensorflow/core/kernels:data_flow" deps

### PR DESCRIPTION
**Pull request by ManfeiBai**
Before migrating PyTorch/XLA to pull XLA from OpenXLA, will delete some unused deps from TensorFlow first;

`@org_tensorflow//tensorflow/core/kernels:data_flow` is not used and will delete directly, @stgpetrovic please correct if I'm wrong

### CODE REVIEW

**Comment by ManfeiBai** [comment]
test results: All checks have passed

**Comment by JackCaoG** [comment]
@ManfeiBai Do you still need to merge this pr?

**Comment by ManfeiBai** [comment]
> @ManfeiBai Do you still need to merge this pr?

not all ready, will close and reopen once ready

**Comment by ManfeiBai** [comment]
> @ManfeiBai Do you still need to merge this pr?

this dep is introduced by @stgpetrovic's [PR](https://github.com/pytorch/xla/pull/4636), will require Goran's review before merge this PR

**Comment by ManfeiBai** [comment]
> @ManfeiBai Do you still need to merge this pr?

yes, @stgpetrovic has reviewed and LGTMed;

it's ok to merge this PR or merge with the other two unused deps(example.pb.h and feature.pb.h) too

@JackCaoG

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
can you resolve the merge conflict?

**Review by miladm — APPROVED** [review]

**Pull request merged**
