### PR TITLE
remove model training using openxla backend

### PR DESCRIPTION
**Pull request by zpcore**
IIUC, there should not exist combination of `openxla` dynamo backend for evaluation.

### CODE REVIEW

**Comment by frgossen** [comment]
I think @JackCaoG had added this and my understanding is that the plan is to retire openxla_eval

**Comment by zpcore** [comment]
> I think @JackCaoG had added this and my understanding is that the plan is to retire openxla_eval

Thanks,

**Review by vanbasten23 — APPROVED** [review]
LGTM assuming openxla_eval is not deprecated per https://github.com/pytorch/xla/pull/6262#issuecomment-1881197725. Suggest to check with Jack about the plan.

**Comment by frgossen** [comment]
I don't understand why this was merged. Shouldn't `openxla` support both training and inference?

**Comment by zpcore** [comment]
> I don't understand why this was merged. Shouldn't `openxla` support both training and inference?

Hi @JackCaoG , can you help confirm if `openxla` backend support both training and inference? And do you have any plan on when to deprecate `openxla_eval`?

**Comment by JackCaoG** [comment]
openxla supports both training and inference. In the long run we want to get rid of `openxla_eval`, but currently `openxla_eval` is likely yield better performance on inference.

**Comment by JackCaoG** [comment]
in the mean time `openxla` to train and inference + `openxla_eval` for inference are valid use cases.

**Comment by zpcore** [comment]
I see, thanks. Let me revert the PR.

**Pull request merged**
