### PR TITLE
[reland] #3019: [test] add opinfo based eager reference test

### PR DESCRIPTION
**Pull request by kshitij12345**
Same as #3019

Had to add skips for `amax/amin`. (Recently changed in XLA)

### CODE REVIEW

**Comment by kshitij12345** [comment]
@JackCaoG this should be good to go

**Comment by JackCaoG** [comment]
Thanks @kshitij12345 , what's the instruction of running the `amax/amin` opInfoTest along?  I think we can uncomment the 
```
            # AllowedOpInfoEntry('amax'),
            # AllowedOpInfoEntry('amin'),
```
but I am wondering if there is an easier way to just run these two tests. @miladm Can you take a look at this after I merged it? I would expect the OpInfo test to pass for `amax` and `amin`.

**Comment by kshitij12345** [comment]
Locally, i would just uncomment and run
```bash
pytest test/test_ops.py -k _amax
```

from xla directory to just run `amax` test and similarly for `amin`

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Pull request merged**
