### PR TITLE
fix change introduced by PT#21852

### PR DESCRIPTION
**Pull request by ailzhang**
https://github.com/pytorch/pytorch/pull/21852

### CODE REVIEW

**Comment by dlibenzi** [comment]
Ouch ... keep biting us:
```
RuntimeError: Attempted to call `variable.set_data(tensor)`, but `variable` and `tensor` have different types of TensorImpl.
```

**Comment by dlibenzi** [comment]
Oh, OK ... one HUNK failed:
```
+ xla/scripts/apply_patches.sh
1 out of 1 hunk FAILED
Applying patch file: /tmp/pytorch/xla/torch_patches/21048.diff
```

Is Will's new PR in?

**Comment by dlibenzi** [comment]
This PR though is benign enough to go in regardless.

**Comment by ailzhang** [comment]
@dlibenzi Yea the first PR of @yf225 's fix (https://github.com/pytorch/pytorch/pull/21865) went in last night. And the last one (https://github.com/pytorch/pytorch/pull/21613) is approved, should be merged soon I think. We can safely remove the patch after that. (We've tested it locally yesterday, should be good).

**Pull request merged**
