### PR TITLE
[stale] Test backward pass nn model with dynamic input

### PR DESCRIPTION
**Pull request by vanbasten23**

### CODE REVIEW

**Comment by vanbasten23** [comment]
Succeeds when we use dynamic test data but static training data: f82efbcf7058d589377b751891d6938ca3b2d4e5. It outputs:
```
Finished training. Got loss: 0.686253547668457
Finished testing, loss= 0.6257358193397522
```

**Comment by vanbasten23** [comment]
Once I made the test data dynamic (0048f3b0da9c7b1f6760269f767ac87883db188d), the test failed with error:
```
root@t1v-n-2a2b95ef-w-0:/workspaces/work# python3 pytorch/xla/test/test_dynamic_shape_models.py
Traceback (most recent call last):
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 78, in <module>
    train(model, loss_fn=criterion, optimizer=optimizer)
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 65, in train
    loss.backward()
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/_tensor.py", line 484, in backward
    torch.autograd.backward(
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function SigmoidBackward0 returned an invalid gradient at index 0 - got [80, 1] but expected shape compatible with [<=80, 1]
```
which I'm going to look into.

**Comment by miladm** [comment]
Looks like sigmoid_bakwards needs to support dynamism. Wdyt?

**Comment by vanbasten23** [comment]
Yeah, Also, for the error `RuntimeError: Function SigmoidBackward0 returned an invalid gradient at index 0 - got [80, 1] but expected shape compatible with [<=80, 1]
`, it failed at https://github.com/pytorch/pytorch/blob/912a1f7b2776c0e7ebf9038e4483a4aa709aa893/torch/csrc/autograd/engine.cpp#L812.

**Comment by miladm** [comment]
We have the stack trace pointing to the `pytorch/torch/csrc/autograd/engine.cpp` error. See the previous comment. @wconstab @ezyang we are wondering if the autograd engine is missing dynamism support. Wdyt?

**Comment by ezyang** [comment]
This error is not one I've seen before. At a guess, CLA's bounded symints don't correctly implement the equality/comparison operators and a test AD engine is doing is failing. If you log symint ops should become clear

**Comment by vanbasten23** [comment]
i messed up this branch so I created a new [one](https://github.com/pytorch/xla/pull/4322).

**Pull request closed without merging**
