### PR TITLE
backport `Enable eager mode for PyTorch/XLA`

### PR DESCRIPTION
**Pull request by JackCaoG**

### CODE REVIEW

**Comment by bhavya01** [comment]
@JackCaoG Can you update your branch with latest changes in r2.4 to be able to run the CI tests on this PR?

**Comment by JackCaoG** [comment]
Thanks! Let me rebase

**Comment by JackCaoG** [comment]
I saw the same failres on 2.4 head CI, I think this one is ready for review. @bhavya01

**Review by bhavya01 — APPROVED** [review]
Thanks! I'm looking into the CI test failures with CUDA backend.

**Pull request merged**
