### PR TITLE
Move CXXABI setting into C++ tests cmake machinery so that simple bui…

### PR DESCRIPTION
**Pull request by davidel**
…lds get that as well.

### CODE REVIEW

**Comment by jysohn23** [comment]
Thanks @davidel. I actually had tried changing CMake this but it didn't work for me (I tried something like this: https://github.com/pytorch/pytorch/blob/ff91b169c78a2e980443f75ea308681bc2c7eb7e/CMakeLists.txt#L38). I tested this PR out and it looks like it's failing to build with `=0`:

```
[ 95%] Building CXX object CMakeFiles/test_ptxla.dir/torch_xla_test.cpp.o
[100%] Linking CXX executable test_ptxla
CMakeFiles/test_ptxla.dir/cpp_test_util.cpp.o: In function `torch_xla::cpp_test::TestBackward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::Device const&, std::function<at::Tensor (std::vector<at::Tensor, std::allocator<at::Tensor> > const&)> const&, double, double)':
cpp_test_util.cpp:(.text+0x5501): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
...
```

Inspecting `CMakeCache.txt` in `build/` dir:
```
(pytorch) root@25db98d579ad:/# grep ABI pytorch/xla/test/cpp/build/CMakeCache.txt
< no hits >
```

Whereas running with env var:
```
(pytorch) root@25db98d579ad:/# grep ABI pytorch/xla/test/cpp/build/CMakeCache.txt
CMAKE_CXX_FLAGS:STRING=-D_GLIBCXX_USE_CXX11_ABI=0
```

**Comment by davidel** [comment]
Not sure what =0 or =1 differ, but let me try with =0.

**Comment by davidel** [comment]
I am confused by the CI tests ... didn't we set CXXABI=0 in CI builds?
The tests for these PR passed ... but CXXABI==1 ...

**Comment by jysohn23** [comment]
> I am confused by the CI tests ... didn't we set CXXABI=0 in CI builds?
> The tests for these PR passed ... but CXXABI==1 ...

Oh no, sorry for the confusion. We decided to be consistent with upstream torch and CI with `=1` and release with `=0`, which is what they do at the moment.

**Comment by davidel** [comment]
Got it ... trying with =0 now...

**Comment by davidel** [comment]
Not finished yet ... too slow VM 😄 
But I think we have to pass the flag to the external project (googletest) build:

https://github.com/pytorch/xla/blob/18fa011c3eba79b93ea38cf5b0946920e45b2053/test/cpp/CMakeLists.txt#L22

https://cmake.org/cmake/help/latest/module/ExternalProject.html#command:externalproject_add

**Comment by davidel** [comment]
Yep, was broken. Recent code fixes it (as described above).

**Pull request merged**
