### PR TITLE
enable nn/mha tests

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/pull/89748

### CODE REVIEW

**Comment by JackCaoG** [comment]
`python3: can't open file '/tmp/pytorch/xla/test/../../test/nn/test_multihead_attention.py': [Errno 2] No such file or directory` do you need to ping a upstream branch?

**Comment by kshitij12345** [comment]
Ah. Sorry, the code wasn't available on master when the PR was made. Rebasing should do the trick. Thanks!

**Comment by kshitij12345** [comment]
CI is green now :)

Thanks @JackCaoG

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Pull request merged**
