### PR TITLE
Support new api for index_add

### PR DESCRIPTION
**Pull request by krshrimali**
This PR attempts to:

* Add support for the new API of `index_add` (ref: https://github.com/pytorch/pytorch/pull/65993).
* Enable OpInfo for `index_add`.

Note: Since this is my first time looking at the source code of XLA, I might have missed something - so please feel free to point any mistakes you see (or any suggestions).

I'll be keeping an eye on the CI to notice any failures, and fix them from there.

cc: @JackCaoG

### CODE REVIEW

**Comment by JackCaoG** [comment]
Building pt/xla will also build tensorflow which takes around 40~60 minutes in my 64v CPU, unforunitly there is not a way to get around it. The good news is that you only need to build tf once(unless we update the pin tf version which is not very common). 

My suggestion for you would be
pytorch/xla actually currently only natively support `index_add_`, (`index_add` or `out` might be supported indirectly). What you need to do is update [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L1600) to take `alpha` argument. You should check if `alpha != 1`, operation should fallback to CPU.  example in [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L1937).

You do need to update existing cpp tests that uses `torch::index_add` to take `alpha=1`. You can also leave the opinfo test along for now.

You need to add a `torch_pin` like [this one](https://github.com/pytorch/xla/pull/3039/files), pin would be your pytorch pr number. This way CI would find the correcy upstream to build.


This way you don't introduce any new feature but only fix the incompatibility. I can add the support for `alpha` later on since it is not as trivial as I thought.

**Comment by krshrimali** [comment]
> Building pt/xla will also build tensorflow which takes around 40~60 minutes in my 64v CPU, unforunitly there is not a way to get around it. The good news is that you only need to build tf once(unless we update the pin tf version which is not very common).
> 
> My suggestion for you would be pytorch/xla actually currently only natively support `index_add_`, (`index_add` or `out` might be supported indirectly). What you need to do is update [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L1600) to take `alpha` argument. You should check if `alpha != 1`, operation should fallback to CPU. example in [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L1937).
> 
> You do need to update existing cpp tests that uses `torch::index_add` to take `alpha=1`. You can also leave the opinfo test along for now.
> 
> You need to add a `torch_pin` like [this one](https://github.com/pytorch/xla/pull/3039/files), pin would be your pytorch pr number. This way CI would find the correcy upstream to build.
> 
> This way you don't introduce any new feature but only fix the incompatibility. I can add the support for `alpha` later on since it is not as trivial as I thought.

Thanks, @JackCaoG for your help on this! I was just taking a look at implementation of `addmm`, and just noticed it also has a fallback to CPU [(here)](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L605). It's interesting, I think I enjoyed reading through the codebase so far :) Just curious, do we plan to add support for such ops which fallback to CPU (like `addmm` and now `index_add`)?

I'll build locally, and push the changes once done. Thanks again! This really helps.

**Comment by krshrimali** [comment]
> @krshrimali You might need to do a `git pull` on master first, you want to make sure [457270c](https://github.com/pytorch/xla/commit/457270c2466b47ee15248f7dbac54915d26beca2) is presented in your branch. You can check that by doing a `git log`.

Yep, I verified that. Here is the entry it shows when I do `git log` for my branch:

```
# My commits
# ...
commit 457270c2466b47ee15248f7dbac54915d26beca2 (origin/master, origin/HEAD, master)
Author: JackCaoG <59073027+JackCaoG@users.noreply.github.com>
Date:   Mon Oct 4 10:44:54 2021 -0700

    Revert "Revert "Update _(log_)softmax_backward parameters (#3137)" (#3146)" (#3150)
    
    This reverts commit 419417dc8d2247edac4ad70241374192e32174c3
```

Also verified that the file has changes that were done in the commit you mentioned: https://github.com/krshrimali/xla/blob/from_torch/index_add/torch_xla/csrc/aten_xla_type.cpp#L471 and https://github.com/krshrimali/xla/blob/from_torch/index_add/torch_xla/csrc/aten_xla_type.cpp#L503.

Apologies for this, but I've checked twice and nothing seems off on my branch w.r.t master of the upstream.

**Comment by JackCaoG** [comment]
Ah, you also need your pytorch pr to contain https://github.com/pytorch/pytorch/pull/66018 to make the build pass. You would also rebase your pytorch pr.

It is pretty annoying when this happen. We need pytorch and pytorch/xla to sync in order to build.

**Comment by JackCaoG** [comment]
@krshrimali done, let's see if test will pass. For linter failure, can you refer to https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#before-submiting-a-pull-request

**Comment by JackCaoG** [comment]
You can use `./test/cpp/build/test_ptxla --gtest_filter=AtenXlaTensorTest.TestXXX` under pt/xla dir to repo the cpp test failure, In your case TestXXX should be `TestIndexAdd` and `TestIndexAddRank0`. I am guessing you also need to update the `torch::index_add` call there. Test is under `test/cpp/test_aten_xla_tensor.cpp` btw.

**Comment by krshrimali** [comment]
> You can use `./test/cpp/build/test_ptxla --gtest_filter=AtenXlaTensorTest.TestXXX` under pt/xla dir to repo the cpp test failure, In your case TestXXX should be `TestIndexAdd` and `TestIndexAddRank0`. I am guessing you also need to update the `torch::index_add` call there. Test is under `test/cpp/test_aten_xla_tensor.cpp` btw.

Hi @JackCaoG - Am sorry for the delayed response, I was travelling last week and was on PTO. Just wanted to acknowledge that the upstream PR is currently going under review, and will have some updates - once done, I'll take a look at this PR.

On another note, it will be great if you could take over this PR when the upstream PR is ready since I'm not really sure about the XLA backend code, and the failures. Would you mind helping me with this? I'll of course ping you once the upstream PR is ready.

**Comment by krshrimali** [comment]
Hi, @JackCaoG - Hope you're doing well. I just wanted to gently ping - the upstream PR has been approved, and it will help if you could take a look at the XLA side changes, and help us take the PR forward (https://github.com/pytorch/pytorch/pull/65993#pullrequestreview-791990237).

Please let me know if there are any questions or any clarification required. :) Thank you for your help.

**Comment by JackCaoG** [comment]
@krshrimali Sounds good, I will start working on this one.

**Comment by JackCaoG** [comment]
Since I do not own the branch(and I can't commit to it), I will open a separate pr and patch your change.

**Pull request closed without merging**
