### PR TITLE
Clean up the redundant arg_min/max releated file

### LINKED ISSUE #5583: Codegen `argmin` and `argmax` op
Update op `argmin` and `argmax` from manual lowering to codegen.

### PR DESCRIPTION
**Pull request by zpcore**
resolves #5583.

### CODE REVIEW

**Comment by lsy323** [comment]
Thanks for preparing the follow up PR for https://github.com/pytorch/xla/pull/5586. LGTM pending on CI completion.

**Review by lsy323 — APPROVED** [review]

**Review by JackCaoG — APPROVED** [review]

**Comment by zpcore** [comment]
This is the follow up with the discussion in https://github.com/pytorch/xla/pull/5586. 

We have switched to the codegen lowering method for arg_max and arg_min. So we can clean up the arg_min and arg_max related files and dependencies used in manual lowering.

**Comment by zpcore** [comment]
Hi @JackCaoG , looks like the GPU test is running forever. Is this due to the https://github.com/pytorch/xla/pull/5570 as you mentioned?

**Comment by JackCaoG** [comment]
no.. it is just slow..

**Pull request merged**
