### PR TITLE
[Pin Update] Version 20230826

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This change bumps libTPU.so to 20230826 and update the corresponding openxla/xla pin.

Test Plan:
CI.

### CODE REVIEW

**Comment by alanwaketan** [comment]
For ResNet MP on V4-8:
After the change:
```
| Training Device=xla:0/1 Epoch=1 Step=2340 Loss=0.00135 Rate=1776.80 GlobalRate=993.25 Time=02:13:37
```

For ResNet SPMD on V4-8:
After the change:
```
| Training Device=xla:0/0 Epoch=1 Step=4680 Loss=0.00135 Rate=1882.09 GlobalRate=1552.79 Time=02:22:06
```

**Review by qihqi — APPROVED** [review]

**Review by lsy323 — APPROVED** [review]
LGTM

**Comment by alanwaketan** [comment]
Looks like one of the GPU test has failed. There could be a regression on GPU. Will need to setup a GPU env to further debug.

**Comment by JackCaoG** [comment]
`//test/cpp:test_tensor` timed out, wondering if it is a real error or some flakeyness. I bump up the test timeout for GPU to 240 minutes in https://github.com/pytorch/xla/commit/76495f0bc833f0a98a08cb56c329b0b492ba1286 so I think it is not the workflow itself timedout but that specified test has some timeout threashold.

**Comment by alanwaketan** [comment]
> `//test/cpp:test_tensor` timed out, wondering if it is a real error or some flakeyness. I bump up the test timeout for GPU to 240 minutes in [76495f0](https://github.com/pytorch/xla/commit/76495f0bc833f0a98a08cb56c329b0b492ba1286) so I think it is not the workflow itself timedout but that specified test has some timeout threashold.

Yea, I need to setup a GPU env to repro.

**Comment by wonjoolee95** [comment]
@ManfeiBai, wondering if you have any GPU that we can use to repro this?

**Comment by wonjoolee95** [comment]
Thanks @ManfeiBai, let me know if you need any help.

**Comment by ManfeiBai** [comment]
this might be the GPU CI issue log: https://source.cloud.google.com/results/invocations/a2d48ef1-784f-43d8-b4e5-69caa341e906/targets/%2F%2Ftest%2Fcpp:test_tensor/log

**Comment by alanwaketan** [comment]
> 76495f0



> this might be the GPU CI issue log: https://source.cloud.google.com/results/invocations/a2d48ef1-784f-43d8-b4e5-69caa341e906/targets/%2F%2Ftest%2Fcpp:test_tensor/log

So you are suggesting the time out could be unrelated? and we should increase the test time out limit?

**Comment by ManfeiBai** [comment]
> 76495f0

yes, agree with the `increase the test time out limit` plan, and let's also trigger GPU test again to confirm issue consistantly too?

**Comment by alanwaketan** [comment]
> > [76495f0](https://github.com/pytorch/xla/commit/76495f0bc833f0a98a08cb56c329b0b492ba1286)
> 
> yes, agree with the `increase the test time out limit` plan, and let's also trigger GPU test again to confirm issue consistantly too?

The issue is consistent. I have ran it twice.

**Comment by ManfeiBai** [comment]
> > > [76495f0](https://github.com/pytorch/xla/commit/76495f0bc833f0a98a08cb56c329b0b492ba1286)
> > 
> > 
> > yes, agree with the `increase the test time out limit` plan, and let's also trigger GPU test again to confirm issue consistantly too?
> 
> The issue is consistent. I have ran it twice.

then I would agree with the `increase the test time out limit` plan, it may help us for more info

**Comment by wonjoolee95** [comment]
Until we can debug the GPU CI for certain, we should probably not cherry-pick this into the r2.1 branch. That means we'll need to re-open your PR to fix the FSDP GPU unit tests, @ManfeiBai. Let me know if you think otherwise, @alanwaketan.

**Comment by alanwaketan** [comment]
> Until we can debug the GPU CI for certain, we should probably not cherry-pick this into the r2.1 branch. That means we'll need to re-open your PR to fix the FSDP GPU unit tests, @ManfeiBai. Let me know if you think otherwise, @alanwaketan.

Let me set the time out now. If it doesn't work, then let's re-open Manfei's PR.

**Comment by alanwaketan** [comment]
It seems we need a longer time limit. @wonjoolee95 @JackCaoG @ManfeiBai Please take a look to see if the current way is preferable?

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Review by JackCaoG — APPROVED** [review]

**Review by wonjoolee95 — APPROVED** [review]

**Comment by alanwaketan** [comment]
Thanks all for reviewing!

**Pull request merged**
