### PR TITLE
[Test] Pull xla from openxla

### PR DESCRIPTION
**Pull request by ManfeiBai**

### CODE REVIEW

**Comment by ManfeiBai** [comment]
commit 58072c7 failed at something like this:
```
[1/173] clang++-8 -MMD -MF /tmp/pytorch/xla/build/temp.linux-x86_64-cpython-38/torch_xla/csrc/batch_norm.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -I/tmp/pytorch/xla -I/tmp/pytorch/xla/bazel-bin -I/tmp/pytorch/xla/bazel-xla -I/tmp/pytorch/xla/bazel-bin/external/org_tensorflow/ -I/tmp/pytorch/xla/bazel-xla/external/org_tensorflow/ -I/tmp/pytorch/xla/bazel-xla/external/com_github_grpc_grpc/include -I/tmp/pytorch/xla/bazel-xla/external/com_google_protobuf/src -I/tmp/pytorch/xla/bazel-xla/external/eigen_archive -I/tmp/pytorch/xla/bazel-xla/external/com_google_absl -I/tmp/pytorch/xla/bazel-xla/external/com_googlesource_code_re2 -I/tmp/pytorch/xla/bazel-xla/com_github_grpc_grpc/include -I/tmp/pytorch -I/tmp/pytorch/torch/csrc -I/tmp/pytorch/torch/lib/tmp_install/include -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/opt/conda/include/python3.8 -c -c /tmp/pytorch/xla/torch_xla/csrc/batch_norm.cpp -o /tmp/pytorch/xla/build/temp.linux-x86_64-cpython-38/torch_xla/csrc/batch_norm.o -std=c++17 -Wno-sign-compare -Wno-deprecated-declarations -Wno-return-type -Wno-macro-redefined -Wno-return-std-move -DNDEBUG -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_XLAC -D_GLIBCXX_USE_CXX11_ABI=1
FAILED: /tmp/pytorch/xla/build/temp.linux-x86_64-cpython-38/torch_xla/csrc/batch_norm.o 
clang++-8 -MMD -MF /tmp/pytorch/xla/build/temp.linux-x86_64-cpython-38/torch_xla/csrc/batch_norm.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -I/tmp/pytorch/xla -I/tmp/pytorch/xla/bazel-bin -I/tmp/pytorch/xla/bazel-xla -I/tmp/pytorch/xla/bazel-bin/external/org_tensorflow/ -I/tmp/pytorch/xla/bazel-xla/external/org_tensorflow/ -I/tmp/pytorch/xla/bazel-xla/external/com_github_grpc_grpc/include -I/tmp/pytorch/xla/bazel-xla/external/com_google_protobuf/src -I/tmp/pytorch/xla/bazel-xla/external/eigen_archive -I/tmp/pytorch/xla/bazel-xla/external/com_google_absl -I/tmp/pytorch/xla/bazel-xla/external/com_googlesource_code_re2 -I/tmp/pytorch/xla/bazel-xla/com_github_grpc_grpc/include -I/tmp/pytorch -I/tmp/pytorch/torch/csrc -I/tmp/pytorch/torch/lib/tmp_install/include -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/opt/conda/include/python3.8 -c -c /tmp/pytorch/xla/torch_xla/csrc/batch_norm.cpp -o /tmp/pytorch/xla/build/temp.linux-x86_64-cpython-38/torch_xla/csrc/batch_norm.o -std=c++17 -Wno-sign-compare -Wno-deprecated-declarations -Wno-return-type -Wno-macro-redefined -Wno-return-std-move -DNDEBUG -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_XLAC -D_GLIBCXX_USE_CXX11_ABI=1
In file included from /tmp/pytorch/xla/torch_xla/csrc/batch_norm.cpp:1:
/tmp/pytorch/xla/torch_xla/csrc/batch_norm.h:3:10: fatal error: 'xla/client/xla_builder.h' file not found
#include "xla/client/xla_builder.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

any good idea about this? @stgpetrovic

**Comment by stgpetrovic** [comment]
We explicitly set which directories we look headers in setup.py so you need to update that too along with cmake for tests.

**Comment by ManfeiBai** [comment]
> We explicitly set which directories we look headers in setup.py so you need to update that too along with cmake for tests.

thanks, Goran, udpated in #bbc312d

**Comment by miladm** [comment]
@stgpetrovic can you please point to a use case scenario for @ManfeiBai to learn how to unblock this issue. looks like we are missing a couple of steps here; unclear what those steps are :)

Thanks!

**Comment by stgpetrovic** [comment]
Taking a look.

The libxla_computation_client.so gets built but very quickly and only has 8.0kb, this is not doing the build properly I think.

This is also the reason the subsequent cpp build fails: the previous build has not created any intermediate output for it to use.
For the `cc_shared_library`, use `roots` for deps, instead `static_deps` (and remove .lsd files from them), that should get you going. The second error will disappear as soon as the lib builds correctly.

Hope that helps

**Comment by ManfeiBai** [comment]
> 4fc356a

Thanks, Goran, tried in [4fc356a](https://github.com/pytorch/xla/pull/4807/commits/4fc356a5c0a4dae4b2b88f547f0c254c7032e86f)

**Comment by ManfeiBai** [comment]
> Taking a look.
> 
> The libxla_computation_client.so gets built but very quickly and only has 8.0kb, this is not doing the build properly I think.
> 
> This is also the reason the subsequent cpp build fails: the previous build has not created any intermediate output for it to use. For the `cc_shared_library`, use `roots` for deps, instead `static_deps` (and remove .lsd files from them), that should get you going. The second error will disappear as soon as the lib builds correctly.
> 
> Hope that helps

Thanks, Goran, tried in [4fc356a](https://github.com/pytorch/xla/pull/4807/commits/4fc356a5c0a4dae4b2b88f547f0c254c7032e86f)

**Pull request closed without merging**
