### PR TITLE
Enable eager mode for PyTorch/XLA

### PR DESCRIPTION
**Pull request by JackCaoG**
Add a eager mode for PyTorch/XLA. We already have an eager mode for debug which is `UseEagerDebugMode` that's controlled by a env var. This was contributed by the AWS folks(cc @amithrm @jeffhataws). I decided to make a offical top level api for it.

In this pr, I 
1. add api `use_eager_mode` along with all the pybinds
2. make sure that `PT_XLA_DEBUG` and `PT_XLA_DEBUG_LEVEL` does not print analysis for eager execution
3. add new metrics for eager mode compilation and eager mode executions

For future pr
1. increase the maximum number of queued task (for eager mode)
3. add api/decorator to compile a specified function in the eager mode.
4. add docs
5. test eager + SPMD

For a 2 layer decoder only model, eager mode can acheive ~40% of throuput compared to the full compiled mode.

### CODE REVIEW

**Comment by lsy323** [comment]
Let's add a test, otherwise LGTM

**Review by lsy323 — APPROVED** [review]

**Comment by JackCaoG** [comment]
The correctness check is handled by `run_eager_debug  "$CDIR/test_operations.py" "$@" --verbosity=$VERBOSITY`. I will expand this in the future.

**Review by qihqi — APPROVED** [review]

**Comment by JackCaoG** [comment]
Ah.. I need to move this api under experimental.. Let me update the pr...

**Comment by JackCaoG** [comment]
I am going to skip the gpu tests and it takes forever to get resouce. From last few runs of the CI in this pr, there is nothing specified about the GPU.

**Pull request merged**
