### PR TITLE
Companion PR for pytorch/pytorch#84579 

### PR DESCRIPTION
**Pull request by ezyang**
pytorch/pytorch#84579

### CODE REVIEW

**Comment by JackCaoG** [comment]
If I understand correctly, now we have to opt-in symint support in a op based. If we put a op under `symint`, we can define the `op_symint` variant that have takes size as `symint`?

**Comment by ezyang** [comment]
> If I understand correctly, now we have to opt-in symint support in a op based. If we put a op under symint, we can define the op_symint variant that have takes size as symint?

That's right. And if you don't opt in, no change on XLA side is needed.

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by ezyang** [comment]
subsumed by https://github.com/pytorch/xla/pull/3978

**Pull request closed without merging**
