### PR TITLE
Add ViT model to the supported models in the tests.

### PR DESCRIPTION
**Pull request by vanbasten23**
The model can be run as, for example, `python3 /pytorch/xla/test/test_train_mp_imagenet_fsdp.py   --fake_data --drop_last   --model vit_b_16 --test_set_batch_size 64 --eval_interval 10   --lr 0.4 --batch_size 128 --num_warmup_epochs 5 --lr_scheduler_divide_every_n_epochs 30     --lr_scheduler_divisor 10 --num_epochs 100   --use_nested_fsdp --use_gradient_checkpointing`

### CODE REVIEW

**Comment by JackCaoG** [comment]
does this only work with fsdp or data prallel can also work?

**Comment by vanbasten23** [comment]
> does this only work with fsdp or data prallel can also work?

Which one is the data parallel? I tested on /pytorch/xla/test/test_train_mp_imagenet_fsdp.py and test/test_train_mp_imagenet.py, and they both work.

**Comment by ronghanghu** [comment]
> > does this only work with fsdp or data prallel can also work?
> 
> Which one is the data parallel? I tested on /pytorch/xla/test/test_train_mp_imagenet_fsdp.py and test/test_train_mp_imagenet.py, and they both work.

`test/test_train_mp_imagenet.py` is the (vanilla) data parallel one (under XRT). The ViT model should work with both vanilla data parallel and FSDP.

**Comment by vanbasten23** [comment]
> 

Thanks for the clarification. Just want to make sure it is accurate: when I ran the `data parallel one`, it ran for a few minutes/steps and then failed with out of memory error; when I ran the fsdp one, it ran much longer, though I didn't wait until the fsdp test finished. Please let me know if it is ok.

**Comment by vanbasten23** [comment]
> > > does this only work with fsdp or data prallel can also work?
> > 
> > 
> > Which one is the data parallel? I tested on /pytorch/xla/test/test_train_mp_imagenet_fsdp.py and test/test_train_mp_imagenet.py, and they both work.
> 
> `test/test_train_mp_imagenet.py` is the (vanilla) data parallel one (under XRT). The ViT model should work with both vanilla data parallel and FSDP.

Thanks for the clarification. Just want to make sure it is accurate: when I ran the `data parallel one`, it ran for a few minutes/steps and then failed with out of memory error; when I ran the fsdp one, it ran much longer, though I didn't wait until the fsdp test finished. Please let me know if it is ok.

**Review by yeounoh — APPROVED** [review]
LGTM, thanks @vanbasten23

**Comment by yeounoh** [comment]
> 

Yea, fsdp should help reduce the memory footprint. Do you want to add vit-b16 to just fsdp?

**Review by yeounoh — CHANGES_REQUESTED** [review]
Let's add vit_b_16 to fsdp only, since it ran into OOM error in other scripts.

**Comment by ronghanghu** [comment]
> > > > does this only work with fsdp or data prallel can also work?
> > > 
> > > 
> > > Which one is the data parallel? I tested on /pytorch/xla/test/test_train_mp_imagenet_fsdp.py and test/test_train_mp_imagenet.py, and they both work.
> > 
> > 
> > `test/test_train_mp_imagenet.py` is the (vanilla) data parallel one (under XRT). The ViT model should work with both vanilla data parallel and FSDP.
> 
> Thanks for the clarification. Just want to make sure it is accurate: when I ran the `data parallel one`, it ran for a few minutes/steps and then failed with out of memory error; when I ran the fsdp one, it ran much longer, though I didn't wait until the fsdp test finished. Please let me know if it is ok.

Yeah, FSDP should save more memory. With a small-enough per-TPU batch size, both FSDP and (vanilla) data parallel should work, so if it is needed/helpful to run ViT-B under (vanilla) data parallel, one can consider reducing the batch size to avoid the OOM.

**Comment by vanbasten23** [comment]
> Collaborator

Done. Though I want to point out that running ViT with FSDP has been taking 5 hours and is still running. I don't think it will complete:
```
| Training Device=xla:0/2 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
| Training Device=xla:0/6 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
| Training Device=xla:0/1 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
| Training Device=xla:0/3 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
| Training Device=xla:0/5 Epoch=18 Step=80 Loss=0.00000 Rate=139.84 GlobalRate=140.10 Time=00:10:50
```

**Review by yeounoh — APPROVED** [review]
LGTM thanks!

**Comment by yeounoh** [comment]
> > Collaborator
> 
> Done. Though I want to point out that running ViT with FSDP has been taking 5 hours and is still running. I don't think it will complete:
> 
> ```
> | Training Device=xla:0/2 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
> | Training Device=xla:0/6 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
> | Training Device=xla:0/1 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
> | Training Device=xla:0/3 Epoch=18 Step=80 Loss=0.00000 Rate=139.85 GlobalRate=140.10 Time=00:10:50
> | Training Device=xla:0/5 Epoch=18 Step=80 Loss=0.00000 Rate=139.84 GlobalRate=140.10 Time=00:10:50
> ```

I think it's OK, i remember running just one epoch for more than an hour on a single machine before. For the testing purposes, we are already past the default number of epochs. If the CI turns green, we can submit.

**Pull request merged**
