### PR TITLE
Update `libtpu` version to Dec17

### PR DESCRIPTION
**Pull request by ManfeiBai**
Upgrade libtpu version to Dec 17th to align with that of our recent Tensorflow Pin(updated to Dec 15th) https://github.com/pytorch/xla/pull/4324

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Thanks! Let's combine this pr with tf update pr next time. This way if we have to revert for whatever reason, we only need to revert one pr.

**Comment by JackCaoG** [comment]
hmm, not sure why CI is failing, maybe rebase?

**Comment by ManfeiBai** [comment]
> hmm, not sure why CI is failing, maybe rebase?

let me check

**Comment by ManfeiBai** [comment]
> > hmm, not sure why CI is failing, maybe rebase?
> 
> let me check

tested locally, could build with the PR commit for TF pin update(https://github.com/pytorch/xla/pull/4324):
XLA Commit ID: 9cf2565f08a4a85af7468475fc97eb4d18ad4df3
PyTorch Commit ID: 6e0cd8b91ed8cb45444224bc24552956016338ec

will check after rebase

**Comment by ManfeiBai** [comment]
> > hmm, not sure why CI is failing, maybe rebase?
> 
> let me check

Thanks, rebased

**Comment by ManfeiBai** [comment]
> Thanks! Let's combine this pr with tf update pr next time. This way if we have to revert for whatever reason, we only need to revert one pr.

yea, sure, Thanks, Jack

**Pull request merged**
