### PR TITLE
Fix multi-gpu metrics report

### PR DESCRIPTION
**Pull request by ymwangg**
This PR fixed https://github.com/pytorch/xla/issues/2508. I'm not sure why GPU device does not allow reusing the same ClusterSpec but leaving it blank seems to work.

Tested with `GPU_NUM_DEVICES=8 python test_train_mp_mnist.py --metrics_debug --fake_data --num_epochs 1`.

Single-gpu metrics report: https://gist.github.com/ymwangg/609b79ed783a1797f87d55480d23bc8d
Multi-gpu metrics report: https://gist.github.com/ymwangg/8218ddf4ed8ce2d1ac35758effabdf6f

cc @YangFei1990

### CODE REVIEW

**Comment by YangFei1990** [comment]
Great, thanks a lot @ymwangg! A few questions for my understanding:
If we do not use the cached session config will it generate some default config? How are we sure that such change won't affect the metrics generation?

**Comment by ymwangg** [comment]
@YangFei1990 My understanding is that the same graph will produce the same results regardless of different session configs. It could be wrong and Google folks may have a better answer.

**Comment by JackCaoG** [comment]
Thanks! I think rebase should fix the build issue.

**Review by JackCaoG — APPROVED** [review]
Thanks @ymwangg !

**Pull request merged**
