### PR TITLE
[WIP]Disable all failed PyTorch test

### PR DESCRIPTION
**Pull request by ManfeiBai**
Moving python op test from TPU2VM to TPUVM, and tracking ticket: https://buganizer.corp.google.com/issues/260639498

---
Test Environment:
```
contaienr: gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm

command to create the TPUVM:
  gcloud config set project tpu-pytorch
  export TPU_NAME=manfei_1vm
  export ZONE=us-central1-a
  gcloud compute tpus tpu-vm ssh ${TPU_NAME} --zone ${ZONE} -- -o ProxyCommand='corp-ssh-helper %h %p'
```

---
Script to run all tests under PyTorch/test repo and within PyTorch/XLA/test/run_tests.sh :
```
#!/bin/bash
set -ex

export TF_CPP_LOG_THREAD_ID=1
export WITH_XLA=1 NO_CUDA=1 XLA_DEBUG_GC=2 CC=clang-8 CXX=clang++-8 CLANG_FORMAT="clang-format-7"
export COMPILE_PARALLEL=1 DEBUG=1 XLA_IR_DEBUG=1 XLA_HLO_DEBUG=1 TF_CPP_LOG_THREAD_ID=1
export XRT_WORKERS="localservice:0;grpc://localhost:51011"
export XLA_USE_XRT=1 XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0" 

export XLA_CUDA=1
export GITHUB_TORCH_XLA_BOT_TOKEN=84eaa41dc4141a6b3fe81c3097347b2e148342c6

export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH:-${CONDA_PREFIX:-"$(dirname $(which conda))/../"}}

export PYTORCH_DIR=/pytorch
export XLA_DIR=$PYTORCH_DIR/xla

# Needs to be kept in sync with .jenkins/pytorch/common_utils.sh in pytorch/pytorch.
export TORCHVISION_COMMIT="$(cat $PYTORCH_DIR/.github/ci_commit_pins/vision.txt)"

# run_torch_xla_tests
XLA_PORT=$(shuf -i 40701-40999 -n 1)
export XRT_WORKERS="localservice:0;grpc://localhost:$XLA_PORT"

export PYTORCH_TESTING_DEVICE_ONLY_FOR="xla"

pushd $XLA_DIR
  echo "Running Python Tests"
  ./test/run_tests.sh
popd

echo "Finish running all python op tests"
```

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Hmm this is odd. Are we sure that all these tests are failing? For example, looking at `test_setitem_scalars` -- I can see that the latest xl-ml run succeeded this op test:

Screen Shot 2022-12-07 at 5 16 31 PM

What is the error `Received signal 6 & 11`? Could you paste the full error logs? I'm assuming it may be an error related to your TPUVM.

**Comment by JackCaoG** [comment]
I noticed that some tests only failed on TPUVM, that might be why?

**Comment by ManfeiBai** [comment]
> Hmm this is odd. Are we sure that all these tests are failing? For example, looking at `test_setitem_scalars` -- I can see that the latest xl-ml run succeeded this op test and some of the other tests that this PR disables:
> 
> Screen Shot 2022-12-07 at 5 16 31 PM
> 
> What is the error `Received signal 6 & 11`? Could you paste the full error logs? I'm assuming it may be an error related to your TPUVM.

Thanks for the comment, I will test again and paste the full error logs here for each new-disabled test;

And do we have any example link about `test_setitem_scalars`'s result in the latest xl-ml, can we search that in the test dashboard? :
https://xl-ml-test.appspot.com/dashboard

About the test environment, I just updated the testing environment in the description, and do we have example or link about how the test environment set in xl-ml-test dashboard for python op tests? And do we have an example to check the test environment to avoid error related to the testing TPUVM environment setting?

**Comment by wonjoolee95** [comment]
You can find previous runs on the xl-ml dashboard, under tab "pt-nightly". On "pt-nightly-python-ops-func-v2-8" and "pt-nightly-python-ops-func-v2-8".

**Comment by wonjoolee95** [comment]
> I noticed that some tests only failed on TPUVM, that might be why?

I see, @ManfeiBai can we first just disable the python-op tests that is currently failing in the xl-ml?

**Comment by ManfeiBai** [comment]
> I noticed that some tests only failed on TPUVM, that might be why?

Thanks for the comment, are these failure information

> You can find previous runs on the xl-ml dashboard, under tab "pt-nightly". On "pt-nightly-python-ops-func-v2-8" and "pt-nightly-python-ops-func-v2-8".

Thanks, will do

**Comment by ManfeiBai** [comment]
> > I noticed that some tests only failed on TPUVM, that might be why?
> 
> I see, @ManfeiBai can we first just disable the python-op tests that is currently failing in the xl-ml?

yeah, sure, will do

**Comment by JackCaoG** [comment]
With this change, is TPUVM python op test currently passing?

**Comment by ManfeiBai** [comment]
> With this change, is TPUVM python op test currently passing?

with this change, all tests under `PyTorch/test` currently passing: 
(all the tests in the following files currently passing)
https://github.com/pytorch/xla/blob/master/test/run_tests.sh#L95-L107

the whole test stoped at `PyTorch/XLA/test_operations.py`, and we didn't try tests in `PyTorch/XLA/test_operations.py` and also skip all test files after this file:
https://github.com/pytorch/xla/blob/385aa7c37d8cfea40890b56a6886b9d242bcad76/test/run_tests.sh#L108

**Review by miladm — APPROVED** [review]
Looks good. Thanks @ManfeiBai.

Looks like we have a short description in front of every test that fails. This looks good.

I assume we will create an master issue with the list of all failing tests to keep track of fixes we make to bring the masked tests back in. Correct?

@ManfeiBai @wonjoolee95

**Comment by wonjoolee95** [comment]
Yes, that's the plan. @ManfeiBai, after we merge this, can we create an issue on GitHub to track this work? Thanks!

**Comment by ManfeiBai** [comment]
> Looks good. Thanks @ManfeiBai.
> 
> Looks like we have a short description in front of every test that fails. This looks good.
> 
> I assume we will create an master issue with the list of all failing tests to keep track of fixes we make to bring the masked tests back in. Correct?
> 
> @ManfeiBai @wonjoolee95

Thanks, Milad, issue created in https://github.com/pytorch/xla/issues/4319

**Comment by ManfeiBai** [comment]
> Yes, that's the plan. @ManfeiBai, after we merge this, can we create an issue on GitHub to track this work? Thanks!

Thanks, Wonjoo, issue created in https://github.com/pytorch/xla/issues/4319

**Pull request merged**
