### PR TITLE
[Profiler] Introduce trace_me decorator

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This pull request introduces a new profiler API called trace_me decorator. I find it very tedious if I want to scope a method as I need to first use the `xp.Trace("")` context manager and then indent the whole method. Now, you can just do:
```python
import torch_xla.debug.profiler as xp

@xp.trace_me("forward")
def forward:
...
```

Test Plan:
PJRT_DEVICE=CPU python test/test_operations.py -v -k XpTraceTest

### CODE REVIEW

**Comment by alanwaketan** [comment]
The PR is ready for review now.

**Review by wonjoolee95 — APPROVED** [review]
👍

**Comment by alanwaketan** [comment]
Thanks, Wonjoo.

**Review by miladm — COMMENTED** [review]
This is awesome! Thanks @alanwaketan!

**Comment by vanbasten23** [comment]
This is cool! Thanks. Just curious, what profiler info do you get when I apply `@xp.trace_me("forward")`?

**Comment by alanwaketan** [comment]
> This is cool! Thanks. Just curious, what profiler info do you get when I apply `@xp.trace_me("forward")`?

Some as you were using `with xp.Step(""):`.

**Pull request merged**
