### PR TITLE
adapt to the amp change on the pytorch side

### PR DESCRIPTION
**Pull request by yaochengji**
depends on the pytorch side [PR](https://github.com/pytorch/pytorch/pull/55562).

### CODE REVIEW

**Comment by JackCaoG** [comment]
Hi @yaochengji , thanks for making this change! Do you mind adding a torch pin? This should resolve the circle CI build failure

**Comment by yaochengji** [comment]
Sure. And it is done.

**Comment by yaochengji** [comment]
The CI failed because my PR depends on the pytorch side PR rebased on master branch, not the original one. I suppose we could wait for the pytorch side merged and take a look at this later.

**Comment by JackCaoG** [comment]
@yaochengji If pytorch pr merged, it will break PT/XLA build, let me ask the author to rebase his pytorch pr.

**Review by JackCaoG — APPROVED** [review]

**Pull request merged**
