### PR TITLE
Add narrow_copy to ATen XLA tensor

### PR DESCRIPTION
**Pull request by asuhan**

### CODE REVIEW

**Comment by asuhan** [comment]
Ok, so what should we do instead? This is like `narrow`, but it makes a copy.

**Comment by dlibenzi** [comment]
> Ok, so what should we do instead? This is like `narrow`, but it makes a copy.

AFAICT the PT native does a narrow+clone, and we have both. No?

**Comment by asuhan** [comment]
Hmmm that would be nice, isn't this just the autograd path though? Let me double check.

**Comment by asuhan** [comment]
Looks like we're good with `at::native::narrow_copy_dense` indeed, changed it to do that.

**Pull request merged**
