### PR TITLE
Update tf pin to 01/31/2023

### PR DESCRIPTION
**Pull request by vanbasten23**
Update tf pin to commit f9cf9416179f99c7a5afdaa3a34509a3d21af43c

### CODE REVIEW

**Comment by JackCaoG** [comment]
Before we doing this, can we confirm that it fixed the nonzero issue? Updating tf pin would require everyone to rebuild tf which is a bit annoying. I am also trying to fix a oom issue, which might require us to update the pin again.

**Comment by vanbasten23** [comment]
> Before we doing this, can we confirm that it fixed the nonzero issue? Updating tf pin would require everyone to rebuild tf which is a bit annoying. I am also trying to fix a oom issue, which might require us to update the pin again.

I'm working on that. Where can we see the list of available libtpu version? Also, to update libtpu version, is it simply changing the line https://github.com/pytorch/xla/blob/9cbcdb4008c14ad8251c5d4d7723aa616f659edb/setup.py#L63 locally and run `pip install torch-xla[tpuvm] --user`? I did that but it didn't install the version I wanted.

**Comment by JackCaoG** [comment]
@vanbasten23 I think you need to do a `python setup.py install` after you modify the `libtpU_version` and then `pip install torch-xla[tpuvm] --user`

**Comment by JackCaoG** [comment]
ok, so we need to at least once tf pin update before the 2.0 release. Let me see if I can also fix the OOM issue for resnet on v4.

**Comment by vanbasten23** [comment]
resnet speed also seems reasonable with xrt
```
Epoch 1 train begin 00:41:41
==> Preparing data..
| Training Device=xla:0/3 Epoch=1 Step=0 Loss=6.89059 Rate=3.62 GlobalRate=3.62 Time=00:42:17
| Training Device=xla:0/5 Epoch=1 Step=0 Loss=6.89059 Rate=3.63 GlobalRate=3.63 Time=00:42:17
| Training Device=xla:0/7 Epoch=1 Step=0 Loss=6.89059 Rate=3.62 GlobalRate=3.62 Time=00:42:17
| Training Device=xla:0/6 Epoch=1 Step=0 Loss=6.89059 Rate=4.41 GlobalRate=4.41 Time=00:42:17
| Training Device=xla:0/4 Epoch=1 Step=0 Loss=6.89059 Rate=3.51 GlobalRate=3.51 Time=00:42:17
| Training Device=xla:1/0 Epoch=1 Step=0 Loss=6.89059 Rate=3.47 GlobalRate=3.47 Time=00:42:17
| Training Device=xla:0/2 Epoch=1 Step=0 Loss=6.89059 Rate=3.56 GlobalRate=3.56 Time=00:42:17
| Training Device=xla:0/1 Epoch=1 Step=0 Loss=6.89059 Rate=3.69 GlobalRate=3.69 Time=00:42:17
| Training Device=xla:0/6 Epoch=1 Step=20 Loss=6.10956 Rate=37.37 GlobalRate=37.26 Time=00:43:01
| Training Device=xla:0/5 Epoch=1 Step=20 Loss=6.10956 Rate=37.05 GlobalRate=34.30 Time=00:43:01
| Training Device=xla:0/4 Epoch=1 Step=20 Loss=6.10956 Rate=37.00 GlobalRate=33.76 Time=00:43:01
| Training Device=xla:0/3 Epoch=1 Step=20 Loss=6.10956 Rate=37.05 GlobalRate=34.24 Time=00:43:01
| Training Device=xla:0/7 Epoch=1 Step=20 Loss=6.10956 Rate=37.05 GlobalRate=34.24 Time=00:43:01
| Training Device=xla:0/2 Epoch=1 Step=20 Loss=6.10956 Rate=37.03 GlobalRate=33.98 Time=00:43:01
| Training Device=xla:0/1 Epoch=1 Step=20 Loss=6.10956 Rate=37.08 GlobalRate=34.52 Time=00:43:01
| Training Device=xla:1/0 Epoch=1 Step=20 Loss=6.10956 Rate=36.98 GlobalRate=33.59 Time=00:43:01
| Training Device=xla:0/7 Epoch=1 Step=40 Loss=3.29797 Rate=244.56 GlobalRate=61.60 Time=00:43:07
| Training Device=xla:0/6 Epoch=1 Step=40 Loss=3.29797 Rate=244.26 GlobalRate=66.56 Time=00:43:07
| Training Device=xla:1/0 Epoch=1 Step=40 Loss=3.29797 Rate=244.73 GlobalRate=60.53 Time=00:43:07
| Training Device=xla:0/3 Epoch=1 Step=40 Loss=3.29797 Rate=244.33 GlobalRate=61.59 Time=00:43:07
| Training Device=xla:0/4 Epoch=1 Step=40 Loss=3.29797 Rate=244.28 GlobalRate=60.80 Time=00:43:07
| Training Device=xla:0/1 Epoch=1 Step=40 Loss=3.29797 Rate=244.39 GlobalRate=62.07 Time=00:43:07
| Training Device=xla:0/5 Epoch=1 Step=40 Loss=3.29797 Rate=244.30 GlobalRate=61.70 Time=00:43:07
| Training Device=xla:0/2 Epoch=1 Step=40 Loss=3.29797 Rate=244.34 GlobalRate=61.18 Time=00:43:07
```

**Comment by vanbasten23** [comment]
Close this as we need to include another xla fix. Will use https://github.com/pytorch/xla/pull/4554 instead.

**Pull request closed without merging**
