### PR TITLE
Update TF pin  for `libtpu-nightly==0.1.dev.20221223` compatible commit

### PR DESCRIPTION
**Pull request by yeounoh**
* New TF pin `dcb263292a9a48eaf58fe900cb9b12b90cb71e4d`
* Update `libtpu-nightly==0.1.dev.20221223`
* Remove `module_registry.cc` diff

### CODE REVIEW

**Comment by JackCaoG** [comment]
Can you verified that it runs on TPUVM and speed of resnet50 with fake data is roughly the same?

**Review by will-cromar — APPROVED** [review]

**Comment by yeounoh** [comment]
> Can you verified that it runs on TPUVM and speed of resnet50 with fake data is roughly the same?

Yea, tested with xrt and pjrt (TPU), the speed feels roughly the same (no vivid slowdown).

**Review by JackCaoG — APPROVED** [review]
Can you open a pr on upstream and make sure build can pass on upstream CI?

**Review by ManfeiBai — APPROVED** [review]

**Comment by yeounoh** [comment]
The upstream test passed, [pr](https://github.com/pytorch/pytorch/pull/91462) -- will merge.

**Pull request merged**
