### PR TITLE
[WIP] Partially Codegen Atan2

### PR DESCRIPTION
**Pull request by ManfeiBai**
partially codegen atan2

---

Generated `LazyIr.h`:

```
class Atan2 : public XlaNode {
 public:
  static torch::lazy::OpKind ClassOpKind() {
    return torch::lazy::OpKind(at::aten::atan2);
  }

  Atan2(const torch::lazy::Value& self, const torch::lazy::Value& other)
      : XlaNode(torch::lazy::OpKind(at::aten::atan2),
              {self, other},
              [&]() { return Atan2OutputShape(self, other); },
              /* num_outputs */ 1,
              torch::lazy::MHash())
  {
    
  }

  std::string ToString() const override {
    std::stringstream ss;
    ss << XlaNode::ToString();
    
    return ss.str();
  }

  

  bool CanBeReused(const torch::lazy::Value& self, const torch::lazy::Value& other) const {
    return false;
    }

  torch_xla::XlaOpVector Lower(LoweringContext* loctx) const override;

  
  

};
```

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Feel free to assign this to me whenever it's ready for review. Also feel free to @ me to ask any questions here as well.

**Comment by wonjoolee95** [comment]
For one of the build errors on CI:
```
/tmp/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:3072:22: error: no member named 'narrow_copy_dense' in namespace 'at::native'
  return at::native::narrow_copy_dense(self, dim, start, length);
         ~~~~~~~~~~~~^
```
Rebasing with the latest master will fix the issue.

**Comment by ManfeiBai** [comment]
> Feel free to assign this to me whenever it's ready for review. Also feel free to @ me to ask any questions here as well.

Thanks, Wonjoo!

**Comment by ManfeiBai** [comment]
> For one of the build errors on CI:
> 
> ```
> /tmp/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:3072:22: error: no member named 'narrow_copy_dense' in namespace 'at::native'
>   return at::native::narrow_copy_dense(self, dim, start, length);
>          ~~~~~~~~~~~~^
> ```
> 
> Rebasing with the latest master will fix the issue.

Thanks, I will~

**Pull request closed without merging**
