### PR TITLE
[Pin Update] Version 20230826(#5527)

### PR DESCRIPTION
**Pull request by ManfeiBai**
Cherry-pick https://github.com/pytorch/xla/pull/5527 onto the r2.1 branch.

Test plan: CI

### CODE REVIEW

**Review by wonjoolee95 — COMMENTED** [review]
Thanks, let's wait for the CI to verify.

**Comment by alanwaketan** [comment]
@ManfeiBai Have we tested that this pin update fix your GPU issue?

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Review by wonjoolee95 — APPROVED** [review]

**Comment by wonjoolee95** [comment]
> @ManfeiBai Have we tested that this pin update fix your GPU issue?

Good point. @ManfeiBai, can you open an PR on master to re-enable the FSDP GPU unit tests?

**Comment by ManfeiBai** [comment]
> > @ManfeiBai Have we tested that this pin update fix your GPU issue?
> 
> Good point. @ManfeiBai, can you open an PR on master to re-enable the FSDP GPU unit tests?

thanks, created in https://github.com/pytorch/xla/pull/5561

**Comment by ManfeiBai** [comment]
> > > @ManfeiBai Have we tested that this pin update fix your GPU issue?
> > 
> > 
> > Good point. @ManfeiBai, can you open an PR on master to re-enable the FSDP GPU unit tests?
> 
> thanks, created and test in CI of #5561

failed due to OOM on GPU CI, will test locally

**Comment by ManfeiBai** [comment]
> > > > @ManfeiBai Have we tested that this pin update fix your GPU issue?
> > > 
> > > 
> > > Good point. @ManfeiBai, can you open an PR on master to re-enable the FSDP GPU unit tests?
> > 
> > 
> > thanks, created and test in CI of #5561
> 
> failed due to OOM on GPU CI, will test locally

FSDP unit test passed on GPU locally

**Pull request merged**
