### PR TITLE
Add unit test for dynamo+training for pytorch/xla

### PR DESCRIPTION
**Pull request by JackCaoG**
Add unit test for dynamo + training

There are two TODO

1. When I run the test I saw
```
/pytorch/torch/_functorch/aot_autograd.py:922: UserWarning: Your compiler for AOTAutograd is returning a a function that doesn't take boxed arguments. Please wrap it with functorch.compile.make_boxed_func or handle the boxed arguments yourself. See https://github.com/pytorch/pytorch/pull/83137#issuecomment-1211320670 for rationale.
  "Your compiler for AOTAutograd is returning a a function that doesn't take boxed arguments. "
```

2. counter after running the resnet18 doesn't make sense, and that counter seems to have different value when I run it with other tests even if I added a `met.clear_counters()` in the front.

FYI @wconstab @shunting314

### CODE REVIEW

**Comment by wconstab** [comment]
for the boxed-arguments thing, i wonder if AOT got pickier recently? I don't know what changed there.

can you share more about what the counter is showing?

**Comment by JackCaoG** [comment]
Currently if I run the resnet18 test for training for 10 steps, there are 12 graphs being compiled and 77 execution happened. I was expecting ~5 graphs compiled and ~50 execution. Need to look into those numbers a bit more.

**Comment by JackCaoG** [comment]
@alanwaketan @wonjoolee95 can I get a reivew? I will investigate the `ExecuteTIme` and `CompileTime` in a separate pr, want to make sure at least correctness part of the test is merged.

**Review by wonjoolee95 — APPROVED** [review]
Thanks!

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Pull request merged**
