### PR TITLE
Set PyTorch git revision to v2.1.0-rc5 for 2.1 releases

### PR DESCRIPTION
**Pull request by ManfeiBai**
Set PyTorch git revision to v2.1.0-rc5 for 2.1 releases

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Seems like their latest 2.1 rc wheel is rc5:
```
wonjoo-macbookpro:pytorch wonjoo$ git tag -l '*v2.1*'
v2.1.0-rc1
v2.1.0-rc2
v2.1.0-rc3
v2.1.0-rc4
v2.1.0-rc5
```
Can you update it that?

**Comment by ManfeiBai** [comment]
> Seems like their latest 2.1 rc wheel is rc5:
> 
> ```
> wonjoo-macbookpro:pytorch wonjoo$ git tag -l '*v2.1*'
> v2.1.0-rc1
> v2.1.0-rc2
> v2.1.0-rc3
> v2.1.0-rc4
> v2.1.0-rc5
> ```
> 
> Can you update it that?

Thanks, updated

**Review by wonjoolee95 — APPROVED** [review]

**Comment by wonjoolee95** [comment]
@will-cromar, can you take a look at this? This updates the PyTorch git tag to their latest RC, `v2.1.0-rc5` -- https://github.com/pytorch/pytorch/tree/v2.1.0-rc5. Thanks!

**Review by will-cromar — APPROVED** [review]
Thanks!

We can update the `v2.0.0` tag and kick off new builds when we fix the `r2.1` branch and finish cherry-picking

**Comment by wonjoolee95** [comment]
Cool, seems like updating the pin on the r2.1 branch will fix the build error -- https://github.com/pytorch/xla/pull/5575. Let's wait until we merge https://github.com/pytorch/xla/pull/5575, and then merge this PR, @ManfeiBai.

**Comment by will-cromar** [comment]
Can you also update the build I added in #5564 when you merge this?

**Comment by ManfeiBai** [comment]
> Thanks!
> 
> We can update the `v2.0.0` tag and kick off new builds when we fix the `r2.1` branch and finish cherry-picking

do we want to change 2.0.0 tag for now before finish all cherry-picking?

**Comment by wonjoolee95** [comment]
> do we want to change 2.0.0 tag for now before finish all cherry-picking?

We can do it after all the cherry-picking, which should ideally be EOD or tomorrow morning.

**Comment by wonjoolee95** [comment]
@ManfeiBai, fyi you'll need to rebase this PR with master to see Will's new build (https://github.com/pytorch/xla/pull/5564).

**Comment by ManfeiBai** [comment]
> #5564

Thanks, rebased and updated

**Review by wonjoolee95 — APPROVED** [review]

**Review by will-cromar — APPROVED** [review]

**Pull request merged**
