### PR TITLE
Update CONTRIBUTING.md XRT Instructions

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
Update XRT_TPU_CONFIG specification.

Test Plan:
[skip ci]

### CODE REVIEW

**Comment by alanwaketan** [comment]
Need more research to figure out 2VM v.s. 1VM before making this update.

**Review by JackCaoG — COMMENTED** [review]
Instead of replacing, I think it is better to list out for `TPU node`(2vm) you need x and for `TPUVM` you need y

**Comment by JackCaoG** [comment]
I changed my mind.. let's get rid of everything about 2vm. We can reabse and merge this pr..

**Review by JackCaoG — APPROVED** [review]

**Comment by alanwaketan** [comment]
> I changed my mind.. let's get rid of everything about 2vm. We can reabse and merge this pr..

That's great. However, do we have some forms of this knowledge preserved elsewhere?

**Comment by alanwaketan** [comment]
Also, this change only modified README. Therefore, I guess we don't care about CI. We can merge directly.

**Comment by miladm** [comment]
Is there a reason this PR is yet to be merged? @alanwaketan

**Review by miladm — APPROVED** [review]
LGTM

**Pull request merged**
