### PR TITLE
Added acos, cosh, asin, asinh unary ops

### PR DESCRIPTION
**Pull request by vishwakftw**

### CODE REVIEW

**Comment by dlibenzi** [comment]
This is still breaking CI.
Code looks OK otherwise, but I will ACK when CI is green.

**Comment by dlibenzi** [comment]
ACK if the previous error is the adaptive avg pool rename breakage.

**Comment by vishwakftw** [comment]
I went through the logs, and seems like it:
```
/tmp/pytorch/xla/torch_xla/csrc/aten_xla_type.h:200:68: error: only virtual member functions can be marked 'override'
      const at::Tensor& grad_output, const at::Tensor& self) const override;
                                                                   ^~~~~~~~
torch_xla/csrc/aten_xla_type.cpp:593:12: error: no member named 'adaptive_avg_pool2d_backward' in 'torch_xla::AtenXlaTypeBase'; did you mean simply 'adaptive_avg_pool2d_backward'?
    return AtenXlaTypeBase::adaptive_avg_pool2d_backward(grad_output, self);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           adaptive_avg_pool2d_backward
torch_xla/csrc/aten_xla_type.cpp:590:25: note: 'adaptive_avg_pool2d_backward' declared here
at::Tensor AtenXlaType::adaptive_avg_pool2d_backward(
                        ^
torch_xla/csrc/aten_xla_type.cpp:598:12: error: no member named 'adaptive_avg_pool2d_backward' in 'torch_xla::AtenXlaTypeBase'; did you mean simply 'adaptive_avg_pool2d_backward'?
    return AtenXlaTypeBase::adaptive_avg_pool2d_backward(grad_output, self);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           adaptive_avg_pool2d_backward
torch_xla/csrc/aten_xla_type.cpp:590:25: note: 'adaptive_avg_pool2d_backward' declared here
at::Tensor AtenXlaType::adaptive_avg_pool2d_backward(
                        ^
```

**Comment by dlibenzi** [comment]
Yeah, unrelated.
We are looking into it.

**Comment by vishwakftw** [comment]
Sure, thank you.

**Pull request merged**
