### PR TITLE
Run TPU CI when label is on PR

### PR DESCRIPTION
**Pull request by will-cromar**

### CODE REVIEW

**Comment by JackCaoG** [comment]
haha I was thinking about trying to add this today. Thanks!

**Review by ManfeiBai — APPROVED** [review]
Thanks, Will! LGTM

**Comment by will-cromar** [comment]
The TPU tests still got skipped :thinking:

**Comment by will-cromar** [comment]
The TPU tests are running! You have to make a commit _after_ adding the `tpuci` label or GHA will ignore it.

**Pull request merged**
