### PR TITLE
Fix the location of libxla_computation_client.so

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #3961
* #3960
* __->__ #3959

Summary:
Update the location of libxla_computation_client.so to the correct place
while building the cpp test binary.

Test Plan:
CI for builiding the cpp test binary.

### CODE REVIEW

**Comment by JackCaoG** [comment]
rebase should fix the ci issue

**Review by will-cromar — APPROVED** [review]
LGTM. The new path looks correct. Why didn't we run into an issue before now?

**Comment by alanwaketan** [comment]
> LGTM. The new path looks correct. Why didn't we run into an issue before now?

That's a good question. I don't know. Maybe worth looking into if the CI runs the C++ tests.

**Comment by alanwaketan** [comment]
> > LGTM. The new path looks correct. Why didn't we run into an issue before now?
> 
> That's a good question. I don't know. Maybe worth looking into if the CI runs the C++ tests.

Looks like we do run the C++ tests... So, mysterious...

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
@alanwaketan can we merge pr with ghstack using UI ?

**Comment by alanwaketan** [comment]
> @alanwaketan can we merge pr with ghstack using UI ?

I don't think so. Also, I'm not even sure if the CI is taking the right changes.

**Comment by JackCaoG** [comment]
In the log I found
```
HEAD is now at ae6aa74f Update on "Fix the location of libxla_computation_client.so"
```

I think it test the right change

**Comment by alanwaketan** [comment]
Cool, which means we can safely use ghstack at will.

**Comment by JackCaoG** [comment]
question.. you merged this into your base branch. When are you going to merge base branch into master?

**Comment by alanwaketan** [comment]
> question.. you merged this into your base branch. When are you going to merge base branch into master?

Got some error while trying to merge the this pull request. I got used to "@pytorchbot merge", and never use the ghstack CLI. Let me dig into it.

**Comment by alanwaketan** [comment]
No idea what's going on even after digging into the code https://github.com/ezyang/ghstack/blob/74cb549c28e35b3ec73973978e3049c4eeea0992/ghstack/land.py#L37. I guess I can manually merge this one using the gh/alanwaketan/1/orig branch... We can try to see if the next also fails.

**Comment by JackCaoG** [comment]
lol we need a xla bot

**Pull request merged**
