### PR TITLE
Create MatMul op to build MatMul with bias op

### PR DESCRIPTION
**Pull request by yeounoh**
This helps improve matmul with bias computation and partially addresses the performance regression with ViT model. This replaces `Dot` with`CreateMatMul` op, which actually calls `Dot` internally if it's simpler multiplications and calls `DotGeneral` otherwise.

### CODE REVIEW

**Comment by JackCaoG** [comment]
failure is unrelated, if you rebase it should go away.

**Comment by JackCaoG** [comment]
ok, nvm. I think it is actually something from the upstram, it should be one of those dynamic shape pr break us. Will check with Nick on Tuesday.

**Comment by JackCaoG** [comment]
@yeounoh Did you verified that with this fix, regression went away?

**Comment by JackCaoG** [comment]
ping, is this pr ready?

**Comment by yeounoh** [comment]
> ping, is this pr ready?

Hey @JackCaoG the PR is not ready. Let me continue the investigation.

**Comment by yeounoh** [comment]
Making the change in PyTorch, https://github.com/pytorch/pytorch/pull/84503 instead. closing this PR without merging.

**Pull request closed without merging**
