### PR TITLE
Companion PR for #80074

### PR DESCRIPTION
**Pull request by Lezcano**
As per title.

I do not know how to target this PR to be tested on 80074 in CI. Is that
possible?

### CODE REVIEW

**Comment by JackCaoG** [comment]
yea, you can add a torch pin like https://github.com/pytorch/xla/pull/3303, just put the pr number in the `.torch_pin` file and CI will check out your pr when doing the test.

**Comment by Lezcano** [comment]
The CI is green!

**Review by JackCaoG — APPROVED** [review]
Thanks! I think you can pin your pytorch pr to this branch(put branch name or your first commit `1914f8befcfad86c3799c3049bd67c4595a4cd11`in the `xla.txt`). before merging your pytorch pr, you want to rebase this branch. merge your pytorch pr. Remove the torch_pin from this branch and then merge pytorch/xla pr.

**Comment by JackCaoG** [comment]
You can either give me a ping to merge this pr. Merging this branch is the last step anyway.

**Comment by Lezcano** [comment]
Now the CI has gone red, but it seems unrelated. What should we do?

**Comment by Lezcano** [comment]
Also, fixing the pin in https://github.com/pytorch/pytorch/pull/80074 to the hash of this PR didn't work. I think it may be because I'm creating this PR from my external clone of XLA, rather than from the main repo (I didn't have the rights to work on the main repo directly)

**Comment by JackCaoG** [comment]
@Lezcano Oh yea. I will grant you the write access so you can create branch on pt/xla directly. The CI issue can be fixed by a new branch or rebase.

**Comment by JackCaoG** [comment]
@Lezcano I have grant you the write access, I think you need to accept it. Can you try to open a new branch(from pytorch/xla directly) and pin the upstream? CI should pass.

**Comment by Lezcano** [comment]
Opened https://github.com/pytorch/xla/pull/3918 from the branch that the PyTorch PR is targeting. Let's merge that one to be fully consistent.

**Pull request closed without merging**
