### PR TITLE
Properly lower aten::lerp

### PR DESCRIPTION
**Pull request by wonjoolee95**
Fixes https://github.com/pytorch/xla/issues/6294

---

Test plan: CI

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Comment by vanbasten23** [comment]
Thanks for fixing it! Can you explain a bit why the previous aten::lerp is not done properly? It seems previously we use the same logic `start + weight * (end - start);`

**Comment by wonjoolee95** [comment]
Sure thing -- so previously, we just did an IR level computation which is slower (and isn't really "lowered"). This PR lowers it properly into XlaOp level, which is what we want to do.

**Comment by bhavya01** [comment]
@wonjoolee95 Did you notice a change in the dispatcher trace after this PR was merged. I still see the same trace as https://github.com/pytorch/xla/issues/6294#issuecomment-1898905975

```
 [call] op=[aten::lerp.Scalar], key=[AutogradXLA]
  [redispatch] op=[aten::lerp.Scalar], key=[Functionalize]
   [callBoxed] op=[aten::lerp.Scalar], key=[XLA]
    [call] op=[aten::scalar_tensor], key=[BackendSelect]
     [redispatch] op=[aten::scalar_tensor], key=[CPU]
    [call] op=[aten::to.dtype_layout], key=[BackendSelect]
     [redispatch] op=[aten::to.dtype_layout], key=[CPU]
      [call] op=[aten::_to_copy], key=[BackendSelect]
       [redispatch] op=[aten::_to_copy], key=[CPU]
        [call] op=[aten::empty_strided], key=[BackendSelect]
         [redispatch] op=[aten::empty_strided], key=[CPU]
        [call] op=[aten::copy_], key=[CPU]
    [call] op=[aten::to.dtype_layout], key=[BackendSelect]
     [redispatch] op=[aten::to.dtype_layout], key=[CPU]
      [call] op=[aten::_to_copy], key=[BackendSelect]
       [redispatch] op=[aten::_to_copy], key=[CPU]
        [call] op=[aten::empty.memory_format], key=[BackendSelect]
         [redispatch] op=[aten::empty.memory_format], key=[CPU]
        [call] op=[aten::copy_], key=[CPU]
```

I was just running this script:
```
import torch
import torch_xla.core.xla_model as xm
x = torch.tensor([2,4,6,8], dtype=torch.float, device=xm.xla_device())
y = torch.tensor([2.0, 2.0, 2.0, 2.0], device=xm.xla_device())
z = torch.lerp(x, y, 0.5)
```

**Comment by anw90** [comment]
> @wonjoolee95 Did you notice a change in the dispatcher trace after this PR was merged. I still see the same trace as [#6294 (comment)](https://github.com/pytorch/xla/issues/6294#issuecomment-1898905975)

I observed the same issue here. I'm testing the PR (https://github.com/pytorch/xla/pull/6339) and found that the slow tracing of Adam still exists:

As described in this thread (https://dev-discuss.pytorch.org/t/decomposition-slows-down-the-lazy-tensor-tracing/1788/3?u=angwang), I exported some timelines with stacks from the test 'test/test_train_mp_imagenet.py' after patching the aforementioned PR. Here is the tar package containing the timelines: https://drive.google.com/file/d/11Po6AG_ry8JJLRMBAb3veY13EYU-Ynrp/view?usp=sharing

From the timeline , we can observe that the tracing of `lerp` op is still trapped in decomposition. 
image

And also, I have reimplemented the lowering of `aten::sub` and `aten::rsub` (https://github.com/pytorch/xla/pull/6668). It appears that the issue of slow tracing still exists.

I'm wondering if re-implementing the lowering could solve the problem?

**Comment by anw90** [comment]
Here is the tracing stack of `aten::sub` after re-implementing the lowering: 
image

**Comment by anw90** [comment]
@wonjoolee95 Do we have any conclusion on whether the re-implementing lowering is still needed?

**Comment by wonjoolee95** [comment]
Apologies for the late reply as I was involved in some urgent items last week, @anw90.

Let's do this -- as seen from the profiles in the comments above, it is clear that these ops are invoked and we do want to properly lower these ops. Whether lowering of these ops will completely remove the slow tracing time with functionalization can be investigated in parallel. With that said, I noticed the CI seems to be failing for https://github.com/pytorch/xla/pull/6668 with seemingly real errors (related to dynamic shape). Let me know if you need further help investigating the failures on that CI.

**Pull request merged**
