### PR TITLE
Remove the enumerate-like parallel loader iterator behavior.

### PR DESCRIPTION
**Pull request by dlibenzi**
FYI, @taylanbil ... will this change need to be matched with FARISEQ change?

### CODE REVIEW

**Comment by taylanbil** [comment]
Yes, this will break fairseq. Thanks for the heads up, I will fix it soon.

**Comment by tmabraham** [comment]
Just confirming this changes the behavior for both the multiprocessing and multithreading API?

**Comment by dlibenzi** [comment]
> Just confirming this changes the behavior for both the multiprocessing and multithreading API?

Yes, as underneath they use the same iterator.
In theory with multi-processing you can even not use the ParallelLoader, but your `tensor.to(device)` call will be serialized before the model execution, which results in performance drop.

**Comment by tmabraham** [comment]
Also have the colab notebooks be updated to reflect this change?

@dlibenzi so is there a performance difference between multiprocessing and multithreading API? If so, why is using MP recommended in the API guide?

**Comment by dlibenzi** [comment]
> Also have the colab notebooks be updated to reflect this change?
> 
> @dlibenzi so is there a performance difference between multiprocessing and multithreading API? If so, why is using MP recommended in the API guide?

Good point about Colabs ... they are currently pinned to the 0.5 release, so they are fine.
We will be following up with a cherry-pick of this change, and modify those as well.

There is difference in performance between multi-thread based and multi-process based replication.
The bigger the work the model does in Python, the higher it is.
We have seen 20..30% boost using multi-processing on resnet50 and transformer.

**Comment by tmabraham** [comment]
@dlibenzi Ah ok sounds good.

**Pull request merged**
