### PR TITLE
Optimize autocast tests.

### PR DESCRIPTION
**Pull request by vanbasten23**
This PR speeds up the test_autocast by setting up autocast_lists, autocast_lists_extra, autocast_unsupported_lists before each test suite instead of each test.

The test suite test_autocast.py has been really slow. (Takes 82 min for [TestAutocastCuda](https://screenshot.googleplex.com/9pjvMCmhYLzGN8W) on HEAD because it creates a new autocast_lists, autocast_lists_extra, autocast_unsupported_lists for each test.

The test `_run_autocast_outofplace` cast out of place, and tensor.to(dtype) returns a copy of the tensor so each test does not change the input tensor. I print the `op and args` in`for op, args in TestAutocastCuda.get_autocast_list('linalg_fp16')` before and after the test runs and the result seems to be identical.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Nice! I guess the timeout we saw in the pin update is not a real regression then?

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Comment by vanbasten23** [comment]
> Nice! I guess the timeout we saw in the pin update is not a real regression then?

I summarized in this [ticket](b/314169482). I ran a commented out test and compared `met.metrics_report()` and HLO, before and after pin update. The results are very close. So I don't think autocast regressed.

**Review by yeounoh — COMMENTED** [review]
This is great, thanks @vanbasten23

**Pull request merged**
