### PR TITLE
[SPMD] Set replicated output false

### PR DESCRIPTION
**Pull request by yeounoh**
After benchmarking and testing we are more confident that we could/should leave output sharding by default.

I also made a slight change to one of the existing unit tests, for partial replication.

### CODE REVIEW

**Comment by yeounoh** [comment]
cc @wonjoolee95 i noticed that you were using the default config, which replicates the output. Let's rebase and rerun your experiment (dynamo+spmd) after this change.

**Review by jonb377 — APPROVED** [review]
LGTM

**Review by JackCaoG — APPROVED** [review]

**Comment by wonjoolee95** [comment]
> cc @wonjoolee95 i noticed that you were using the default config, which replicates the output. Let's rebase and rerun your experiment (dynamo+spmd) after this change.

Sounds good, thanks for the heads-up.

**Review by wonjoolee95 — APPROVED** [review]

**Comment by JackCaoG** [comment]
This CL breaks TPU CI, revert for now.

**Pull request merged**
