### PR TITLE
XLA bindings for torch_neuronx.trace and profile bindings

### PR DESCRIPTION
**Pull request by mrnikwaws**
### Summary
These changes add on top of https://github.com/pytorch/pytorch/pull/107827 they allow special scalars to be turned on and temporarily disabling device tensor caching for the purpose of consistently lowering HLO for AOT compilation.  Similarly the debug variable bindings allow python code to turn meta-data lowering to HLO off and on in python.

Both additions can be used to create context which limit the scope of changed behavior in the XLA runtime.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Comment by mrnikwaws** [comment]
@JackCaoG is there a way to trigger the rebuild check?  This should work now the pytorch change is merged.

**Comment by JackCaoG** [comment]
yea I triggered the build again

**Comment by mrnikwaws** [comment]
Thanks!

**Comment by JackCaoG** [comment]
@wonjoolee95 can you help cherry-picking this one into 2.1?

**Pull request merged**
