### PR TITLE
Pull latest changes for TensorFlow

### PR DESCRIPTION
**Pull request by wonjoolee95**
This reverts commit ff079bb48744e5aa6696201ccf34057f15fc7cac.

So, this PR:
- Pulls latest changes for TensorFlow
- Fix build issues that rises with it

Refer to https://github.com/pytorch/xla/pull/3298 for some more context.

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Can also confirm that running the failed test `TestConv3DNonSquare` succeeds locally:
```
[----------] Global test environment set-up.
[----------] 1 test from TensorTest
[ RUN      ] TensorTest.TestConv3DNonSquare
2022-01-25 06:58:25.152082: I 1820482 tensorflow/compiler/xla/xla_client/xrt_local_service.cc:40] Peer localservice 1 {localhost:40934}
2022-01-25 06:58:25.152470: I 1820482 tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-25 06:58:25.222190: I 1820482 tensorflow/compiler/xla/service/service.cc:170] XLA service 0x2f4f540 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-01-25 06:58:25.222269: I 1820482 tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Host, Default Version
2022-01-25 06:58:25.266092: I 1820482 tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localservice -> {0 -> localhost:40934}
2022-01-25 06:58:25.268555: I 1820482 tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:437] Started server with target: grpc://localhost:40934
2022-01-25 06:58:25.967363: I 1820569 tensorflow/compiler/jit/xla_device.cc:428] XLA_GPU and XLA_CPU devices are deprecated and will be removed in subsequent releases. Instead, use either @tf.function(jit_compile=True) for must-compile semantics, or run with TF_XLA_FLAGS=--tf_xla_auto_jit=2 for auto-clustering best-effort compilation.

[       OK ] TensorTest.TestConv3DNonSquare (451667 ms)
[----------] 1 test from TensorTest (451667 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (451667 ms total)
[  PASSED  ] 1 test.

```

**Comment by wonjoolee95** [comment]
`TestConv3DNonSquare` keeps failing in PyTorch CircleCI. Trying to disable this test for now and see if PyTorch CircleCI can succeed. Issue for tracking this disabled test -- https://github.com/pytorch/xla/issues/3316.

**Comment by yeounoh** [comment]
> `TestConv3DNonSquare` keeps failing in PyTorch CircleCI. Trying to disable this test for now and see if PyTorch CircleCI can succeed. Issue for tracking this disabled test -- #3316.

Great, before we merge this, let's update `setup.py` so that it specifies the correct/matching `libtpu-nightly` version. This is not a blocker on circleci, but if someone wants to build master, it will break.

**Comment by JackCaoG** [comment]
```
FAILED: /tmp/pytorch/xla/build/temp.linux-x86_64-3.7/torch_xla/csrc/tensor_impl.o 
clang++-8 -MMD -MF /tmp/pytorch/xla/build/temp.linux-x86_64-3.7/torch_xla/csrc/tensor_impl.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -I/tmp/pytorch/xla -I/tmp/pytorch/xla/third_party/tensorflow/bazel-tensorflow -I/tmp/pytorch/xla/third_party/tensorflow/bazel-bin -I/tmp/pytorch/xla/third_party/tensorflow/bazel-tensorflow/external/protobuf_archive/src -I/tmp/pytorch/xla/third_party/tensorflow/bazel-tensorflow/external/com_google_protobuf/src -I/tmp/pytorch/xla/third_party/tensorflow/bazel-tensorflow/external/eigen_archive -I/tmp/pytorch/xla/third_party/tensorflow/bazel-tensorflow/external/com_google_absl -I/tmp/pytorch -I/tmp/pytorch/torch/csrc -I/tmp/pytorch/torch/lib/tmp_install/include -I/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/include -I/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/include/THC -I/opt/conda/envs/pytorch/include/python3.7m -c -c /tmp/pytorch/xla/torch_xla/csrc/tensor_impl.cpp -o /tmp/pytorch/xla/build/temp.linux-x86_64-3.7/torch_xla/csrc/tensor_impl.o -std=c++14 -Wno-sign-compare -Wno-deprecated-declarations -Wno-return-type -Wno-macro-redefined -Wno-return-std-move -DNDEBUG -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_XLAC -D_GLIBCXX_USE_CXX11_ABI=1
/tmp/pytorch/xla/torch_xla/csrc/tensor_impl.cpp:144:34: error: no member named 'int64_t' in namespace 'xla'
        xla::util::ToVector<xla::int64_t>(shape.get().dimensions()));
```

Seems like we need a rebase. I think we should try to merge this change before Friday, let's resolve the conflicts now

**Comment by wonjoolee95** [comment]
Rebased with latest changes and fixed some newly introduced build failures.

**Comment by wonjoolee95** [comment]
Pulled in latest changes from PTXLA again.

**Pull request merged**
