### PR TITLE
Revert "Don't set $TPU_LIBRARY_PATH during import (#5698)"

### PR DESCRIPTION
**Pull request by alanwaketan**
This reverts commit 146f2a0140c5217a31d55cfdebb1efb6bc05b41a.

It regresses the profiler.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
hmm, I wonder why

**Comment by alanwaketan** [comment]
> hmm, I wonder why

No ideas...

**Review by will-cromar — APPROVED** [review]
Do you have any more details? If the profiler depends on `$TPU_LIBRARY_PATH`, we should fix this upstream.

**Comment by alanwaketan** [comment]
> Do you have any more details? If the profiler depends on `$TPU_LIBRARY_PATH`, we should fix this upstream.

Do you have the more details you need in the gchat?

**Pull request merged**
