### PR TITLE
Support divwith rouning mode

### PR DESCRIPTION
**Pull request by JackCaoG**
This is to fix https://github.com/pytorch/xla/issues/2741. Pytorch change the signature for `div` in https://github.com/pytorch/pytorch/pull/50280 

The solution is to append a `trunc` or `floor` depending on the `rounding_mode` provided.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks @JackCaoG ! The lowering part LGTM! 
One small nit according to https://github.com/pytorch/pytorch/pull/50280/files#diff-6d5fd984918d72e20343e25ddc0acf96e77ea3c6e548a1153698b0d970830407R222 which simply redirects to div_out as well. Maybe add a test case to see whether it's necessary?

**Comment by JackCaoG** [comment]
> Thanks @JackCaoG ! The lowering part LGTM!
> One small nit according to https://github.com/pytorch/pytorch/pull/50280/files#diff-6d5fd984918d72e20343e25ddc0acf96e77ea3c6e548a1153698b0d970830407R222 which simply redirects to div_out as well. Maybe add a test case to see whether it's necessary?

sounds good, I will add a test for that `div` api

**Comment by JackCaoG** [comment]
Looking into gpu test failure

```
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()

t1 = torch.tensor(-47, dtype=torch.int16, device=device)
t2 = torch.tensor(47, dtype=torch.int16, device=device)

import pdb; pdb.set_trace()
print(torch.divide(t1, t2, rounding_mode="trunc"))
```

give
```
tensor(-0., device='xla:1')
```

on cpu
```
(Pdb) print(torch.divide(t1.cpu(), t2.cpu(), rounding_mode="trunc"))
tensor(-1, dtype=torch.int16)
```

**Comment by JackCaoG** [comment]
`trunc` actually uses `abs` and `floor` and I observe
```
(Pdb) torch.abs(t1/t2)
tensor(1.0000, device='xla:1')
(Pdb) torch.abs(t1/t2) >= 1
tensor(False, device='xla:1')
```

This seems to be a precision issue with int16, will work around it in the test.

**Review by ailzhang — APPROVED** [review]
Thanks!

**Pull request merged**
