### PR TITLE
Companion PR for pytorch/pytorch#106272

### PR DESCRIPTION
**Pull request by nkaretnikov**

### CODE REVIEW

**Comment by nkaretnikov** [comment]
Added meta for median in https://github.com/pytorch/pytorch/pull/106272, which affected the counters.

**Comment by nkaretnikov** [comment]
Forgot to rebase on origin/master, fixed now.

**Comment by JackCaoG** [comment]
yea any op that will fallback in pytorch/xla will do I believe

**Comment by wonjoolee95** [comment]
Thanks @nkaretnikov, `aten::_foobar` is perfect. We'll merge https://github.com/pytorch/xla/pull/5393 as soon as its CI is green and your https://github.com/pytorch/pytorch/pull/106272 should be unblocked.

**Comment by nkaretnikov** [comment]
@wonjoolee95 sounds good, closing this one, then!

**Pull request closed without merging**
