### PR TITLE
Add NEURON device type check to certain operations

### PR DESCRIPTION
**Pull request by aws-kingrj**
- tested with AWS Neuron
- Need to also check on NEURON device type in same places as TPU since previously NEURON used the same device type

### CODE REVIEW

**Comment by JackCaoG** [comment]
let me know when this pr is ready for review

**Comment by JackCaoG** [comment]
@will-cromar can you take a look at this one?

**Comment by aws-kingrj** [comment]
Hey, we are still testing this it will need more changes

**Review by jeffhataws — CHANGES_REQUESTED** [review]
Don't merge yet. We are seeing issues in testing with this change.

**Comment by jeffhataws** [comment]
This PR should be ready to merge now @JackCaoG

**Review by will-cromar — APPROVED** [review]

**Comment by JackCaoG** [comment]
Can you resolve the merge conflict? Then we can start merging

**Comment by aws-kingrj** [comment]
Fixed

**Comment by jeffhataws** [comment]
Error:

```
torch_xla/csrc/data_ops.cpp:32:54: error: 'GetCurrentDevice' was not declared in this scope; did you mean 'torch_xla::bridge::GetCurrentDevice'?
   32 |   XlaDeviceType hw_type = static_cast<XlaDeviceType>(GetCurrentDevice().type());
      |                                                      ^~~~~~~~~~~~~~~~
      |                                                      torch_xla::bridge::GetCurrentDevice
In file included from torch_xla/csrc/data_ops.cpp:11:
./torch_xla/csrc/aten_xla_bridge.h:97:28: note: 'torch_xla::bridge::GetCurrentDevice' declared here
   97 | torch::lazy::BackendDevice GetCurrentDevice();
      |                            ^~~~~~~~~~~~~~~~
```

**Comment by aws-kingrj** [comment]
Fixed the error

**Pull request merged**
