### PR TITLE
Revert "Update 81058.diff"

### PR DESCRIPTION
**Pull request by atalman**
This reverts commit a62fe9039cd162564f535dd6869e806586d43718.

### CODE REVIEW

**Comment by JackCaoG** [comment]
@atalman has the upstream change also reverted?

**Comment by atalman** [comment]
@JackCaoG I don't see upstream change https://github.com/pytorch/xla/commits/master

**Comment by JackCaoG** [comment]
xla test at 2.0 head is green now, I don't think we need to revert this pr

**Comment by steventk-g** [comment]
Updated to https://github.com/pytorch/xla/commit/a62fe9039cd162564f535dd6869e806586d43718
To revert https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L52
FYI @atalman this is required for every XLA release

**Pull request closed without merging**
