### PR TITLE
update release rc wheel name to RC6

### PR DESCRIPTION
**Pull request by ManfeiBai**

### CODE REVIEW

**Review by will-cromar — COMMENTED** [review]
Can you update all of these to`rc6` instead? https://github.com/pytorch/pytorch/tree/v2.2.0-rc6

**Comment by ManfeiBai** [comment]
> Can you update all of these to`rc6` instead? https://github.com/pytorch/pytorch/tree/v2.2.0-rc6

Thanks, @will-cromar, updated to rc6

**Review by will-cromar — APPROVED** [review]
Thanks

**Review by zpcore — APPROVED** [review]
LGTM!

**Pull request merged**
