### PR TITLE
Allow the alias check to work on CPU tensors as well.

### PR DESCRIPTION
**Pull request by dlibenzi**

### CODE REVIEW

**Comment by dlibenzi** [comment]
> Why do we want to check CPU tensors? Their save/load is handled correctly by Pytorch save/load right?

Yes, but usually one builds a model with CPU tensors, then `model.to()` it to XLA, and the `model.to()` destroys the view fabric, if any.
I'd like to use that API as a way to have folks check whether we are in a case like that (see this weekend "accuracy thread").

**Comment by dlibenzi** [comment]
> Oh I see. Hmmm although I'd leave a warning instead of throwing for CPU tensors.
> A message like "PyTorch doesn't preserve view-relationship across device" should work. The XLA tensors in save/load in kinda surprising behavior to users, but for across device it should be expected.

Does pytorch's `model.to()` do that?
I think if `b` has some storage-sharing with `a`, and both are parameters of the model, the `_apply()` API behind the `model.to(device)` should just be doing `new_a = a.to(device)` and `new_b = b.to(device)`, right?

**Comment by ailzhang** [comment]
@dlibenzi Yup, pytorch's `module.to()` doesn't preserve storage-sharing either.

**Comment by dlibenzi** [comment]
> @dlibenzi Yup, pytorch's `module.to()` doesn't preserve storage-sharing either.

My worry is if someone create a model, experiments with it on CPU, and then move to GPU/TPU.
IMHO pytorch should either handle, or complain in such case. Likely a rare case, but not impossible to happen.

**Pull request merged**
