### PR TITLE
Fix for xla_builder.Op.tuple return data type

### PR DESCRIPTION
**Pull request by awshaichen**
Issue: https://github.com/pytorch/xla/issues/3230

### CODE REVIEW

**Comment by JackCaoG** [comment]
Build error is not related and should be fixed after https://github.com/pytorch/xla/pull/3228.

This is an interesting, I dump the HLO for the bf16 tensor and saw
```
(Pdb) print(torch_xla._XLAC._get_xla_tensors_hlo([xla_results[1]]))

HloModule IrToHlo.10

%test_mixed_dtype_tuple.2 (p0.3: f32[2,3]) -> (f32[2,3], bf16[2,3]) {
  %p0.3 = f32[2,3]{1,0} parameter(0)
  %convert.4 = bf16[2,3]{1,0} convert(f32[2,3]{1,0} %p0.3)
  ROOT %tuple.5 = (f32[2,3]{1,0}, bf16[2,3]{1,0}) tuple(f32[2,3]{1,0} %p0.3, bf16[2,3]{1,0} %convert.4)
}

ENTRY %IrToHlo.10 (p0.1: f32[2,3]) -> (bf16[2,3]) {
  %p0.1 = f32[2,3]{1,0} parameter(0), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="<listcomp>@test_operations.py" source_line=1823}
  %call.6 = (f32[2,3]{1,0}, bf16[2,3]{1,0}) call(f32[2,3]{1,0} %p0.1), to_apply=%test_mixed_dtype_tuple.2, metadata={op_type="xla___op_test_mixed_dtype_tuple" op_name="xla___op_test_mixed_dtype_tuple" source_file="__call__@xla_op_registry.py" source_line=48}
  %get-tuple-element.7 = f32[2,3]{1,0} get-tuple-element((f32[2,3]{1,0}, bf16[2,3]{1,0}) %call.6), index=0, metadata={op_type="xla___op_test_mixed_dtype_tuple" op_name="xla___op_test_mixed_dtype_tuple" source_file="__call__@xla_op_registry.py" source_line=48}
  %get-tuple-element.8 = bf16[2,3]{1,0} get-tuple-element((f32[2,3]{1,0}, bf16[2,3]{1,0}) %call.6), index=1, metadata={op_type="xla___op_test_mixed_dtype_tuple" op_name="xla___op_test_mixed_dtype_tuple" source_file="__call__@xla_op_registry.py" source_line=48}
  ROOT %tuple.9 = (bf16[2,3]{1,0}) tuple(bf16[2,3]{1,0} %get-tuple-element.8)
}
```

The XLAOP is indeed bf16 and the question was coming from the `logical_element_type`. `CreateFrom` touches too many ops, I would rather fix this specified issue.. Looking into this a bit more

**Comment by JackCaoG** [comment]
Hmm, this is not something specified about `tuple`, if I do 
```
return a.cast(xb.Type.BF16)
```

I still see the same mismatch type
```
(Pdb) xla_results
[tensor([[ 0.0461,  0.4023, -1.0078],
        [ 0.2168, -0.6133,  0.5039]], device='xla:0')]
```

I think the issue is `xb.cast` doesn't correctly overwrite the `logical element type`.

**Comment by JackCaoG** [comment]
```
diff --git a/torch_xla/csrc/tensor.cpp b/torch_xla/csrc/tensor.cpp
index bdda6dea..ecee6316 100644
--- a/torch_xla/csrc/tensor.cpp
+++ b/torch_xla/csrc/tensor.cpp
@@ -1042,11 +1042,17 @@ ir::Value XLATensor::CreateTensorNode(xla::ComputationClient::DataPtr data,
   return ir::MakeNode<ir::ops::DeviceData>(std::move(data));
 }
 
-std::vector<XLATensor> XLATensor::MakeOutputTensors(ir::NodePtr node) const {
+std::vector<XLATensor> XLATensor::MakeOutputTensors(
+    ir::NodePtr node, bool inherit_logical_type) const {
   std::vector<XLATensor> tensors;
   tensors.reserve(node->num_outputs());
   for (size_t i = 0; i < node->num_outputs(); ++i) {
-    tensors.push_back(CreateFrom(ir::Value(node, i)));
+    if (inherit_logical_type) {
+      tensors.push_back(CreateFrom(ir::Value(node, i)));
+    } else {
+      tensors.push_back(CreateFrom(ir::Value(node, i),
+                                   /*logical_element_type=*/c10::nullopt));
+    }
   }
   return tensors;
 }
diff --git a/torch_xla/csrc/tensor.h b/torch_xla/csrc/tensor.h
index 923b5a98..a86e2b28 100644
--- a/torch_xla/csrc/tensor.h
+++ b/torch_xla/csrc/tensor.h
@@ -1335,7 +1335,8 @@ class XLATensor {
   //     a = a + b
   void TryLimitGraphSize();
 
-  std::vector<XLATensor> MakeOutputTensors(ir::NodePtr node) const;
+  std::vector<XLATensor> MakeOutputTensors(
+      ir::NodePtr node, bool inherit_logical_type=true) const;
 
   ir::Value GetIrValueForTensor(const at::Tensor& tensor,
                                 const Device& device) const;
diff --git a/torch_xla/csrc/tensor_methods.cpp b/torch_xla/csrc/tensor_methods.cpp
index 03ba912a..7a2a3b1d 100644
--- a/torch_xla/csrc/tensor_methods.cpp
+++ b/torch_xla/csrc/tensor_methods.cpp
@@ -431,7 +431,9 @@ std::vector<XLATensor> XLATensor::user_computation(
   }
   ir::NodePtr node = ir::MakeNode<ir::ops::UserComputation>(
       ir::OpKind::Get(opname), input_values, std::move(computation));
-  return inputs.front().MakeOutputTensors(node);
+  // Cast can be one of the user computation and we don't want to inherit the
+  // logical_element_type in this case
+  return inputs.front().MakeOutputTensors(node, /*inherit_logical_type=*/false);
 }
```
This should be the proper fix, could you rebase and apply this diff?

**Comment by awshaichen** [comment]
Thanks for getting back! Just applied your patch and verified that it fixes the tests.

**Comment by JackCaoG** [comment]
Hmm, seems like it is an existing issue
```
(Pdb) tensors[0]
tensor([False,  True,  True,  True])
(Pdb) tensors[0].to('xla:0') & tensors[0].to('xla:0').byte()
tensor([False,  True,  True,  True], device='xla:0')
(Pdb) tensors[0] & tensors[0].byte()
tensor([0, 1, 1, 1], dtype=torch.uint8)
```

I will open a github issue to track it. In the mean time feel free to remove the check (after manually verifying it fixed your issue)

**Review by JackCaoG — APPROVED** [review]
Thanks! I will merge the pr once all test passed

**Comment by awshaichen** [comment]
Thank you! I moved the new test to a separate class and verified that the change fixes it. Will close https://github.com/pytorch/xla/issues/3230 afterwards.

**Pull request merged**
