### PR TITLE
Add aten::abs operator

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Add aten::abs operator

Test Plan:
- Added a test in test/cpp/test_aten_xla_tensor.cpp

### CODE REVIEW

**Comment by vishwakftw** [comment]
I did notice that the code is slightly duplicated. Do you think a macro would be helpful in this case, which could potentially reduce code duplication and implement all the unary operations in one go?

**Comment by asuhan** [comment]
I'd rather live with the small amount of duplication / boilerplate. @dlibenzi what do you think?

**Comment by dlibenzi** [comment]
Let's chat tomorrow.
For now let's go with the current way.

**Comment by vishwakftw** [comment]
@dlibenzi @asuhan This is the idea I had, please feel free to comment on it:

In `torch_xla/csrc/aten_xla_type.cpp`, I would define this macro:
```c++

#define IMPLEMENT_UNARY_OP_XLATYPE(name) \
  at::Tensor AtenXlaType::name(const at::Tensor& self) const { \
    return bridge::AtenFromXlaTensor(XLATensor::name(bridge::GetXlaTensor(self))); \
  }
```

and then do this to add the unary operations:

```
IMPLEMENT_UNARY_OP_XLATYPE(abs)   // abs
IMPLEMENT_UNARY_OP_XLATYPE(cos)   // cos
IMPLEMENT_UNARY_OP_XLATYPE(exp)   // exp
IMPLEMENT_UNARY_OP_XLATYPE(log)   // log
IMPLEMENT_UNARY_OP_XLATYPE(neg)   // neg
IMPLEMENT_UNARY_OP_XLATYPE(sin)   // sin
IMPLEMENT_UNARY_OP_XLATYPE(sqrt)  // sqrt

IMPLEMENT_UNARY_OP_XLATYPE(relu)  // relu
IMPLEMENT_UNARY_OP_XLATYPE(t)     // t
```

A very similar thing would be done in `torch_xla/csrc/tensor.cpp` and `torch_xla/csrc/ops/ops.cpp`

**Comment by dlibenzi** [comment]
So I don't think saving 2 lines in include files buys us much.
The somehow repeated soup comes from the ops.cpp machinery, for which I posted https://github.com/pytorch/xla/pull/261

The other parts (include files and CPP simple redirection, I personally do not mind to see expanded code).

**Comment by vishwakftw** [comment]
Sure, thank you for your comment. I’ll work on sending PRs for the remaining ops once #261 is merged.

**Pull request merged**
