### PR TITLE
Add missing includes

### PR DESCRIPTION
**Pull request by peterbell10**
Currently the xla build fails when I try to remove this include from PyTorch's headers.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
seems like it failed the same way as the pytorch pr, looking at the error log it is from
```
external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/torch_xla/csrc/_objs/init_python_bindings/init_python_bindings.pic.d ... (remaining 725 arguments skipped)
In file included from external/tsl/tsl/platform/logging.h:26,
                 from external/tsl/tsl/platform/errors.h:30,
                 from ./torch_xla/csrc/runtime/util.h:19,
                 from ./torch_xla/csrc/device.h:11,
                 from ./torch_xla/csrc/aten_xla_bridge.h:11,
                 from torch_xla/csrc/init_python_bindings.cpp:29:
```

**Comment by peterbell10** [comment]
Looks like the GPU test failure is just a time-out.

**Comment by JackCaoG** [comment]
yea, I think this pr invalidate the cache so it build from scratch and timeout. There was another pr(https://github.com/pytorch/xla/pull/5441) run into the same issue. I just merged that one and let's see how it goes. If CI passed on head we are unblocked on this one as well.

**Comment by JackCaoG** [comment]
I think we can ignore the gpu failure. Can this pr be merged without your upstream pr? If so we can just rebase and merge this one. Then you can point your pytorch pr to a new xla commit and merge your pytorch pr.

**Comment by peterbell10** [comment]
Yeah no need to coordinate this with the pytorch PR since it's so trivial. Rebased and hoping CI completes this time.

**Comment by JackCaoG** [comment]
sounds good! I will merge this once CI is green

**Comment by JackCaoG** [comment]
not sure what's happening with CI, I will try to build it on my own and if everything passes I will merge this one.

**Comment by JackCaoG** [comment]
totally forgot about this one, let me patch it locally now.

**Comment by JackCaoG** [comment]
builds fine on my end, merging.

**Pull request merged**
