### PR TITLE
Add version selection snippet for r1.8

### PR DESCRIPTION
**Pull request by zcain117**

### CODE REVIEW

**Comment by zcain117** [comment]
@jysohn23 any tips for testing this?

**Comment by jysohn23** [comment]
AFK now, but what I previously did was set the env var on local VM and
verify that the TPU runtime was switched and then again on Colab Kaggle
once wheels are released.

**Comment by zcain117** [comment]
Tested as per https://b.corp.google.com/issues/180416761#comment4
I'll update our internal documentation too on the process of testing this kind of PR

**Review by jysohn23 — APPROVED** [review]
Thanks!

**Pull request merged**
