### PR TITLE
Update _(log_)softmax_backward parameters

### PR DESCRIPTION
**Pull request by soulitzer**
Need to update XLA for https://github.com/pytorch/pytorch/pull/65242
See: https://app.circleci.com/pipelines/github/pytorch/pytorch/383084/workflows/bfba5a8c-19ca-4c58-8228-90227cd783bf/jobs/16122854

cc @JackCaoG

### CODE REVIEW

**Comment by JackCaoG** [comment]
@soulitzer Can you add a torch_pin like in https://github.com/pytorch/xla/pull/3003/files? This will help CI to pick the right upstream branch to run the test. Pin should just be your pytorch pr number.

**Comment by soulitzer** [comment]
oh nice, looks like the tests are passing now!

**Comment by soulitzer** [comment]
@JackCaoG The upstream PyTorch PR just landed, so this should be ready to land!

**Comment by soulitzer** [comment]
The upstream PyTorch has just been reverted unfortunately https://github.com/pytorch/pytorch/pull/65242#issuecomment-931563226. So we may have to do the same here.

**Pull request merged**
