### PR TITLE
[Pallas] Remove torch.empty in tracing

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
Previously we rely on torch.empty to create some empty tensors as the outputs from the Pallas and then make Pallas as in-place ops. However, it turns out that torch.empty will actually allocate memory and therefore it's expansive to use. In this change, I switched to simply pass the shapes and dtypes to construct the graph node.

Test Plan:
PJRT_DEVICE=TPU python test/test_pallas.py

Performance benchmarks can be found: http://shortn/_wdmom7I6q7

### CODE REVIEW

**Comment by alanwaketan** [comment]
This PR is ready for review.

**Comment by JackCaoG** [comment]
I will take a look

**Review by JackCaoG — APPROVED** [review]

**Comment by JackCaoG** [comment]
Do we need this in 2.3 release? I don't consider this as the critical fix, wdyt?

**Comment by alanwaketan** [comment]
> Do we need this in 2.3 release? I don't consider this as the critical fix, wdyt?

I think it is, but I will hold it until I finished some e2e modeling tests. Thanks for the review.

**Pull request merged**
