### PR TITLE
All gather layout

### PR DESCRIPTION
**Pull request by JackCaoG**
Ping the layout for `all-gather`, this should solve https://github.com/pytorch/xla/issues/3423. I will let gpu test to verify that this does not break anything and test the pod with new wheel.

FYI @ronghanghu

### CODE REVIEW

**Comment by ronghanghu** [comment]
Awesome, I'll try it out. Thanks for the fix!

**Review by hjm-aws — APPROVED** [review]

**Comment by JackCaoG** [comment]
ehh.. test failed at gpu, I will try to take a look today

**Comment by JackCaoG** [comment]
test actually passed on TPU front, I will try to repro it on gpu vm and debug a bit more

**Comment by JackCaoG** [comment]
Chatted with Blake from the XLA team, TPU emitter actually does not supporting pinnging the layout for both `all_gather` and `reduce_scatter` then use them side by side. We should only pin the layout for `all_reduce` and leave everything else not pinned. I will start a separate pr to remove the layout pining for `reduce_scatter`.

**Pull request closed without merging**
