### PR TITLE
clear pending ir should also clear the cc op tokens

### PR DESCRIPTION
**Pull request by JackCaoG**
TODO:
1. also clear the pending ir on the device random seed
2. add test

given  he urgency of the bug, I am inclined to merge this today.

### CODE REVIEW

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Review by wonjoolee95 — APPROVED** [review]

**Comment by JackCaoG** [comment]
I will wait for the TPU CI to pass then merge it.

**Review by miladm — APPROVED** [review]
LGTM

**Comment by miladm** [comment]
@JackCaoG 
The PR said you'd like to add a test - great idea; I don't seem to find it on this PR.

**Comment by JackCaoG** [comment]
@miladm I will have a follow up pr, don't want to block this one. I verified locally that with this change dynamo gives the small graph.

**Pull request merged**
