### PR TITLE
Update XLA pin to 2023/08/08

### PR DESCRIPTION
**Pull request by JackCaoG**
I had to update the gcc-10 locally to make it build(thanks @lsy323 for the help), the command I used is
```
 1225  [2023-08-09 16:55:27] echo 'deb http://deb.debian.org/debian bullseye main' >> /etc/apt/sources.list
 1226  [2023-08-09 16:55:35] sudo apt update
 1227  [2023-08-09 16:55:52] sudo apt install gcc-10
 1228  [2023-08-09 16:58:28] gcc --version
```
assuming you are using the dev container, after this you should see
```
root@dada83f25caf:/src/pytorch/xla# gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I was able to verify that on v3-8, resnet50 spmd speed does not regress
```
Epoch 1 train begin 18:08:17
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=33.94 GlobalRate=33.94 Time=18:09:18
| Training Device=xla:0/0 Epoch=1 Step=20 Loss=5.32911 Rate=3106.94 GlobalRate=629.86 Time=18:09:26
| Training Device=xla:0/0 Epoch=1 Step=40 Loss=0.62358 Rate=3994.76 GlobalRate=1087.50 Time=18:09:34
| Training Device=xla:0/0 Epoch=1 Step=60 Loss=0.01664 Rate=4588.41 GlobalRate=1462.34 Time=18:09:43
| Training Device=xla:0/0 Epoch=1 Step=80 Loss=0.00676 Rate=4817.95 GlobalRate=1770.98 Time=18:09:51
| Training Device=xla:0/0 Epoch=1 Step=100 Loss=0.00539 Rate=4630.87 GlobalRate=2012.93 Time=18:10:00
| Training Device=xla:0/0 Epoch=1 Step=120 Loss=0.00484 Rate=4783.34 GlobalRate=2229.60 Time=18:10:08
```

### CODE REVIEW

**Review by jonb377 — APPROVED** [review]
Thanks!

**Comment by JackCaoG** [comment]
failure is on the C++ test build, will try to fix that tmr.

**Comment by JackCaoG** [comment]
TPU CI is failing, I think the gcc needs to be updated there as well..

**Comment by JackCaoG** [comment]
waiting for the TPU CI and then open a pytorch pr pointing to  this pr.

**Comment by JackCaoG** [comment]
opened https://github.com/pytorch/pytorch/pull/107262. we might have to update the gcc for the upstream as well.

**Pull request merged**
