### PR TITLE
[PJRT] Create function to spawn threads instead of processes.

### PR DESCRIPTION
**Pull request by will-cromar**
This unblocks some of @jonb377's experiments that don't support multiprocessing yet.

### CODE REVIEW

**Review by jonb377 — APPROVED** [review]
LGTM, thanks Will!

**Review by JackCaoG — COMMENTED** [review]
Do we expect to keep this `spawn thread` long term? If not I would say add comment to make it very clear that this is an internal temporary helper. This will prevent us from forgetting deleting this method and some user takes dependency on this method.

**Comment by will-cromar** [comment]
It's not clear whether we need this long-term yet or if we can easily make @jonb377's workload multiprocess-friendly. Since this is under `experimental`, users should assume that we may not merge this into the stable API.

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Pull request merged**
