### PR TITLE
Optimize protobuf TF patch

### PR DESCRIPTION
**Pull request by lsy323**
This diff is based on https://github.com/pytorch/xla/pull/4594

The XRT performance regression caused by protobuf version upgrade in TF cannot be fixed in the near future. Reducing the size of the tf patch to make TF pin update work to be easier.

The patch for the following files in TF repo is removed, the change was related to Windows Build. The size of patch is reduced from ~2000 to ~500 lines.

.bazelrc
tensorflow/opensource_only.files
tensorflow/python/grappler/BUILD
tensorflow/python/saved_model/BUILD
tensorflow/tools/toolchains/win/BUILD
tensorflow/tools/toolchains/win/tf_win_01232023/BUILD
tensorflow/tools/toolchains/win/tf_win_01232023/BUILD
tensorflow/tools/toolchains/win/tf_win_01232023/armeabi_cc_toolchain_config.bzl
tensorflow/tools/toolchains/win/tf_win_01232023/builtin_include_directory_paths_msvc
tensorflow/tools/toolchains/win/tf_win_01232023/toolchain_image_info
tensorflow/tools/toolchains/win/tf_win_01232023/windows_cc_toolchain_config.bzl

### CODE REVIEW

**Comment by vanbasten23** [comment]
I wonder how you reduced the patch size. Is it by only retaining the part related to protobuf version update?

**Comment by lsy323** [comment]
> 

The original patch reverts the TF commits https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38 and https://github.com/tensorflow/tensorflow/commit/764ec7606a3925bf950772f90d9e196380cbbeb5. Both commits are related to protobuf upgrade. Only the changes related to windows build are removed from the patch.

**Review by vanbasten23 — APPROVED** [review]

**Comment by JackCaoG** [comment]
@lsy323 Did you verify that this change will keep the resnet speed the same?

**Review by JackCaoG — APPROVED** [review]
approve per our discussion.

**Comment by lsy323** [comment]
> @lsy323 Did you verify that this change will keep the resnet speed the same?

Verified the resnet speed remains the same after this optimized patch:
Before TF pin update with the protobuf update:
```
| Training Device=xla:1/0 Epoch=1 Step=2300 Loss=0.00135 Rate=1205.59 GlobalRate=756.14 Time=03:55:12
| Training Device=xla:0/2 Epoch=1 Step=2300 Loss=0.00135 Rate=1205.04 GlobalRate=769.98 Time=03:55:12
| Training Device=xla:0/3 Epoch=1 Step=2300 Loss=0.00135 Rate=1204.85 GlobalRate=757.61 Time=03:55:12
| Training Device=xla:0/1 Epoch=1 Step=2300 Loss=0.00135 Rate=1204.44 GlobalRate=758.80 Time=03:55:12
| Training Device=xla:1/0 Epoch=1 Step=2320 Loss=0.00135 Rate=1208.34 GlobalRate=758.59 Time=03:55:14
| Training Device=xla:0/1 Epoch=1 Step=2320 Loss=0.00135 Rate=1209.03 GlobalRate=761.26 Time=03:55:14
| Training Device=xla:0/3 Epoch=1 Step=2320 Loss=0.00135 Rate=1208.23 GlobalRate=760.06 Time=03:55:14
| Training Device=xla:0/2 Epoch=1 Step=2320 Loss=0.00135 Rate=1208.02 GlobalRate=772.40 Time=03:55:14
| Training Device=xla:0/2 Epoch=1 Step=2340 Loss=0.00135 Rate=1235.01 GlobalRate=774.94 Time=03:55:16
| Training Device=xla:0/3 Epoch=1 Step=2340 Loss=0.00135 Rate=1234.87 GlobalRate=762.62 Time=03:55:16
| Training Device=xla:1/0 Epoch=1 Step=2340 Loss=0.00135 Rate=1233.36 GlobalRate=761.15 Time=03:55:16
| Training Device=xla:0/1 Epoch=1 Step=2340 Loss=0.00135 Rate=1234.19 GlobalRate=763.81 Time=03:55:16
```
After this patch:
```
| Training Device=xla:0/3 Epoch=1 Step=2280 Loss=0.00135 Rate=1193.55 GlobalRate=779.25 Time=19:09:20
| Training Device=xla:1/0 Epoch=1 Step=2300 Loss=0.00135 Rate=1201.00 GlobalRate=778.90 Time=19:09:22
| Training Device=xla:0/1 Epoch=1 Step=2300 Loss=0.00135 Rate=1200.13 GlobalRate=783.37 Time=19:09:22
| Training Device=xla:0/3 Epoch=1 Step=2300 Loss=0.00135 Rate=1200.40 GlobalRate=781.65 Time=19:09:22
| Training Device=xla:0/2 Epoch=1 Step=2300 Loss=0.00135 Rate=1200.73 GlobalRate=783.29 Time=19:09:22
| Training Device=xla:1/0 Epoch=1 Step=2320 Loss=0.00135 Rate=1204.57 GlobalRate=781.28 Time=19:09:24
| Training Device=xla:0/3 Epoch=1 Step=2320 Loss=0.00135 Rate=1204.57 GlobalRate=784.03 Time=19:09:24
| Training Device=xla:0/2 Epoch=1 Step=2320 Loss=0.00135 Rate=1204.54 GlobalRate=785.66 Time=19:09:24
| Training Device=xla:0/1 Epoch=1 Step=2320 Loss=0.00135 Rate=1203.93 GlobalRate=785.74 Time=19:09:24
| Training Device=xla:1/0 Epoch=1 Step=2340 Loss=0.00135 Rate=1223.73 GlobalRate=783.75 Time=19:09:26
| Training Device=xla:0/3 Epoch=1 Step=2340 Loss=0.00135 Rate=1223.29 GlobalRate=786.49 Time=19:09:26
| Training Device=xla:0/1 Epoch=1 Step=2340 Loss=0.00135 Rate=1223.07 GlobalRate=788.19 Time=19:09:26
| Training Device=xla:0/2 Epoch=1 Step=2340 Loss=0.00135 Rate=1223.04 GlobalRate=788.12 Time=19:09:26
```

**Pull request merged**
