### PR TITLE
Update TF and using new xla::QRDecomposition API

### PR DESCRIPTION
**Pull request by JackCaoG**
This is to fix the API change introduced by tf in https://github.com/tensorflow/tensorflow/commit/89b614f023b82b90adcfc928046e1455df349b98

### CODE REVIEW

**Review by jysohn23 — COMMENTED** [review]
Thanks @JackCaoG, could you PTAL CI failures?
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AtenXlaTensorTest.TestLogDet
```

**Comment by JackCaoG** [comment]
> TestLogDet

Looking, this mightbe another api behavior changed.. I don't like when tf does that silently...

**Comment by jysohn23** [comment]
> Looking, this mightbe another api behavior changed.. I don't like when tf does that silently...

+1 seems to happen more often that I'd like similar to like the recent `Permute` changes :|

**Comment by JackCaoG** [comment]
Logdet had an implementation change in the pr mentioned above and it break our test. I am talking to pr author to see if we can get this fix ASAP

**Comment by JackCaoG** [comment]
Synced tf up to https://github.com/tensorflow/tensorflow/commit/00d31f1d50c3ef475d8301f70ffbf0647038f53f. Verified that test is passing locally.

**Review by zcain117 — APPROVED** [review]
LGTM assuming tests pass

**Review by jysohn23 — APPROVED** [review]

**Pull request merged**
