### PR TITLE
[Functionalization] Remove view in view_symint

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This pull request removes views in tensor_method::view_symint.

Test Plan:
XLA_DISABLE_FUNCTIONALIZATION=1 PJRT_DEVICE=TPU python ../test/test_view_ops.py -v -k TestViewOpsXLA.test_view_view PJRT_DEVICE=TPU python ../test/test_view_ops.py -v -k TestViewOpsXLA.test_view_view

### CODE REVIEW

**Comment by alanwaketan** [comment]
@vanbasten23 Any insights about the ds failures?

**Review by alanwaketan — COMMENTED** [review]
It LGTM but I cannot approve. haha

**Comment by JackCaoG** [comment]
I think you want to rebase

**Comment by vanbasten23** [comment]
> I think you want to rebase

already done after the amp pr merged.

**Review by JackCaoG — APPROVED** [review]

**Pull request merged**
