### PR TITLE
enable mkldnn

### PR DESCRIPTION
**Pull request by ailzhang**

### CODE REVIEW

**Comment by dlibenzi** [comment]
We can probably enable here too?

https://github.com/pytorch/xla/blob/6ce9affadea09278524bea174c54e4703135feab/scripts/build_torch_wheels.sh#L82

No @jysohn23 ?

**Comment by jysohn23** [comment]
> We can probably enable here too?
> 
> https://github.com/pytorch/xla/blob/6ce9affadea09278524bea174c54e4703135feab/scripts/build_torch_wheels.sh#L82
> 
> No @jysohn23 ?

I think we could? But don't we need to install that package first?

**Comment by dlibenzi** [comment]
> > We can probably enable here too?
> > https://github.com/pytorch/xla/blob/6ce9affadea09278524bea174c54e4703135feab/scripts/build_torch_wheels.sh#L82
> > 
> > No @jysohn23 ?
> 
> I think we could? But don't we need to install that package first?

We used to build with it ... no?
IIRC we used to install it...

**Comment by ailzhang** [comment]
@jysohn23 mkldnn comes in pytorch submodule `ideep` so we don't need install new deps.

**Comment by jysohn23** [comment]
> @jysohn23 mkldnn comes in pytorch submodule `ideep` so we don't need install new deps.

Ah I see! Thanks for the info. Will keep an eye on our nightly builds then.

**Pull request merged**
