### PR TITLE
Make r2.3 to be compatible with PyPI

### PR DESCRIPTION
**Pull request by lsy323**
This applies https://github.com/pytorch/xla/pull/6145/ to master branch.

### CODE REVIEW

**Comment by lsy323** [comment]
Triggered GHA TPU CI at https://github.com/pytorch/xla/actions/runs/8457783279

**Comment by lsy323** [comment]
Have another try at https://github.com/pytorch/xla/actions/runs/8462299657

**Review by will-cromar — APPROVED** [review]
Thanks!

**Comment by lsy323** [comment]
This PR makes the torch_xla setup script compatible with PyPI. The next release may not need this change, because of the work of making HEAD PyPI compatible is ongoing.

**Pull request merged**
