### PR TITLE
Pull latest changes for TensorFlow

### PR DESCRIPTION
**Pull request by wonjoolee95**
Pulling in latest changes from TensorFlow and fixing resulting build issues.

Pulled latest TensorFlow:
```
# Go into third_party/tensorflow (from pytorch/xla)
cd third_party/tensorflow 
# Checkout master and pull latest
git checkout master
git pull
# Add this commit from PTXLA
cd ../..
git add third_party/tensorflow
```

Changes include:
1. Replace `xla::` types such as `xla::int64_t` and `xla::string` with `std` types (this accounts for 99% of this PR)
    - Reason for change: `xla` types were removed from TensorFlow
2. Replace ArgMin/MaxTwoPass with ArgMin/Max (`torch_xla/csrc/reduction.cpp`)
    - Reason for change: ArgMin/MaxTwoPass was from XLA and replaced with regular ArgMin/Max
    - Verified with existing ArgMin/Max unit tests in PTXLA still passing after this change. 
3. Replace removed function `RoundUpToNearest` (`third_party/xla_client/xrt_computation_client.cc`)
     - Reason for change: Function `RoundUpToNearest` was removed from XLA file we import. Replaced this function call to inline implementation.
     - Before change: `num_bytes = RoundUpToNearest(num_bytes, alignment);`
     - After change: `num_bytes = tensorflow::MathUtil::CeilOfRatio(num_bytes, alignment) * alignment;`
   
Confirmed that with this change, the build and tests succeeds locally in cloudtop and TPUVM.

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Building on cloudtop finally successful with these changes 😄

**Comment by JackCaoG** [comment]
@wonjoolee95 Nice! Can we also test on TPUVM build?

**Comment by wonjoolee95** [comment]
> @wonjoolee95 Nice! Can we also test on TPUVM build?

Sure thing! Working on it.

**Comment by wonjoolee95** [comment]
When building on TPUVM, saw some build failures specifically in `third_party/xla_client` related to more of the `xla` type issues we've seen before.

**Comment by wonjoolee95** [comment]
With the latest commit, can confirm that building on TPUVM succeeds. Steps I took:
```
1. SSH to TPUVM 
gcloud alpha compute tpus tpu-vm ssh wonjoo-tpuvm 
2. Pull TensorFlow latest TensorFlow in third_party
3. Check this PR out locally
gh pr checkout 3298
4. Build (PT and) PTXLA 
sudo TPUVM_MODE=1 BUILD_CPP_TESTS=0 python setup.py install

Build succeeds!
```

**Comment by wonjoolee95** [comment]
Forced pushed to fix merge conflict with latest commit.

**Comment by wonjoolee95** [comment]
Now waiting on a PR that builds our own PTXLA docker image, which should hopefully make our CircleCI tests pass -- https://github.com/pytorch/xla/pull/3282.

**Comment by JackCaoG** [comment]
It is a huge change and will likely conflicting with many other prs. I will try to take a look tmr. AFAIK three changes are `int64_t`, `std::string` and `argmax/min`, is there anything else I should pay attention to?

**Comment by wonjoolee95** [comment]
> It is a huge change and will likely conflicting with many other prs. I will try to take a look tmr. AFAIK three changes are `int64_t`, `std::string` and `argmax/min`, is there anything else I should pay attention to?

That's pretty much all. I've updated the PR summary on the top to have some more detailed info.

**Review by yeounoh — APPROVED** [review]
LGTM, and thank you @wonjoolee95 for the summary :)

**Comment by JackCaoG** [comment]
I will trust yeounoh on this one. @wonjoolee95 I prefer to delay the merge to Monday morning(so we can revert it right away if something is wrong). Do we have any urgent use case to merge this pr today?

**Comment by wonjoolee95** [comment]
I'm definitely okay with waiting until Monday. 

I believe @miladm and @yeounoh  wanted to test something with Blake's fix that's included with the new TF. Does Monday work for you?

**Review by miladm — APPROVED** [review]
@wonjoolee95 thanks for running through such a heavy lifting task. I spent a good chunk of time reviewing the code. LGTM.

Feel free to merge after your summary of the code to help us make sure what we took away from the code is consistent with yours.

**Comment by wonjoolee95** [comment]
> @wonjoolee95 thanks for running through such a heavy lifting task. I spent a good chunk of time reviewing the code. LGTM.
> 
> Feel free to merge after your summary of the code to help us make sure what we took away from the code is consistent with yours.

Thanks for reviewing! I've added the summary on top of the PR (the very first edited comment).

**Comment by miladm** [comment]
Monday works for me.

**Pull request merged**
