### PR TITLE
Stable graph detection and Dynamic Device Switching 

### PR DESCRIPTION
**Pull request by cjolivier01**
@JackCaoG @ailzhang 

Contains (extracted from plugin): 

* **XlaComputationProxy** 
This is not the original xla_computation_proxy.cc/h from the pytorch/xla project.  I was not aware this file used to exist in this project until much later 😊  
Implements ComputationClient->xla::ServiceInterface mapping in a way compatible with the current lazy tensor implementation. 
* **LazySentinel** (lazy_sentinel.cc) 
  * Determines graph stability. Modes are: 
  * Seek Stable Graph 
  * Trusted Model (all train steps on device)
  * Assume stable on provided step # 
  * Allows for on-the-fly graph rewrite (I.e. prune outputs) 
* **ProxyComputationClient** 
  * Hides device-switching behind a single ComputationClient interface 
  * Derives from **XrtComputationClient**, installable via factory set via pybind _ptproxy_initialize().  "“local device” is currently the Xrt device, which should be changed as noted below. 
  * Ideally, it doesn’t derive from XrtComputationClient, but that is difficult to maintain out-of-stream for a number of reasons. 
In order to run in the general sense, I will need to do a few changes to make XrtComputationClient the default proxy type rather than **XlaComputationClient** 

 

Outstanding items: 
* Port my dds tests to this generalized implementation
* Normalize commenting style (trying to switch to the “///” convention) 
* Detach XrtComputationProxy construction from unrepeatable global initialization so that it may be used as a target device 
* This allows both “base” and “proxy” devices to be any sort of device that implements  the ComputationClient interface 
* This hasn’t been done yet in order to maintain minimal changes in ptxla code base for maintainability of out-of-repo code 
* Parallelism in a few places 
* Maybe some replication edge cases with data movement issues? 
* Merge ReleaseXrtData with ReleaseDataByHandle as a generalization 
* Remove all “verbose” flags and stdout 
* Asserts -> TF_xxx asserts 
* Remove/merge utility routines which exist due to the plugin’s isolation 
* Disconnect “proxy name” knowledge a few places, such as factory and ComputationClientManager 
* Remove topology function artifact 

Note: cmake file is temporary and just so I can build in the interim.

### CODE REVIEW

**Comment by cjolivier01** [comment]
I realize this is kind of scary big, although the intersection with the codebase is small (at least comparatively speaking).  
Can keep as a plugin (even if not upstreamed) if ptxla plugin interface can be added (also small) as outlined here: https://github.com/pytorch/xla/pull/2814

**Comment by JackCaoG** [comment]
Hey Chris, thanks for sharing this! I am a bit busy with the upcoming TPUVM launch, will try to spend more time on this pr when that thing is over 😄

**Comment by cjolivier01** [comment]
Thanks, Jack!  Obviosly it can't go in as it is, but I'd love to get your feedback on the general approach (which I can go over any time here or in a call) before I do all the stuff in the TODO list.  Maybe it makes more sense as an independent plugin if there's at least a way to plug in (like the PR referenced), which is how I have it now -- in a different shared object/pip (not necessarily in pytorch repo).  But I am ok either way.  For general use, at least in the short term, the XrtComputationClient would need to be disconnected a little from its init path since it can't have two created with each pointing to a different device as it is.  It doesnt seem like this would be too difficult, but it wouldn't be very generalized/maintainable out-of-repo, so I haven't done it :)

**Comment by cjolivier01** [comment]
closing because will need to refactor significantly since lazy tensors are being upstreamed

**Pull request closed without merging**
