### PR TITLE
Disable python operations tests that fail on TPU

### PR DESCRIPTION
**Pull request by zcain117**
Also remove the `_xla_float64` suffix from some tests so that they actually get disabled

### CODE REVIEW

**Comment by dlibenzi** [comment]
Can we fix the precision instead?

**Comment by zcain117** [comment]
> Can we fix the precision instead?

For 9 of the 12, my understanding is that @mruberry would need to change things on the pytorch side. For 3 of the 12, I can try adjusting precision but the values seem kind of far off, e.g.

```
======================================================================
FAIL: test_triangular_solve_batched_many_batches_xla_float64 (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch/test/common_device_type.py", line 197, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/pytorch/test/common_utils.py", line 339, in wrapper
    fn(*args, **kwargs)
  File "/pytorch/test/common_device_type.py", line 428, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/pytorch/test/common_device_type.py", line 428, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/pytorch/xla/test/../../test/test_torch.py", line 8965, in test_triangular_solve_batched_many_batches
    self.assertEqual(torch.matmul(A, x), b.expand(A.shape[:-2] + (5, 1)))
  File "/pytorch/test/common_device_type.py", line 335, in assertEqual
    return DeviceTypeTestBase.assertEqual(self, x, y, prec, message, allow_inf)
  File "/pytorch/test/common_utils.py", line 784, in assertEqual
    assertTensorsEqual(x, y)
  File "/pytorch/test/common_utils.py", line 754, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.0183, device='xla:1', dtype=torch.float64) not less than or equal to 0.001 : 
======================================================================
FAIL: test_cholesky_solve_batched_many_batches_xla_float64 (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch/test/common_device_type.py", line 197, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/pytorch/test/common_utils.py", line 339, in wrapper
    fn(*args, **kwargs)
  File "/pytorch/test/common_device_type.py", line 428, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/pytorch/test/common_device_type.py", line 428, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/pytorch/xla/test/../../test/test_torch.py", line 7093, in test_cholesky_solve_batched_many_batches
    self.assertEqual(torch.matmul(A, x), b.expand(A.shape[:-2] + (5, 10)))
  File "/pytorch/test/common_device_type.py", line 335, in assertEqual
    return DeviceTypeTestBase.assertEqual(self, x, y, prec, message, allow_inf)
  File "/pytorch/test/common_utils.py", line 784, in assertEqual
    assertTensorsEqual(x, y)
  File "/pytorch/test/common_utils.py", line 754, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(0.3627, device='xla:1', dtype=torch.float64) not less than or equal to 0.001 : 
```

**Comment by dlibenzi** [comment]
If a test is failing for 1.0183 and 0.3627, then it seems there might be something wrong or the test does something which mathematically amplify rounding errors.

**Comment by zcain117** [comment]
> If a test is failing for 1.0183 and 0.3627, then it seems there might be something wrong or the test does something which mathematically amplify rounding errors.

Yes I agree but these seem like low-priority ops compared to e.g. setting up metrics regression tests. IMO we will have to prioritize and work through the list of disabled tests.

I tried at another precision and found similar errors, so I updated the comment explaining why 3 of the tests are disabled. The output is wrong, it doesn't seem to be a test precision issue

**Comment by mruberry** [comment]
fyi the tests you're swapping in are different from the tests you attempted to swap out, is that intended?

**Comment by zcain117** [comment]
> fyi the tests you're swapping in are different from the tests you attempted to swap out, is that intended?

Just double checked and this is the correct list based on the latest run of these tests on TPU

**Pull request merged**
