### PR TITLE
[test] Update tf_cc_test from OpenXLA

### PR DESCRIPTION
**Pull request by ManfeiBai**

### CODE REVIEW

**Comment by ManfeiBai** [comment]
this build will fail because we miss some func definition from tf when we using cc_test

**Review by stgpetrovic — COMMENTED** [review]
Hm, where do we get the //tensorflow include here? We have only //bazel:rules_def.bzl, but I don't see a tensorflow dir in this patch.

Copying the missing functions seems like the way to go tho.

**Comment by ManfeiBai** [comment]
> Hm, where do we get the //tensorflow include here? We have only //bazel:rules_def.bzl, but I don't see a tensorflow dir in this patch.
> 
> Copying the missing functions seems like the way to go tho.

Thanks for pointing that out, @stgpetrovic, we could use tsl and absl too, so I change to use `cc_test` from tsl

**Comment by ManfeiBai** [comment]
will close this PR and track in https://github.com/pytorch/xla/pull/5165/

**Pull request closed without merging**
