### PR TITLE
Update GPU README to use torch 2.1.2 because pip required it and PJRT_DEVICE as GPU

### PR DESCRIPTION
**Pull request by changm**
Updating README based on what PIP said was required.

Also required PJRT_DEVICE=GPU because PJRT_DEVICE=CUDA was not recognized.

### CODE REVIEW

**Comment by JackCaoG** [comment]
this has changed since 2.1, in 2.2 we actually want `PJRT_DEVICE=GPU`. If you check our doc for 2.1 it still says `GPU` https://github.com/pytorch/xla/blob/r2.1/docs/gpu.md#run-a-simple-model

**Comment by changm** [comment]
Thanks for the fast review! Do you know what the proper way to run this is then? Following the instructions doesn't work with `PJRT_DEVICE=CUDA` and making `torch=2.2` doesn't exist. 

I was able to get it to run with `torch=2.1.2` and `PJRT_DEVICE=GPU`.

**Comment by JackCaoG** [comment]
2.2 will be release in Jan 2024, the doc in the master branch reflects the usage of the nightly. For 2.1 you should keep using `PJRT_DEVICE=GPU`. If you want to try nightly you can follow https://github.com/pytorch/xla?tab=readme-ov-file#python-packages, if you want to build nighty youself, you can follow https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md

**Comment by changm** [comment]
Great thanks for the instructions.  I'll close this PR and try the nightly builds.

**Pull request closed without merging**
