### PR TITLE
Deprecate XLA_USE_BF16

### PR DESCRIPTION
**Pull request by JackCaoG**
User should downcast their model directly or use amp.

### CODE REVIEW

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by will-cromar** [comment]
Thanks! I'm glad to see this being removed.

**Comment by miladm** [comment]
Can we also remove this line from the repo @JackCaoG?
https://github.com/pytorch/xla/blob/master/configuration.yaml#L125

**Comment by JackCaoG** [comment]
sure

**Pull request merged**
