### PR TITLE
cherry pick defer init

### PR DESCRIPTION
**Pull request by JackCaoG**

### CODE REVIEW

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by JackCaoG** [comment]
kicked off a new build, hopefully it will pass. Also building on my TPUVM as a backup.

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by alanwaketan** [comment]
This PR is only used to trigger an experimental build and is not supposed to be merged.

**Pull request closed without merging**
