### PR TITLE
add torch_xla 2.0 with python 3.10 wheel

### PR DESCRIPTION
**Pull request by ManfeiBai**
cc @zpcore

### CODE REVIEW

**Comment by JackCaoG** [comment]
why do we need py3.10 whl for 2.0?

**Comment by ManfeiBai** [comment]
> why do we need py3.10 whl for 2.0?

torchbench might need this wheel cc @zpcore

**Comment by zpcore** [comment]
Thanks @ManfeiBai for building the 2.0. Currently I am working on reproducing the torchbench result from 6 months ago. python 3.10 version torch_xla 2.0 will help in reproducing the results since all the other benchmark releated packages I use are built for python 3.10.

**Comment by zpcore** [comment]
I already found the intended version in docker image. Guess I don't need it anymore. Thanks @ManfeiBai for building the wheel.

**Pull request closed without merging**
