### PR TITLE
[benchmarks] Fix execution with AMP precision.

### PR DESCRIPTION
**Pull request by ysiraichi**
This PR moves AMP to be only activated in the forward execution.

cc @miladm

### CODE REVIEW

**Comment by zpcore** [comment]
Hi @ysiraichi , did you see any issue recently that GPU xla backend also failed to run? I am not sure if this is related to the data format changes.

**Comment by ysiraichi** [comment]
Not really...

**Comment by vanbasten23** [comment]
Overall, LGTM.
One quick question, why do we want to moves AMP to be only activated in the forward execution? If we dont do it, what error do you see?

**Comment by ysiraichi** [comment]
It's not exactly an error. But [this is how AMP is supposed to be used](https://pytorch.org/docs/stable/amp.html#torch.autocast). This is also how PyTorch's benchmarking script uses it (if we want to have comparable numbers).

**Review by golechwierowicz — APPROVED** [review]

**Pull request merged**
