### PR TITLE
[Dynamo|TPU] Skip`DynamoTrainingBasicTest.test_resnet18` on TPU

### PR DESCRIPTION
**Pull request by ManfeiBai**
Before bring `test_dynamo.py` to TPU CI in https://github.com/pytorch/xla/pull/5369, set skip `DynamoTrainingBasicTest.test_resnet18` on TPU

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Curious on which hardware this is failing -- I assume this is failing on TPU due to precision? Or is it failing on GPU as well?

**Comment by ManfeiBai** [comment]
> Curious on which hardware this is failing -- I assume this is failing on TPU due to precision? Or is it failing on GPU as well?

didn't test on GPU, this failure appear on TPU, maybe we should make a patch for TPU only to fix this?

**Comment by wonjoolee95** [comment]
The CI is green on head, which means it should succeed on CPU and GPU.

We should be able to easily skip it only on TPU with a `@skipif`, something like https://github.com/pytorch/xla/blob/master/test/test_operations.py#L59.

**Comment by ManfeiBai** [comment]
> The CI is green on head, which means it should succeed on CPU and GPU.
> 
> We should be able to easily skip it only on TPU with a `@skipif`, something like https://github.com/pytorch/xla/blob/master/test/test_operations.py#L59.

thanks, @wonjoolee95, cool, really good point, has applied `@skipOnTpu`

**Review by wonjoolee95 — APPROVED** [review]

**Pull request merged**
