### PR TITLE
Add example for a decoder only model

### PR DESCRIPTION
**Pull request by JackCaoG**
This will be used to show how to do 2d sharding since I can't really do 2d sharding on a resnet.

### CODE REVIEW

**Comment by alanwaketan** [comment]
This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.

**Review by alanwaketan — APPROVED** [review]

**Comment by JackCaoG** [comment]
> This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.

I am thinking about that. right now I am thinkign something like
```
examples/
    data_parallel/
        xla_ddp
        ddp
        spmd_ddp
    2d sharding/
        spmd_2d_harding
	fsdp/
        fsdp
        fsdp_v2
```

any way of organizing it is by techinology, for example group all of the SPMD examples together.

**Comment by alanwaketan** [comment]
> > This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.
> 
> I am thinking about that. right now I am thinkign something like
> 
> ```
> examples/
>     data_parallel/
>         xla_ddp
>         ddp
>         spmd_ddp
>     2d sharding/
>         spmd_2d_harding
> 	fsdp/
>         fsdp
>         fsdp_v2
> ```
> 
> any way of organizing it is by techinology, for example group all of the SPMD examples together.

I will personally drop all non-spmd use cases. Otherwise, it will diverge our efforts to direct all of our users to use SPMD...

**Comment by JackCaoG** [comment]
> This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.

I actually refactor this code from tpu-pytorch. I think for fsdp v2 we can just wrap around it so user don't have to read the model code if they dont want to. 2d sharding they have to modify the model code which is a bit annoying..

**Comment by JackCaoG** [comment]
> > > This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.
> > 
> > 
> > I am thinking about that. right now I am thinkign something like
> > ```
> > examples/
> >     data_parallel/
> >         xla_ddp
> >         ddp
> >         spmd_ddp
> >     2d sharding/
> >         spmd_2d_harding
> > 	fsdp/
> >         fsdp
> >         fsdp_v2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > any way of organizing it is by techinology, for example group all of the SPMD examples together.
> 
> I will personally drop all non-spmd use cases. Otherwise, it will diverge our efforts to direct all of our users to use SPMD...

I will write a readme to tell them what we recommend. I felt like it is better to give people choice. If they run our examples(only takes ~1 minutes to run each) it is fairly obvious that SPMD one is faster. I don't want it be like they take a look at examples, don't understand what's spmd and then just move on.

**Comment by alanwaketan** [comment]
> > > > This example directory becomes more and more complex. I guess it's okay, but feel like we are just redoing what we have done in pytorch-tpu here.
> > > 
> > > 
> > > I am thinking about that. right now I am thinkign something like
> > > ```
> > > examples/
> > >     data_parallel/
> > >         xla_ddp
> > >         ddp
> > >         spmd_ddp
> > >     2d sharding/
> > >         spmd_2d_harding
> > > 	fsdp/
> > >         fsdp
> > >         fsdp_v2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > any way of organizing it is by techinology, for example group all of the SPMD examples together.
> > 
> > 
> > I will personally drop all non-spmd use cases. Otherwise, it will diverge our efforts to direct all of our users to use SPMD...
> 
> I will write a readme to tell them what we recommend. I felt like it is better to give people choice. If they run our examples(only takes ~1 minutes to run each) it is fairly obvious that SPMD one is faster. I don't want it be like they take a look at examples, don't understand what's spmd and then just move on.

Or they could run our DDP and FSDPv1 examples and think they are slow and buggy and move on.

**Comment by zpcore** [comment]
Looks like we now must run the *.py test file directly instead of a single unit test with the import:
```
example_folder = os.path.dirname(
      os.path.dirname(os.path.dirname(os.path.abspath(
         sys.argv[0])))) + "/examples"
```
For example: 
```
TORCH_TEST_DEVICES=pytorch/xla/test/pytorch_test_base.py LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib:/usr/local/lib:${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib" python -m unittest test.dynamo.test_dynamo_dynamic_shape.DynamoDynamicShapeBasicTest.test_dynamic_shape_symint_as_return
```
will return `ModuleNotFoundError: No module named 'decoder_only_model'`.

**Comment by JackCaoG** [comment]
hmm I added `test_dynamic_shape_symint_as_return ` last week and it runs OK. import should be handled by https://github.com/pytorch/xla/blob/master/test/dynamo/test_dynamo_dynamic_shape.py#L3-L7

**Comment by zpcore** [comment]
Sorry, I mean the test is fine with how the CI is running it now. Just we are unable to manually use `python -m unittest ...` for this case.

**Pull request merged**
