### PR TITLE
std/var: Add support for floating point correction

### PR DESCRIPTION
**Pull request by peterbell10**
See pytorch/pytorch#94073

### CODE REVIEW

**Comment by JackCaoG** [comment]
Thanks @peterbell10 , Let me know when this is ready to be reviewed. Is this pr plan to make it to the 2.0 release?

**Comment by peterbell10** [comment]
This isn't critical for the 2.0 release.

**Comment by peterbell10** [comment]
@JackCaoG PTAL

**Comment by JackCaoG** [comment]
@wonjoolee95 can you take a look at this one?

**Review by wonjoolee95 — APPROVED** [review]
LGTM, thanks! On the PyTorch PR, you can pin the commit on this PR to make the XLA CI pass. Also, we need to delete the torch pin in this PR before merging this in. Let me know if you need help with the merge process.

**Comment by peterbell10** [comment]
> On the PyTorch PR, you can pin the commit on this PR to make the XLA CI pass.

@wonjoolee95 this doesn't work because my branch is on a fork.

**Comment by wonjoolee95** [comment]
> > On the PyTorch PR, you can pin the commit on this PR to make the XLA CI pass.
> 
> @wonjoolee95 this doesn't work because my branch is on a fork.

Ah I see, okay, let me open a copy PR to pick this up.

**Comment by wonjoolee95** [comment]
@peterbell10, opened https://github.com/pytorch/xla/pull/4674 to pick this up. The last commit on that PR `503401a24e532a9019ef140199319221294045ee` should be available to be picked-up from the PyTorch PR.

**Comment by wonjoolee95** [comment]
Closing this as https://github.com/pytorch/xla/pull/4674 is merged.

**Pull request closed without merging**
