### PR TITLE
Remove unused registration for einsum.

### PR DESCRIPTION
**Pull request by ailzhang**
Our registration for `einsum` is not triggered so skipping registering it for now to unblock my pytorch change on default composite (which will enable a proper `einsum` lowering once it's done). 

https://github.com/pytorch/xla/issues/1364

### CODE REVIEW

**Comment by ailzhang** [comment]
@davidel I do plan to lower it properly after the default composite change so was thinking about leaving the lowering code here. But I can also remove it for now and add it back later. What do you think?

**Comment by davidel** [comment]
If it is going to have a use soon, then it's OK to leave.
Why this ended up not being used?

**Comment by ailzhang** [comment]
Because it was actually a composite op, even we registered a lowering it was never called :(

**Comment by ailzhang** [comment]
Actually let me remove it for now to keep the codebase clean, should be easy to copy paste when adding it back.

**Pull request merged**
