### PR TITLE
Migrate to upstream ir_metadata.h 

### PR DESCRIPTION
**Pull request by wonjoolee95**
Migrate to classes and functions defined in upstream ir_metadata.h.

TODO
- ~Map `XLA_IR_DEBUG` to `FLAGS_torch_lazy_ir_debug`~ (Done)

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Updated `__init__.py` to map PTXLA env variables to upstream PT `lazy-tensor-core` env variables.

**Comment by JackCaoG** [comment]
@wonjoolee95 Let me know when this pr is ready to be reviewed.

**Comment by wonjoolee95** [comment]
An update on this PR: 

Previously, Nikolay mentioned that PyTorch FLAGS can be accessed with:
```
from caffe2.python import workspace
workspace.GlobalInit(['caffe2', '--torch_lazy_ir_debug=true'])
```

With this code, however, the CircleCI build above currently fails with:
```
  File "/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch_xla-1.11-py3.7-linux-x86_64.egg/torch_xla/__init__.py", line 6, in <module>
    from caffe2.python import workspace
  File "/opt/conda/envs/pytorch/lib/python3.7/site-packages/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/opt/conda/envs/pytorch/lib/python3.7/site-packages/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'metanet_pb2' from 'caffe2.proto' (/opt/conda/envs/pytorch/lib/python3.7/site-packages/caffe2/proto/__init__.py)
```

I've reached out to Nikolay regarding this on Slack. Meanwhile, I'll continue to work on other migration.

**Comment by JackCaoG** [comment]
weird, this import works locally for me. I think https://github.com/facebookarchive/caffe2/issues/2099#issuecomment-376025922 explains why this happened. Seems like it has something to do with pytorch path?

**Comment by wonjoolee95** [comment]
Hmm, seems like it's working locally for me as well. I'll try to update the CircleCI environment to try to install the missing package.

**Comment by wonjoolee95** [comment]
Got some update on this, as part of https://github.com/pytorch/pytorch/issues/67151, `caffe2` is officially not a part of nightly PyTorch builds. We should include the `Scope` related methods for now. The other `ir_metadata` related have been included in part of the newer PR https://github.com/pytorch/xla/pull/3385.

**Pull request closed without merging**
