### PR TITLE
[Feature] PJRT support gpu multiple hosts

### PR DESCRIPTION
**Pull request by wbmc**
- Problems
  + GPU doesn't support multiple hosts with PJRT runtime [issue 5588](https://github.com/pytorch/xla/issues/5558) 
- Solution
  + Compatible with `torchelastic` style to launch pytorch jobs
  + Support launching gpu multiple hosts with PJRT runtime

### CODE REVIEW

**Comment by vanbasten23** [comment]
hi @wbmc, thanks a lot for the contribution.

1. I read through your PR and have a few comments. From the PR, on a high level,
- I don't see how users should use it from their ends. It'd be great if you can add some PR description.
- Also, have you tested using multiple GPU VMs? The GPU CI only has 1 host and is not enough to test the feature.

2. Furthermore, I think this feature is worth an Github issue or a design. Per https://github.com/pytorch/pytorch#releases-and-contributing, if you plan to contribute new features, please first open an issue and discuss it with us. Currently, the team has an ongoing effort to implement multi-host GPU.

The implementation is not the hard part. What the team is currently discussing or wants is a consistent user experience with PyTorch and JAX. Also, we would like it to play well with GSPMD, FSDP and other PyTorch/XLA feature.

**Comment by wbmc** [comment]
> hi @wbmc, thanks a lot for the contribution.
> 
> 1. I read through your PR and have a few comments. From the PR, on a high level,
> 
> * I don't see how users should use it from their ends. It'd be great if you can add some PR description.
> * Also, have you tested using multiple GPU VMs? The GPU CI only has 1 host and is not enough to test the feature.
> 
> 2. Furthermore, I think this feature is worth an Github issue or a design. The github issue [[PJRT] Support GPU Multiple Hosts #5558](https://github.com/pytorch/xla/issues/5558) you opened doesn't have much info. Per https://github.com/pytorch/pytorch#releases-and-contributing, if you plan to contribute new features, please first open an issue and discuss it with us. Currently, the team has an ongoing effort to implement multi-host GPU.
> 
> The implementation is not the hard part. What the team is currently discussing or wants is a consistent user experience with PyTorch and JAX. Also, we would like it to play well with GSPMD, FSDP and other PyTorch/XLA features.

Yes, I had test on multiple hosts (a simple all-reduce test on 2 nodes and 16 x A100).
That's a good idea that add some PR descriptions and usages to make the users understand.
Next, Let's discuss at [https://github.com/pytorch/xla/issues/5558](https://github.com/pytorch/xla/issues/5558)
Should I add the example to `pjrt.md` ?

The log below is an all-reduce test on 2 hosts and 16 x A100 GPUs.
```
2023-09-15 02:15:49.346986: I external/xla/xla/pjrt/distributed/service.cc:119] Experimental coordination service is enabled.
2023-09-15 02:15:49.347305: I external/xla/xla/pjrt/distributed/service.cc:149] Jax service listening on 33.151.161.146:30285
2023-09-15 02:15:49.350451: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:0 has connected to coordination service. Incarnation: 2208140455693555140
2023-09-15 02:15:49.350597: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.352342: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:1 has connected to coordination service. Incarnation: 236811497298455355
2023-09-15 02:15:49.352451: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.354235: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:2 has connected to coordination service. Incarnation: 8304127430578798647
2023-09-15 02:15:49.354321: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.356617: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:3 has connected to coordination service. Incarnation: 15042791690196313667
2023-09-15 02:15:49.356782: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.359359: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:4 has connected to coordination service. Incarnation: 12626296033295617445
2023-09-15 02:15:49.359457: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.360185: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:5 has connected to coordination service. Incarnation: 4506215198899583585
2023-09-15 02:15:49.360300: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.362089: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:6 has connected to coordination service. Incarnation: 5143641390414488289
2023-09-15 02:15:49.362184: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:49.364009: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:7 has connected to coordination service. Incarnation: 13421789597007649953
2023-09-15 02:15:49.364119: I external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:303] Coordination agent has successfully connected.
2023-09-15 02:15:50.134298: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:9 has connected to coordination service. Incarnation: 7248634949326409205
2023-09-15 02:15:50.187686: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:14 has connected to coordination service. Incarnation: 8252941071002401340
2023-09-15 02:15:50.235656: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:15 has connected to coordination service. Incarnation: 12300962377928678811
2023-09-15 02:15:50.277550: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:11 has connected to coordination service. Incarnation: 14204551261445058228
2023-09-15 02:15:50.364378: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:13 has connected to coordination service. Incarnation: 9937035408342571101
2023-09-15 02:15:50.592342: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:12 has connected to coordination service. Incarnation: 9502647996696210448
2023-09-15 02:15:50.881470: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:8 has connected to coordination service. Incarnation: 15445073284921189773
2023-09-15 02:15:51.063882: I external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:551] /job:jax_worker/replica:0/task:10 has connected to coordination service. Incarnation: 2242860592052992179
2023-09-15 02:15:51.064579: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064606: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064615: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064621: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064639: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064670: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064678: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:51.064686: I external/xla/xla/pjrt/distributed/client.cc:132] Connected to distributed JAX controller
2023-09-15 02:15:52.417217: I external/xla/xla/service/service.cc:168] XLA service 0x6aa8b00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.417264: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.418224: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.418481: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 1 for BFCAllocator.
2023-09-15 02:15:52.419114: I external/xla/xla/service/service.cc:168] XLA service 0x6df3d80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.419163: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.420343: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.420554: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 0 for BFCAllocator.
2023-09-15 02:15:52.427672: I external/xla/xla/service/service.cc:168] XLA service 0x6aa8b00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.427708: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.428777: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.429021: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 0 for BFCAllocator.
2023-09-15 02:15:52.433832: I external/xla/xla/service/service.cc:168] XLA service 0x6c103e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.433856: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.435339: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.435677: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 0 for BFCAllocator.
2023-09-15 02:15:52.437800: I external/xla/xla/service/service.cc:168] XLA service 0x6df3d80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.437822: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.439091: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.439436: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 1 for BFCAllocator.
2023-09-15 02:15:52.440169: I external/xla/xla/service/service.cc:168] XLA service 0x6e92450 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.440194: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.440234: I external/xla/xla/service/service.cc:168] XLA service 0x6af6bb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.440257: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.441308: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.441407: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.441500: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 0 for BFCAllocator.
2023-09-15 02:15:52.441640: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 1 for BFCAllocator.
2023-09-15 02:15:52.441706: I external/xla/xla/service/service.cc:168] XLA service 0x30aa260 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-15 02:15:52.441729: I external/xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2023-09-15 02:15:52.442804: I external/xla/xla/pjrt/gpu/se_gpu_pjrt_client.cc:634] Using BFC allocator.
2023-09-15 02:15:52.443032: I external/xla/xla/pjrt/gpu/gpu_helpers.cc:105] XLA backend allocating 63898533888 bytes on device 1 for BFCAllocator.
2023-09-15 02:15:54.824678: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.892814: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.909408: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.913312: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.913363: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.913854: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.913946: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:54.914088: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8904
2023-09-15 02:15:56.434560: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.487943: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.591397: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.591672: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.601554: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.606381: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.612240: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
2023-09-15 02:15:56.622188: I external/xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:52] Using nvlink for parallel linking
Print all-reduce result on rank 0: 
tensor([[-44.0312, -44.0312],
        [ 29.2812,  29.2812],
        [-35.5625, -35.5625],
        [ 66.8125,  66.8125],
        [-43.1250, -43.1250],
        [ -2.2812,  -2.2812],
        [  1.2969,   1.2969],
        [123.0000, 123.0000],
        [-27.4062, -27.4062],
        [-29.0781, -29.0781]], device='xla:0')
```

**Comment by vanbasten23** [comment]
Sounds good. Let's discuss at https://github.com/pytorch/xla/issues/5558.

**Comment by wbmc** [comment]
It had been merged in this [PR](https://github.com/pytorch/xla/pull/5657)
Job well done.
Thanks!
@vanbasten23

**Pull request closed without merging**
