### PR TITLE
Fix some more core aten ops

### PR DESCRIPTION
**Pull request by wonjoolee95**
Fixes https://github.com/pytorch/xla/issues/5896, fixes https://github.com/pytorch/xla/issues/5867, fixes https://github.com/pytorch/xla/issues/5884, fixes https://github.com/pytorch/xla/issues/5889

### CODE REVIEW

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Comment by cota** [comment]
I've bisected this commit to a large amount of failures (all torchbench inference on XLA:GPU).

Some example failures:

```
INFO:__main__:Run with --model-config={"model_name": "BERT_pytorch"} --experiment-config={"accelerator": "cuda", "xla": "PJRT", "xla_flags": null, "dynamo": "openxla", "test": "train"}
ERROR:torchbench_model:Cannot load benchmark model
Traceback (most recent call last):
  File "/home/ecg/nightly_runs/2024-01-24/pytorch/xla/benchmarks/torchbench_model.py", line 288, in default_precision_flag
    benchmark = self.load_benchmark()
  File "/home/ecg/nightly_runs/2024-01-24/pytorch/xla/benchmarks/torchbench_model.py", line 267, in load_benchmark
    return benchmark_cls(
  File "/home/ecg/nightly_runs/2024-01-24/benchmark/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/ecg/nightly_runs/2024-01-24/benchmark/torchbenchmark/models/BERT_pytorch/__init__.py", line 148, in __init__
    trainer = BERTTrainer(bert, len(vocab), train_dataloader=train_data_loader, test_dataloader=test_data_loader,
  File "/home/ecg/nightly_runs/2024-01-24/benchmark/torchbenchmark/models/BERT_pytorch/bert_pytorch/trainer/pretrain.py", line 38, in __init__
    self.device = torch.device(device)
TypeError: device() received an invalid combination of arguments - got (bool), but expected one of:
 * (torch.device device)
      didn't match because some of the arguments have invalid types: (!bool!)
 * (str type, int index)
 * ```

```
INFO:__main__:Run with --model-config={"model_name": "Background_Matting"} --experiment-config={"accelerator": "cuda", "xla": "PJRT", "xla_flags": null, "dynamo": "openxla", "test": "eval"}
ERROR:torchbench_model:Cannot load benchmark model
Traceback (most recent call last):
  File "/home/ecg/nightly_runs/2024-01-24/pytorch/xla/benchmarks/torchbench_model.py", line 288, in default_precision_flag
    benchmark = self.load_benchmark()
  File "/home/ecg/nightly_runs/2024-01-24/pytorch/xla/benchmarks/torchbench_model.py", line 267, in load_benchmark
    return benchmark_cls(
  File "/home/ecg/nightly_runs/2024-01-24/benchmark/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/ecg/nightly_runs/2024-01-24/benchmark/torchbenchmark/models/Background_Matting/__init__.py", line 72, in __init__
    netB.to(self.device)
  File "/home/ecg/nightly_runs/2024-01-24/pytorch/torch/nn/modules/module.py", line 1137, in to
    raise TypeError('nn.Module.to only accepts floating point or complex '
TypeError: nn.Module.to only accepts floating point or complex dtypes, but got desired dtype=torch.bool
```

Does this ring any bells?
```

**Comment by wonjoolee95** [comment]
Thanks for catching this. It's hard to identify the offending op just looking at the trace, but this PR basically only touches two ops -- aten::reciprocal and aten::sigmoid. Let me revert the changes that this PR does for this two ops for now and investigate.

**Comment by wonjoolee95** [comment]
Reading the error, it's complaining that it's getting passed a boolean in `.device()` and `.to()` methods. Just by a quick look, the errors seem irrelevant to this PR's change but let me continue to investigate.

@cota, is there doc that describes the set-up for me to repro that (run torchbench) in GPU?

**Comment by cota** [comment]
@wonjoolee95 I re-did the bisection paying more attention this time. It turns out that the problem was introduced in a prior commit, not in this PR. My apologies! :(
Things are now working on master, and I have confirmed that reinstating this PR still works.
I've sent https://github.com/pytorch/xla/pull/6387 to reapply this change.

**Pull request merged**
