### PR TITLE
Skip test on two logical ops

### PR DESCRIPTION
**Pull request by xuhdev**
Related to https://github.com/pytorch/pytorch/pull/28162

### CODE REVIEW

**Comment by nairbv** [comment]
what does this mean / why are we skipping them?

**Comment by ailzhang** [comment]
Skipping is not the way to fix ;) We need to know the root cause why it worked and how it's broken before we disable it

**Comment by mruberry** [comment]
> Skipping is not the way to fix ;) We need to know the root cause why it worked and how it's broken before we disable it

We can disable tests to allow engineering progress / continue to run the rest of the test suite. Where are these tests coming from in PyTorch, though? I can't find them.

**Comment by xuhdev** [comment]
I added the skipping merely because `logical_xor` is also skipped. I think it would deserve another PR if we wanna fix this. I have no idea what the storage error message means:

> RuntimeError: torch_xla/csrc/tensor_impl.cpp:147 : XLA tensors do not have storage

@mruberry These tests do not exist in PyTorch yet but they are to be added in https://github.com/pytorch/pytorch/pull/28162

**Comment by xuhdev** [comment]
I personally would prefer to not skip any test if there is a way to figure out the reason...

**Comment by ailzhang** [comment]
@xuhdev I think this might be related to the dispatcher behavior, I'm compiling your PR locally, will probably send out some updates on the source of the error in a few hrs. :D

**Comment by xuhdev** [comment]
@ailzhang Thanks! Actually you can test  `logical_xor` on master, which has been currently skipped (if this is easier for you). These logical operators have similar structure.

**Comment by ailzhang** [comment]
Commented on the PT PR :D

**Comment by ailzhang** [comment]
Adding a label here since the original PT PR is being updated.

**Comment by xuhdev** [comment]
I think we can safely close this for now. There are some complications on the PT PR. Will deal with it on Monday

**Pull request closed without merging**
