### PR TITLE
Forward subprocess stdout and stderr in all cases

### PR DESCRIPTION
**Pull request by frgossen**
Previously output was not forwarded in failure cases.

### CODE REVIEW

**Comment by cota** [comment]
Sorry to be that guy. Can you break up the patch into the NFC bits and the ones that matter?

**Comment by cota** [comment]
What I mean is: this PR will go in as a single commit that doesn't fully reflect what the code changes are.

**Comment by frgossen** [comment]
As discussed offline, the diff includes dependent PRs. Will let the CI finish and rebase then.

**Comment by frgossen** [comment]
All checks have passed
Rebasing to clean up the diff

**Pull request merged**
