### PR TITLE
[SPMD][DTensor] introduce xla_distribute_module for DTensor integration

### PR DESCRIPTION
**Pull request by yeounoh**
This is to support https://github.com/pytorch/pytorch/issues/92909

### CODE REVIEW

**Comment by yeounoh** [comment]
cc @baoleai for visibility

**Comment by yeounoh** [comment]
CI turned green, and locally looks good on TPU and CPU
```
python test/spmd/test_dtensor_integration.py
...
----------------------------------------------------------------------
Ran 3 tests in 3.740s

OK
```

**Review by alanwaketan — APPROVED** [review]
LGTM, but how does that work with auto_sharding? You still shard the inputs in the test case.

**Comment by yeounoh** [comment]
> LGTM, but how does that work with auto_sharding? You still shard the inputs in the test case.

Good question, we were thinkning about introducing pre-defined partition_fn for autosharding, e.g., `torch_xla.distributed.auto_sharding_policy` (subject to change). It would just be calling `use_spmd(auto=True)` though.

**Pull request merged**
