### PR TITLE
[SPMD] Fix TPU CI after #5478

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
Let's fix all TPU CI failures after #5478.

Test Plan:
TPU CI

### CODE REVIEW

**Comment by JackCaoG** [comment]
Can you fix the linter and trigger the tpu CI in this pr?

**Comment by alanwaketan** [comment]
Oops, just triggered the TPU CI... Let me fix the linters and re-trigger it. On the hands, is it pantheon still the only way to trigger TPU CI?

**Comment by JackCaoG** [comment]
yea you can find the trigeer, modify the branch to your branch and run it

**Comment by alanwaketan** [comment]
TPU CI is passing. Let's merge it!

**Comment by alanwaketan** [comment]
Oops, I still need a LGTM.

**Review by JackCaoG — APPROVED** [review]

**Pull request merged**
