### PR TITLE
Backport infra/ansible to r2.0

### PR DESCRIPTION
**Pull request by wonjoolee95**
Backport infra/ansible to r2.0

### CODE REVIEW

**Comment by JackCaoG** [comment]
@mateuszlewko FYI

**Comment by wonjoolee95** [comment]
@JackCaoG, are we good on merging this to `2.0` branch? Or shall we wait on @mateuszlewko's input?

**Comment by wonjoolee95** [comment]
Thanks for the approval, Jack. I'll merge this and update the `v2.0.0` tag on the `r2.0` branch.

**Comment by wonjoolee95** [comment]
Updated the `v2.0.0` tag on `r2.0` branch with commands:
```
  456  git checkout r2.0
  457  git pull
  459  git tag -d v2.0.0
  461  git push origin r2.0 :refs/tags/v2.0.0
  462  git tag v2.0.0 500e1c27530a21408fbd181a7296eda9cdcbe834
  464  git push origin r2.0 v2.0.0
```
Now, we can see that the `v2.0.0` tag corresponds to this commit -- https://github.com/pytorch/xla/releases/tag/v2.0.0.

**Pull request merged**
