### PR TITLE
[test] Replace `core:lib` with `"@org_tensorflow//tensorflow/tsl/plat…

### PR DESCRIPTION
**Pull request by ManfeiBai**
…form:hash",`

### CODE REVIEW

**Comment by JackCaoG** [comment]
seems like error is from https://github.com/pytorch/xla/blob/0015ea695a298ea38b3e2101855791af97d1b13c/torch_xla/csrc/runtime/runtime.cc#L1

**Comment by ManfeiBai** [comment]
> seems like error is from
> 
> https://github.com/pytorch/xla/blob/0015ea695a298ea38b3e2101855791af97d1b13c/torch_xla/csrc/runtime/runtime.cc#L1

Thanks, Jack, updated to add `stacktrace_handler`

**Comment by ManfeiBai** [comment]
checked all the deps in `util` and added its deps fully first before continue to check `async_task_test `'s deps

**Comment by JackCaoG** [comment]
hmm, it failed at building the CPP test again.

**Comment by ManfeiBai** [comment]
this PR failed and plan to redefine `ptxla_cc_test` with `xla_cc_test` to help to fix some failure by https://github.com/pytorch/xla/pull/5165;

so will continue to track work in https://github.com/pytorch/xla/pull/5197 after the https://github.com/pytorch/xla/pull/5165

**Pull request closed without merging**
