### PR TITLE
Migrate to upstream Device

### PR DESCRIPTION
**Pull request by wonjoolee95**
Adding back this commit. 

Opened a PyTorch PR pinned to this PR for debugging -- https://github.com/pytorch/pytorch/pull/74497.

### CODE REVIEW

**Comment by JackCaoG** [comment]
Can you rebase to get pass the test error?

**Comment by wonjoolee95** [comment]
@JackCaoG FYI this is ready for review now. Thanks!

**Comment by JackCaoG** [comment]
I will approve now since it is the same pr we reverted. After Yeounoh's fix is merged, please make sure this change does not break pytorch CI before merging.

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by wonjoolee95** [comment]
> I will approve now since it is the same pr we reverted. After Yeounoh's fix is merged, please make sure this change does not break pytorch CI before merging.

Thanks! Merging this now as the PyTorch CI pinned onto this branch (https://github.com/pytorch/pytorch/pull/74756) has all passed the CI.

**Pull request merged**
