### PR TITLE
Add neural style transfer notebook.

### PR DESCRIPTION
**Pull request by ailzhang**
I'm not very familiar with colab, but tried to make it runnable by everyone with google drive access. Please let me know if this works.

### CODE REVIEW

**Comment by ailzhang** [comment]
sigh github said no lol

**Comment by jysohn23** [comment]
Thanks @ailzhang! A few things:
* Should we maybe remove cell outputs? @dlibenzi had suggested that for my previous notebooks.
* There's an empty cell at the end with no content. Maybe we could clean it up?

**Comment by dlibenzi** [comment]
> Thanks @ailzhang! 2 things:
> 
> * Should we maybe remove cell outputs? @dlibenzi had suggested that for my previous notebooks.
> * There's an empty cell at the end with no content. Maybe we could clean it up?

Oh yes, removing output ... I kinda agree.
But maybe if there is a picture it helps as decoration?
No strong feeling here from my POV.

**Comment by dlibenzi** [comment]
> > Thanks @ailzhang! 2 things:
> > 
> > * Should we maybe remove cell outputs? @dlibenzi had suggested that for my previous notebooks.
> > * There's an empty cell at the end with no content. Maybe we could clean it up?
> 
> Oh yes, removing output ... I kinda agree.
> But maybe if there is a picture it helps as decoration?
> No strong feeling here from my POV.

Yeah, @jysohn23 I feel in this case the output helps in the "Colab Decoration", no?

**Comment by jysohn23** [comment]
> Yeah, @jysohn23 I feel in this case the output helps in the "Colab Decoration", no?

We can leave it in there (I'm in favor of leaving output in there, especially this one 😄)

**Comment by dlibenzi** [comment]
I am merging this @ailzhang .
I am in favor of adding back the puppies though 😄

**Pull request merged**
