### PR TITLE
Allowing squeezenet after verifying it runs e2e

### PR DESCRIPTION
**Pull request by taylanbil**
For some reason, loss doesn't move with --fake_data enabled. It should not be an issue though. Let me know what you think.

### CODE REVIEW

**Comment by dlibenzi** [comment]
I'd hold off on this, as if we want to enable the tests, it'd fail.

**Comment by asuhan** [comment]
Why would the tests fail?

**Comment by taylanbil** [comment]
do we require a certain accuracy / loss value with fake data?

**Comment by asuhan** [comment]
We can certainly relax the threshold if that's the problem. Also, you could look at the ranges of the values in the real data input and make the fake data more similar, it should be possible.

**Comment by dlibenzi** [comment]
Oh, OK. With real data the model is fine.
Got confused by the thread.

**Pull request merged**
