### PR TITLE
Support dynamism on "transpose" operation.

### PR DESCRIPTION
**Pull request by vanbasten23**
Currently the `test_backward_pass_with_dynamic_input` tests failed with error:
```
RuntimeError: /workspaces/work/pytorch/xla/torch_xla/csrc/helpers.cpp:273 : Check failed: out_size <= size_at_dyndim / input_shape.dimensions( input_dynamic_dimension) (2 vs. 1)
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()
        torch_xla::XlaHelpers::GetDynamicReshapeInfo(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::XlaHelpers::GetDynamicReshape(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::Permute::MakePermuteShape(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::ViewInfo::ViewInfo(torch_xla::ViewInfo::Type, xla::Shape, std::vector<long, std::allocator<long> >)
        torch_xla::tensor_methods::transpose(c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > const&, long, long)
        torch_xla::XLANativeFunctions::t_copy(at::Tensor const&)
...
*** End stack trace ***
Unable to map dynamic dimension of shape s32[<=12,2]{1,0} to output sizes (2, 12)
```
This PR is intended to fix this error.

With this PR, the above test fails with another error:
```
======================================================================
ERROR: test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 115, in test_backward_pass_with_dynamic_input
    loss.backward()
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: `InlinedVector::at(size_type) const` failed bounds check
```
From the [stacktrace](https://paste.googleplex.com/6299248223059968), it seems something is wrong with `XLANativeFunctions::unsqueeze_copy` which I will fix in the next PR.

### CODE REVIEW

**Comment by vanbasten23** [comment]
Just did a rebase onto origin/functionalization, the new error changed to:
```
======================================================================
ERROR: test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 114, in test_backward_pass_with_dynamic_input
    loss.backward()
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: /workspaces/work/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:3147: SymIntArrayRef expected to contain only concrete integers
Exception raised from asIntArrayRefSlow at /workspaces/work/pytorch/c10/core/SymIntArrayRef.h:41 (most recent call first):
frame #0: <unknown function> + 0x9cdff (0x7fb19b6dadff in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4d (0x7fb0ee13290d in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x57 (0x7fb19b6d9e47 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7a (0x7fb19b6d7a6a in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: c10::asIntArrayRefSlow(c10::ArrayRef<c10::SymInt>, char const*, long) + 0xc9 (0x7fb0628571f9 in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #5: torch_xla::XLANativeFunctions::view_copy_symint(at::Tensor const&, c10::ArrayRef<c10::SymInt>) + 0x54 (0x7fb062823764 in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x103d76c (0x7fb062d7376c in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x103dace (0x7fb062d73ace in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x103dcaa (0x7fb062d73caa in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x103dbcf (0x7fb062d73bcf in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x103db21 (0x7fb062d73b21 in /home/ptxla/.local/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0xaa0ad6 (0x7fb0fbcbdad6 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xa9fae5 (0x7fb0fbcbcae5 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0xa9f88f (0x7fb0fbcbc88f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0xa9edb0 (0x7fb0fbcbbdb0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0xa94285 (0x7fb0fbcb1285 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0x1c4f6bf (0x7fb0e857a6bf in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x1c4f771 (0x7fb0e857a771 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x18c9c96 (0x7fb0e81f4c96 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0x2cdcbac (0x7fb0e9607bac in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: at::_ops::view_copy::call(at::Tensor const&, c10::ArrayRef<c10::SymInt>) + 0x804 (0x7fb0e9cb6724 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #21: <unknown function> + 0x48f78a7 (0x7fb0eb2228a7 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #22: <unknown function> + 0x499c941 (0x7fb0eb2c7941 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #23: <unknown function> + 0x499cb2a (0x7fb0eb2c7b2a in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #24: <unknown function> + 0x499ca4f (0x7fb0eb2c7a4f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #25: <unknown function> + 0x499c9a1 (0x7fb0eb2c79a1 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #26: <unknown function> + 0xaa0ad6 (0x7fb0fbcbdad6 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #27: <unknown function> + 0xa9fae5 (0x7fb0fbcbcae5 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #28: <unknown function> + 0xa9f88f (0x7fb0fbcbc88f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0xa9edb0 (0x7fb0fbcbbdb0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #30: <unknown function> + 0xa94285 (0x7fb0fbcb1285 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #31: <unknown function> + 0x1c4f6bf (0x7fb0e857a6bf in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #32: <unknown function> + 0x1c4f771 (0x7fb0e857a771 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #33: <unknown function> + 0x18c9c96 (0x7fb0e81f4c96 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #34: <unknown function> + 0x2cdcbac (0x7fb0e9607bac in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #35: <unknown function> + 0x2cdd244 (0x7fb0e9608244 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #36: at::_ops::view::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>) + 0x1e8 (0x7fb0e9ff82c8 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #37: <unknown function> + 0x73a3f3f (0x7fb0edccef3f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #38: <unknown function> + 0x73a3b74 (0x7fb0edcceb74 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #39: <unknown function> + 0x73a4751 (0x7fb0edccf751 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #40: <unknown function> + 0x73a493a (0x7fb0edccf93a in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #41: <unknown function> + 0x73a485f (0x7fb0edccf85f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #42: <unknown function> + 0x73a47b1 (0x7fb0edccf7b1 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #43: <unknown function> + 0xaa0ad6 (0x7fb0fbcbdad6 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #44: <unknown function> + 0xa9fae5 (0x7fb0fbcbcae5 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #45: <unknown function> + 0xa9f88f (0x7fb0fbcbc88f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #46: <unknown function> + 0xa9edb0 (0x7fb0fbcbbdb0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #47: <unknown function> + 0xa94285 (0x7fb0fbcb1285 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #48: <unknown function> + 0x1c4f6bf (0x7fb0e857a6bf in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #49: <unknown function> + 0x1c4f771 (0x7fb0e857a771 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #50: <unknown function> + 0x18c9c96 (0x7fb0e81f4c96 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #51: <unknown function> + 0x2cdcbac (0x7fb0e9607bac in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #52: <unknown function> + 0x2cdd244 (0x7fb0e9608244 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #53: at::_ops::view::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>) + 0x1e8 (0x7fb0e9ff82c8 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #54: <unknown function> + 0x66ef22c (0x7fb0ed01a22c in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #55: <unknown function> + 0x66656df (0x7fb0ecf906df in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #56: <unknown function> + 0x6664c75 (0x7fb0ecf8fc75 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #57: <unknown function> + 0x66659e1 (0x7fb0ecf909e1 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #58: <unknown function> + 0x6665bca (0x7fb0ecf90bca in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #59: <unknown function> + 0x6665aef (0x7fb0ecf90aef in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #60: <unknown function> + 0x6665a41 (0x7fb0ecf90a41 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #61: <unknown function> + 0xaa0ad6 (0x7fb0fbcbdad6 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #62: <unknown function> + 0xa9fae5 (0x7fb0fbcbcae5 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #63: <unknown function> + 0xa9f88f (0x7fb0fbcbc88f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
```

**Comment by alanwaketan** [comment]
The `test_backward_pass_with_dynamic_input` seems working on the functionalization branch?

**Comment by vanbasten23** [comment]
> The `test_backward_pass_with_dynamic_input` seems working on the functionalization branch?

We have never gotten this test to work in either the master branch or the functionalization branch: https://github.com/pytorch/xla/blob/53a9cb2be5ee5972ea4cf11801be0950b2adf041/test/test_dynamic_shape_models.py#L95-L98. The ultimate goal of this PR is to get this test to work.

Some more context: previously this test were blocked on the view ops so we wanted to leverage the functionalization work.

**Review by JackCaoG — COMMENTED** [review]
as discussed, let move this pr to a separate functionalization_ds branch

**Comment by vanbasten23** [comment]
> as discussed, let move this pr to a separate functionalization_ds branch

done

**Review by JackCaoG — APPROVED** [review]

**Review by alanwaketan — APPROVED** [review]

**Comment by vanbasten23** [comment]
Thanks for the review!

**Pull request merged**
