### PR TITLE
Add PjRt check for test_too_many_parameter test

### PR DESCRIPTION
**Pull request by wonjoolee95**

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Did you have a chance to verify it on TPUVM directly?

**Comment by wonjoolee95** [comment]
> Did you have a chance to verify it on TPUVM directly?

Not yet, I'm rebuilding PyTorch and XLA right now locally after rebasing with master. I'll verify before I merge this.

**Review by JackCaoG — APPROVED** [review]

**Comment by wonjoolee95** [comment]
I can confirm that running this test with `PjRt` runs (and passes) the test and with `xrt` skips the test:
```
wonjoo@t1v-n-0dd7892e-w-0:~/pytorch/xla$ PJRT_DEVICE=TPU python test/test_operations.py TestAtenXlaTensor.test_too_many_parameter
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Running pjrt
Test finished
----------------------------------------------------------------------
Ran 1 test in 33.527s

OK
wonjoo@t1v-n-0dd7892e-w-0:~/pytorch/xla$ python test/test_operations.py TestAtenXlaTensor.test_too_many_parameter
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Running xrt
Test finished
----------------------------------------------------------------------
Ran 1 test in 13.094s

OK
wonjoo@t1v-n-0dd7892e-w-0:~/pytorch/xla$ 
```
nit: the print statements were for debugging

**Comment by wonjoolee95** [comment]
Merging this as I've verified it on TPUVM and the CI is green.

**Pull request merged**
