### PR TITLE
Update the tf pin to 2023 01/23

### PR DESCRIPTION
**Pull request by JackCaoG**
I am able to get tests to pass on TPUVM after
1. pin to a commit that reverts the grpc change https://github.com/tensorflow/tensorflow/commit/b41c4a309d8c6da7074a6bbb8087b21d21d2c37a
2. manually build libtpu since libtpu build has been failing for a week

now letting the CI to confirm changes for CPU and GPU.

FYI @antoniojkim

### CODE REVIEW

**Comment by JackCaoG** [comment]
Also, the build can pass without sandbox on my docker. I will remove the sandbox env var in a following commit.

**Comment by JackCaoG** [comment]
ok, GPU build seems to have some issues
```
/tmp/pytorch/xla/third_party/tensorflow/bazel-bin/tensorflow/tsl/protobuf/autotuning.pb.h:247:34: warning: In the GNU C Library, "major" is defined by <sys/sysmacros.h>. For historical compatibility, it is currently defined by <sys/types.h> as well, but we plan to remove this soon. To use "major", include <sys/sysmacros.h> directly. If you did not intend to use a system-defined macro "major", you should undefine it after including <sys/types.h>. [-W#pragma-messages]
  ::PROTOBUF_NAMESPACE_ID::int32 major() const;
                                 ^
/usr/include/x86_64-linux-gnu/sys/sysmacros.h:101:21: note: expanded from macro 'major'
# define major(dev) __SYSMACROS_DM (major) gnu_dev_major (dev)
                    ^
/usr/include/x86_64-linux-gnu/sys/sysmacros.h:52:32: note: expanded from macro '__SYSMACROS_DM'
#define __SYSMACROS_DM(symbol) __SYSMACROS_DM1 \
                               ^
/usr/include/x86_64-linux-gnu/sys/sysmacros.h:62:30: note: expanded from macro '__SYSMACROS_DM1'
#define __SYSMACROS_DM1(...) __glibc_macro_warning (#__VA_ARGS__)
                             ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:470:3: note: expanded from macro '__glibc_macro_warning'
  __glibc_macro_warning1 (GCC warning message)
  ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:468:42: note: expanded from macro '__glibc_macro_warning1'
# define __glibc_macro_warning1(message) _Pragma (#message)
                                         ^
<scratch space>:50:6: note: expanded from here
 GCC warning "In the GNU C Library, \"major\" is defined\n by <sys/sysmacros.h>. For historical compatibility, it is\n currently defined by <sys/types.h> as well, but we plan to\n remove this soon. To use \"major\", include <sys/sysmacros.h>\n directly. If you did not intend to use a system-defined macro\n \"major\", you should undefine it after including <sys/types.h>."
     ^

```

**Comment by JackCaoG** [comment]
OK great, for some reason the GPU build also passes.. now I am going to test the wheel build and upstream CI.

**Review by antoniojkim — APPROVED** [review]
I've verified that it works for gcc10 now

**Comment by antoniojkim** [comment]
@JackCaoG what is the status of this? when can this be merged into `master`?

**Comment by JackCaoG** [comment]
I am blocked by the internal libtpu build failure, someone is taking a look. I am hoping to merge this(I might need to move the pin again to match the libtpu) by the end of this week.

**Comment by JackCaoG** [comment]
move the pin to 01/23, libtpu build should start passing tmr.

**Comment by vanbasten23** [comment]
Btw, with this PR, `nonzero` would give the correct result:
```
root@t1v-n-5f93dd4b-w-0:/workspaces/work# XLA_EXPERIMENTAL="nonzero:masked_select:masked_scatter" python3 runTest.py
tensor([[0, 0],
        [0, 3],
        [0, 5]], device='xla:0', dtype=torch.int32)
```
as opposed to the old tf pin: https://github.com/pytorch/xla/issues/4432.

**Comment by JackCaoG** [comment]
Kicked off the CI, docker trigger and upstream CI build at https://github.com/pytorch/pytorch/pull/92999. If all of them passed, we are ready to merge

**Comment by JackCaoG** [comment]
@vanbasten23 You can try again, if you use `01/25` libtpu it should work(it worked for me)

**Comment by JackCaoG** [comment]
cpu test failure is irrelevant

**Comment by vanbasten23** [comment]
I wonder if it's been tested on TPU. When I try to run a test on my container on TPU VM, I got an error: https://paste.googleplex.com/6236687502934016. Not sure if it's my env setup issue.

**Comment by JackCaoG** [comment]
it worked for me on TPUVM.

**Comment by JackCaoG** [comment]
Ok I updated the libtpu to `01/24` due to some known issue and I did
```
(pytorch) root@t1v-n-7513beeb-w-0:/pytorch/xla# pip3 install torch_xla[tpuvm]
Requirement already satisfied: torch_xla[tpuvm] in /pytorch/xla (2.0.0)
Collecting libtpu-nightly@ https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20230124-py3-none-any.whl
  Downloading https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20230124-py3-none-any.whl (229.0 MB)
     |████████████████████████████████| 229.0 MB 41 kB/s 
(pytorch) root@t1v-n-7513beeb-w-0:/pytorch/xla# XRT_TPU_CONFIG="localservice;0;localhost:51011" python /test/test.py
tensor(1000000, device='xla:1')
(pytorch) root@t1v-n-7513beeb-w-0:/pytorch/xla# PJRT_DEVICE="TPU" python /test/test.py
tensor(1000000, device='xla:0')
```

it is a sanity test
```
(pytorch) root@t1v-n-7513beeb-w-0:/pytorch/xla# cat /test/test.py
import torch
import torch_xla
import torch_xla.core.xla_model as xm



t1 = torch.tensor(100, device=xm.xla_device())
t2 = t1 * 10000
xm.mark_step()
print(t2)
```

**Comment by JackCaoG** [comment]
resnet speed also seems reasonable with xrt
```
| Training Device=xla:0/3 Epoch=1 Step=100 Loss=0.02205 Rate=537.77 GlobalRate=148.01 Time=23:28:17
| Training Device=xla:0/7 Epoch=1 Step=100 Loss=0.02205 Rate=537.16 GlobalRate=142.25 Time=23:28:17
| Training Device=xla:0/1 Epoch=1 Step=100 Loss=0.02205 Rate=537.61 GlobalRate=140.93 Time=23:28:17
| Training Device=xla:0/4 Epoch=1 Step=100 Loss=0.02205 Rate=537.57 GlobalRate=141.35 Time=23:28:17
| Training Device=xla:0/5 Epoch=1 Step=100 Loss=0.02205 Rate=536.95 GlobalRate=140.43 Time=23:28:17
| Training Device=xla:0/6 Epoch=1 Step=120 Loss=0.01664 Rate=552.46 GlobalRate=171.87 Time=23:28:22
| Training Device=xla:0/1 Epoch=1 Step=120 Loss=0.01664 Rate=552.85 GlobalRate=160.86 Time=23:28:22
| Training Device=xla:1/0 Epoch=1 Step=120 Loss=0.01664 Rate=551.93 GlobalRate=159.68 Time=23:28:22
| Training Device=xla:0/4 Epoch=1 Step=120 Loss=0.01664 Rate=552.16 GlobalRate=161.30 Time=23:28:22
| Training Device=xla:0/5 Epoch=1 Step=120 Loss=0.01664 Rate=552.02 GlobalRate=160.31 Time=23:28:22
| Training Device=xla:0/2 Epoch=1 Step=120 Loss=0.01664 Rate=551.40 GlobalRate=161.69 Time=23:28:22
| Training Device=xla:0/3 Epoch=1 Step=120 Loss=0.01664 Rate=552.12 GlobalRate=168.53 Time=23:28:22
| Training Device=xla:0/7 Epoch=1 Step=120 Loss=0.01664 Rate=551.90 GlobalRate=162.28 Time=23:28:22
```

**Review by will-cromar — APPROVED** [review]

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Pull request merged**
