### PR TITLE
updating BN forward inference running_stats output

### PR DESCRIPTION
**Pull request by jjsjann123**
output two defined empty tensor for BN forward.
This is to stay in consistency with PyTorch core changes that are introducing in https://github.com/pytorch/pytorch/pull/57321

### CODE REVIEW

**Comment by JackCaoG** [comment]
Change LGTM, could you add a `.torch_pin` (example https://github.com/pytorch/xla/pull/2944/files#diff-e71f55b9deb410fad9d5945c4c30878a93369434520520987ac03c59bfa5280d) and point it to your pytorch pr? This way when CI is kicked off it will use your branch as upstream pytorch.

**Comment by jjsjann123** [comment]
Looks like the CI is linked. Unfortunately the fix doesn't seem to work... Let me take another look.

**Comment by jjsjann123** [comment]
Does size 0 tensor considered NULL in XLA?
The tensor is created with this vvv. `bridge::GetXlaTensor(at::empty({0}, at_input.options()));` and later checked with this `td::get<1>(xla_output).is_null()`

I need to figure out how to run that test locally... It's way to painful to debug with CI. :(

**Comment by jjsjann123** [comment]
I don't understand the PR failure in last commit.

Granted that without merging master, xla branch doesn't build due to some API changes. But shouldn't that give me a build error instead of a test failure?
I finally got a local build with tests and I have verified the fix for `TensorTest.TestBatchNorm1D`. :crossed_fingers:

**Comment by JackCaoG** [comment]
Thanks! I will review this change when pytorch pr is more final.

**Comment by jjsjann123** [comment]
@JackCaoG Finally got an approval on my PyTorch PR. Do you want me to rebase this one so it's in a ready to merge state?

**Comment by JackCaoG** [comment]
@jjsjann123 Please do, I will take a quick look after CI pass. Thanks for putting this togther!

**Review by JackCaoG — APPROVED** [review]
Upstream already merged. I will remove the pin and merge this one

**Pull request merged**
