### PR TITLE
Adding the benchmarking with TorchBench

### PR DESCRIPTION
**Pull request by Liyang90**
Merging the benchmark fork

### CODE REVIEW

**Comment by JackCaoG** [comment]
Thanks @Liyang90 @zpcore can you verified if this script works on today's nightly before we merge this one?

**Comment by zpcore** [comment]
> Thanks @Liyang90 @zpcore can you verified if this script works on today's nightly before we merge this one?

I don't think so, there are several things we want to update, e.g.,:
1) https://github.com/zpcore/xla/commit/835b5eae064c9ef17685c3d7b3353c691306250e:  Dynamo backend naming

2) https://github.com/zpcore/xla/commit/b146f0a313c798c4829c9eaaa2363b2bef6ed969 Update with newest torchbench call api.

3) https://github.com/zpcore/xla/commit/b853e8587262504c43a49c320769ad33848b1b17 Enable Dynamo optimizer.

Should we check in this version first and make the update next? We can add the CI once we are done with the update with the latest build.

**Comment by Liyang90** [comment]
> > Thanks @Liyang90 @zpcore can you verified if this script works on today's nightly before we merge this one?
> 
> I don't think so, there are several things we want to update, e.g.,:
> 
> 1. [zpcore@835b5ea](https://github.com/zpcore/xla/commit/835b5eae064c9ef17685c3d7b3353c691306250e):  Dynamo backend naming
> 2. [zpcore@b146f0a](https://github.com/zpcore/xla/commit/b146f0a313c798c4829c9eaaa2363b2bef6ed969) Update with newest torchbench call api.
> 3. [zpcore@b853e85](https://github.com/zpcore/xla/commit/b853e8587262504c43a49c320769ad33848b1b17) Enable Dynamo optimizer.
> 
> Should we check in this version first and make the update next? We can add the CI once we are done with the update with the latest build.

Right, I think this PR requires a follow up PR before its functionality is tested.

**Comment by JackCaoG** [comment]
Yea I am ok with merging it as it is while we are working on follow up prs.

**Review by JackCaoG — APPROVED** [review]

**Comment by frgossen** [comment]
I ran into a few issues with the runner and think it needs a few minor changes. 
https://github.com/pytorch/xla/pull/5806/files

**Pull request merged**
