### PR TITLE
[Functionalization] Remove View in tensor_methods::slice

### PR DESCRIPTION
**Pull request by vanbasten23**
Summary:
This pull request removes the View path in tensor_methods::slice when
Functionalization is enabled.

Test Plan: CI

### CODE REVIEW

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by vanbasten23** [comment]
Still debugging the failing test `FAIL: test_save_view_alias_check (__main__.TestAtenXlaTensor)`

**Comment by vanbasten23** [comment]
> Still debugging the failing test `FAIL: test_save_view_alias_check (__main__.TestAtenXlaTensor)`

Should've been fixed by the latest change.

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by vanbasten23** [comment]
Thanks for the review!

**Pull request merged**
