### PR TITLE
Gconvert

### PR DESCRIPTION
**Pull request by dlibenzi**

### CODE REVIEW

**Comment by asuhan** [comment]
What's up with the failing test? Looks like our backward implementation worked in conjunction with `nll_loss_forward` as implemented by `ATen`, but not with our own?

**Comment by dlibenzi** [comment]
Two failures in CI, works in my workstation. Let me pull PT latest ...

**Comment by dlibenzi** [comment]
After a PT pull now I see the failure. Weird, I had pulled Friday night.
Looking into the weight handling.

**Comment by dlibenzi** [comment]
After looking at the THNN code, one is the correct total weight initializer in case of missing weights.
We might have to go ahead and implement the weight lowering at some point later.

**Comment by asuhan** [comment]
The weight lowering should be easy, I think it's just multiplying the gradient we compute now by the original weights. However, as long as we don't have an use case for it, we can postpone it indefinitely.

**Pull request merged**
