### PR TITLE
[test] Openxla try jun 06 2023 test

### PR DESCRIPTION
**Pull request by ManfeiBai**

### CODE REVIEW

**Comment by ManfeiBai** [comment]
bazel build successed locally, failed in CI

**Comment by JackCaoG** [comment]
@stgpetrovic We have been seeing this 
```
2023-06-07T23:09:46.1517791Z error: command '/usr/local/bin/bazel' failed with exit code 37
2023-06-07T23:09:46.4314863Z ##[error]Process completed with exit code 1.
2023-06-07T23:09:46.4361165Z ##[group]Run pytorch/test-infra/.github/actions/teardown-linux@main
2023-06-07T23:09:46.4361418Z with:
```
error pretty frequently and we don't see the error message. Any debugging tip?

**Comment by ManfeiBai** [comment]
try `python setup.py install` locally and failed with error:
```
ERROR: /workspace/pytorch/xla/torch_xla/csrc/BUILD:31:17: Compiling torch_xla/csrc/RegisterXLA.cpp failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/torch_xla/csrc/_objs/tensor/RegisterXLA.pic.d ... (remaining 573 arguments skipped)
```

I could bazel build `codegen/lazy_tensor_generator`, `codegen/fix_includes` and `torch/csrc/gen_lazy_tensor`, 

but found the path in the error message:`bazel-out/k8-opt/bin/torch_xla/csrc/_objs/tensor/RegisterXLA.pic.d` shows:
only `RegisterXLA.pic.d` don't have its matched `RegisterXLA.pic.o`:
```
(base) jenkins@8729079ec483:/workspace/pytorch/xla/bazel-out/k8-opt/bin/torch_xla/csrc/_objs/tensor$ ls
0                        multinomial.pic.o
1                        native_batch_norm_backward.pic.d
RegisterAutogradXLA.pic.d            native_batch_norm_backward.pic.o
RegisterAutogradXLA.pic.o            native_batch_norm_forward.pic.d
RegisterXLA.pic.d                native_batch_norm_forward.pic.o
XLANativeFunctions.pic.d            nll_loss2d.pic.d
XLANativeFunctions.pic.o            nll_loss2d.pic.o
adam_optimizer_step.pic.d            nll_loss2d_backward.pic.d
adam_optimizer_step.pic.o            nll_loss2d_backward.pic.o
adaptive_max_pool2d.pic.d            nll_loss_backward.pic.d
adaptive_max_pool2d.pic.o            nll_loss_backward.pic.o
all_gather.pic.d                nms.pic.d
all_gather.pic.o                nms.pic.o
```

I do have modified `torch_xla/csrc/BUILD` but not sure why this error appear and whether I have touched the `RegisterXLA`? what is you suggest? @stgpetrovic

**Comment by ManfeiBai** [comment]
continue tracking in https://github.com/pytorch/xla/pull/5151

**Pull request closed without merging**
