### PR TITLE
Add `unique`, `unique_consecutive`

### PR DESCRIPTION
**Pull request by mrguenther**
Add implementations for `torch.unique` and `torch.unique_consecutive`.

Issue: #7542

### CODE REVIEW

**Comment by ManfeiBai** [comment]
Thanks, looks like we have a real error for py3.9: 'FAILED test/test_ops.py::TestOpInfoCPU::test_reference_eager_unique_cpu_int64 - AssertionError: The values for attribute 'shape' do not match: torch.Size([5, 1]) != torch.Size([5]).'

Please let know if this take more than one hour to investigate too

**Comment by mrguenther** [comment]
I'm pretty sure the Python 3.9 version isn't executing my implementation at all; I was able to reproduce the test failure in a Python 3.9 environment, but when I explicitly called the lowering for `torch.ops.aten.unique_consecutive`, I got the correct result.
```
>>> sys.version_info
sys.version_info(major=3, minor=9, micro=20, releaselevel='final', serial=0)
>>>
>>> torch.unique_consecutive(torch.zeros((5, 5), dtype=torch.float32), return_inverse=True, return_counts=False, dim=-2)
(tensor([[0., 0., 0., 0., 0.]]), tensor([0, 0, 0, 0, 0]))
>>>
>>> torch_xla2.ops.all_aten_jax_ops()[torch.ops.aten.unique_consecutive](jnp.zeros((5, 5), dtype=jnp.float32), return_inverse=True, return_counts=False, dim=-2)
(Array([[0., 0., 0., 0., 0.]], dtype=float32), Array([0, 0, 0, 0, 0], dtype=int32), Array([5], dtype=int32))
```
That would suggest it's an issue with the overload registration, but only in Python 3.9. Do you have an idea what might be wrong?

**Comment by mrguenther** [comment]
Wait, never mind. It's `unique` that's failing, not `unique_consecutive`. That would certainly explain why I can't get my `unique_consecutive` implementation to produce the same output as the test failure. :P

**Comment by mrguenther** [comment]
The Python 3.9 bug should be fixed now.

**Review by qihqi — APPROVED** [review]

**Pull request merged**
