### PR TITLE
Adding tutorial doc that should help users to get started and understand how code change, perf analysis and optimization can be done.

### PR DESCRIPTION
**Pull request by ssusie**
Hi, I would like to make this tutorial doc public

### CODE REVIEW

**Review by yeounoh — APPROVED** [review]
LGTM, reviewed with the offline ver.

**Comment by ssusie** [comment]
Thank @yeounoh! How do I get approval from a maintainer?

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Comment by yeounoh** [comment]
> Thank @yeounoh! How do I get approval from a maintainer?

Only updates the doc, will merge.

**Comment by JackCaoG** [comment]
The content is somewhat similar to https://github.com/pytorch/xla/blob/master/API_GUIDE.md but with a lot more detail. I would recommend add a reference to this doc in the API_GUIDE so people can see it. I would also suggest rename the file to `PyTorch XLA Overview` and add a reference in index in https://github.com/pytorch/xla/blob/master/docs/source/index.rst#test

**Comment by ssusie** [comment]
Added @JackCaoG's asks in my branch. Will create a new pr.

**Pull request merged**
