### PR TITLE
Allow einsum to take optional parameter to align with torch

### PR DESCRIPTION
**Pull request by janeyx99**
This is to allow https://github.com/pytorch/pytorch/pull/84890 to allow an einsum optimization, which currently breaks, see https://github.com/pytorch/pytorch/actions/runs/3114441739/jobs/5050779137.

### CODE REVIEW

**Comment by JackCaoG** [comment]
Check https://github.com/pytorch/xla/tree/master/.circleci#pinning-pytorch-pr-in-pytorchxla-pr regarding how to pin this pr against a pytorch pr.

**Comment by janeyx99** [comment]
All checks green, on the pinned commit, removing pin.

**Comment by janeyx99** [comment]
https://github.com/pytorch/pytorch/pull/84890 has been landed already--this PR is also ready for merge to unblock XLA CI.

**Comment by JackCaoG** [comment]
@janeyx99 can we try to avoid merge xla breaking pr during the weekend, :D? XLA build failed for two days.

**Comment by janeyx99** [comment]
@JackCaoG Yes, sorry about that. I was planning on landing this right after following the instructions but realized to my dismay that I didn't get a review on it yet. 😬

**Pull request merged**
