### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by JackCaoG**
This will make our docs show up in https://pytorch.org/xla/master/, I might want to also do this for the 1.13 release branch, which will update https://pytorch.org/xla/release/1.13/index.html

### CODE REVIEW

**Comment by JackCaoG** [comment]
Let me also move the FSDP doc

**Comment by JackCaoG** [comment]
@ronghanghu FYI, I moved the FSDP doc to a different location.

**Review by will-cromar — APPROVED** [review]

**Comment by JackCaoG** [comment]
I am going to merge it now since doc change won't be test by local CI (only on master CI)

**Comment by JackCaoG** [comment]
@vanbasten23 can you backport this change to 1.13 and update  https://pytorch.org/xla/release/1.13/index.html ? I think you have done it once.

**Pull request merged**
