### PR TITLE
Install libtpu for release dockers

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This pull requests adds libtpu dependency back to the tabel.

Test Plan:
N/A.

### CODE REVIEW

**Comment by alanwaketan** [comment]
I actually don't know how to test this thing locally...

**Comment by will-cromar** [comment]
It'll be something like

```
cd infra/ansible
docker build . --build-arg=ansible_vars="arch=amd64 accelerator=tpu bundle_libtpu=0"
```

**Comment by alanwaketan** [comment]
Thanks, Will. Will report back the test results.

**Review by will-cromar — APPROVED** [review]
LGTM once you have it passing

**Comment by alanwaketan** [comment]
Here is the output:
```
jwtan@t1v-n-94bbce5b-w-0:/mnt/disks/ssd/work/pytorch/xla/infra/ansible$ docker build . --build-arg=ansible_vars="arch=amd64 accelerator=tpu bundle_libtpu=0"
[+] Building 1445.5s (22/22) FINISHED                                                                                                                                                                                                                
 => [internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 963B                                                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.8-bullseye                                                                                                                                                                          0.4s
 => [internal] load build context                                                                                                                                                                                                               0.0s
 => => transferring context: 11.28kB                                                                                                                                                                                                            0.0s
 => CACHED [release  1/14] FROM docker.io/library/python:3.8-bullseye@sha256:61c936f508d8f1e42733328e3e493122d0a41484858894b750d49aed534b5bab                                                                                                   0.0s
 => [release  2/14] WORKDIR /tmp/wheels                                                                                                                                                                                                         0.2s
 => CACHED [build 2/5] WORKDIR /ansible                                                                                                                                                                                                         0.0s
 => CACHED [build 3/5] RUN pip install ansible                                                                                                                                                                                                  0.0s
 => [build 4/5] COPY . /ansible                                                                                                                                                                                                                 0.2s
 => [build 5/5] RUN ansible-playbook -vvv playbook.yaml -e "stage=build" -e "arch=amd64 accelerator=tpu bundle_libtpu=0"                                                                                                                     1275.0s
 => [release  3/14] COPY --from=build /src/pytorch/dist/*.whl ./                                                                                                                                                                                1.1s 
 => [release  4/14] COPY --from=build /src/pytorch/xla/dist/*.whl ./                                                                                                                                                                            0.6s 
 => [release  5/14] COPY --from=build /dist/torchvision*.whl ./                                                                                                                                                                                 0.0s 
 => [release  6/14] RUN echo "Installing the following wheels" && ls *.whl                                                                                                                                                                      0.4s 
 => [release  7/14] RUN pip install *.whl                                                                                                                                                                                                      70.7s 
 => [release  8/14] WORKDIR /ansible                                                                                                                                                                                                            2.3s 
 => [release  9/14] RUN pip install ansible                                                                                                                                                                                                    29.9s 
 => [release 10/14] COPY . /ansible                                                                                                                                                                                                             0.1s 
 => [release 11/14] RUN ansible-playbook -vvv playbook.yaml -e "stage=release" -e "arch=amd64 accelerator=tpu bundle_libtpu=0" --tags "install_deps"                                                                                           45.5s 
 => [release 12/14] RUN rm -rf /ansible /tmp/wheels                                                                                                                                                                                             0.8s 
 => [release 13/14] COPY --from=build /dist/*.whl /dist/                                                                                                                                                                                        1.9s 
 => exporting to image                                                                                                                                                                                                                          5.9s 
 => => exporting layers                                                                                                                                                                                                                         5.9s 
 => => writing image sha256:a0ea2da949b2fe350d24d2fd8b12d2b2c300d46e691021854c1ef6182cb503d5  
```

**Comment by alanwaketan** [comment]
libtpu is installed in the image:
```
root@13786c0a02cc:/# pip list
Package                  Version
------------------------ ----------------
absl-py                  2.1.0
ansible                  6.7.0
ansible-core             2.13.13
cachetools               5.3.3
certifi                  2024.2.2
cffi                     1.16.0
charset-normalizer       3.3.2
cloud-tpu-client         0.10
cryptography             42.0.5
filelock                 3.13.4
fsspec                   2024.3.1
google-api-core          1.34.1
google-api-python-client 1.8.0
google-auth              2.29.0
google-auth-httplib2     0.2.0
googleapis-common-protos 1.63.0
httplib2                 0.22.0
idna                     3.7
importlib_metadata       7.1.0
intel-openmp             2024.1.0
Jinja2                   3.1.3
libtpu-nightly           0.1.dev20240409
MarkupSafe               2.1.5
mkl                      2024.1.0
mkl-include              2024.1.0
mpmath                   1.3.0
networkx                 3.1
numpy                    1.24.4
oauth2client             4.1.3
packaging                24.0
pillow                   10.3.0
pip                      23.0.1
protobuf                 3.20.3
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pycparser                2.22
pyparsing                3.1.2
PyYAML                   6.0.1
requests                 2.31.0
resolvelib               0.8.1
rsa                      4.9
setuptools               57.5.0
six                      1.16.0
sympy                    1.12
tbb                      2021.12.0
torch                    2.4.0
torch-xla                2.4.0
torchvision              0.19.0a0+2c4665f
typing_extensions        4.11.0
uritemplate              3.0.1
urllib3                  2.2.1
wheel                    0.43.0
zipp                     3.18.1
```

**Comment by alanwaketan** [comment]
@will-cromar The python version however is still 3.8? I remember we bump it before.

**Comment by alanwaketan** [comment]
I guess I probably need to make the command to the following:
`docker build . --build-arg=ansible_vars="arch=amd64 accelerator=tpu bundle_libtpu=0 python_version=3.10"`

**Comment by alanwaketan** [comment]
> I guess I probably need to make the command to the following: `docker build . --build-arg=ansible_vars="arch=amd64 accelerator=tpu bundle_libtpu=0 python_version=3.10"`

No, it doesn't work. How can utilize the change here locally? https://github.com/pytorch/xla/pull/6685 cc @will-cromar

**Comment by alanwaketan** [comment]
Let's merge this first and I will figure out the python thing later.

**Comment by will-cromar** [comment]
Looks like the builds passed. The python version is an argument to the dockerfile (it's the base image that we pull before we even run ansible), so it would be `--build-arg=python=3.10`

**Comment by alanwaketan** [comment]
Thanks, Will. I learned something!

**Pull request merged**
