### PR TITLE
Pin update 20240513

### PR DESCRIPTION
**Pull request by qihqi**

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
LGTM if all test passed

**Comment by JackCaoG** [comment]
Seems like some stablehlo test failed

**Comment by qihqi** [comment]
> Seems like some stablehlo test failed

Chatted with @lsy323 decided to disable it first to unblock pin update.

**Review by lsy323 — APPROVED** [review]

**Review by ManfeiBai — APPROVED** [review]
Thanks, LGTM

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Review by bhavya01 — APPROVED** [review]

**Pull request merged**
