### PR TITLE
Skips failing precision tests

### PR DESCRIPTION
**Pull request by mruberry**
Per title.

### CODE REVIEW

**Comment by mruberry** [comment]
CircleCI just started throwing 404 errors. So coming back to this later today.

**Comment by mruberry** [comment]
@dlibenzi Good point. The type of error we're seeing now is:

`Traceback (most recent call last):
  File "/tmp/pytorch/test/common_device_type.py", line 181, in instantiated_test
    return test(self, device_arg)
  File "/tmp/pytorch/xla/test/../../test/test_indexing.py", line 206, in test_index_scalar_with_bool_mask
    a = torch.tensor(1, device=device)
RuntimeError: torch_xla/csrc/ops/as_strided.cpp:71 : Check failed: !size.empty() 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::ir::ops::AsStrided::StrideIsSupported(absl::Span<long long const>, absl::Span<long long const>)
	torch_xla::AtenXlaType::as_strided(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<long>)
	torch_xla::AtenXlaType::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)
	c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&> >, at::Tensor (c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)>::call(c10::OperatorKernel*, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)`

I'll link the appropriate PR in PyTorch that broke us as soon as I'm back at my work machine.

**Comment by mruberry** [comment]
Type promotion tests are not being skipped properly. I'll need to investigate on Monday.

**Comment by dlibenzi** [comment]
> @dlibenzi Good point. The type of error we're seeing now is:
> 
> `Traceback (most recent call last): File "/tmp/pytorch/test/common_device_type.py", line 181, in instantiated_test return test(self, device_arg) File "/tmp/pytorch/xla/test/../../test/test_indexing.py", line 206, in test_index_scalar_with_bool_mask a = torch.tensor(1, device=device) RuntimeError: torch_xla/csrc/ops/as_strided.cpp:71 : Check failed: !size.empty() *** Begin stack trace *** tensorflow::CurrentStackTrace[abi:cxx11]() torch_xla::ir::ops::AsStrided::StrideIsSupported(absl::Span<long long const>, absl::Span<long long const>) torch_xla::AtenXlaType::as_strided(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<long>) torch_xla::AtenXlaType::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&) c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&> >, at::Tensor (c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)>::call(c10::OperatorKernel*, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)`
> 
> I'll link the appropriate PR in PyTorch that broke us as soon as I'm back at my work machine.

Looking into it ...

**Comment by mruberry** [comment]
Test failures are limited to test_operations.py, and I think that's just not picking up the latest changes. Let me merge this to unblock CI runs on PyTorch CI and file an issue.

**Comment by mruberry** [comment]
#1480 addresses the underlying issue.

**Pull request closed without merging**
