### PR TITLE
Use stablehlo.composite instead of stablehlo.custom_call

### PR DESCRIPTION
**Pull request by mlevesquedion**
The recently added composite op provides a more straightforward way to model decomposable ops: https://openxla.org/stablehlo/spec#composite

You may notice that I added a `test.` prefix to names used in tests. This is because the composite op expects its name to be namespaced: https://github.com/openxla/stablehlo/blob/b27ef13c377983d04c233adb8e1de093ec7f350a/docs/spec.md?plain=1#L6543

Here's a sample of what the new IR looks like:

```
func.func @main(%arg0: tensor<f32>, %arg1: tensor<5xf32>) -> tensor<5xf32> {
  %0 = stablehlo.constant dense<1.000000e+00> : tensor<5xf32>
  %1 = stablehlo.add %arg1, %0 : tensor<5xf32>
  %2 = stablehlo.composite "test.p" %1, %arg0 {decomposition = @test.p.impl} : (tensor<5xf32>, tensor<f32>) -> tensor<5xf32>
  return %2 : tensor<5xf32>
}
func.func private @test.p.impl(%arg0: tensor<5xf32>, %arg1: tensor<f32>) -> tensor<5xf32> {
  %0 = stablehlo.broadcast_in_dim %arg1, dims = [] : (tensor<f32>) -> tensor<5xf32>
  %1 = stablehlo.add %arg0, %0 : tensor<5xf32>
  return %1 : tensor<5xf32>
}
```

### CODE REVIEW

**Comment by lsy323** [comment]
@mlevesquedion Can you fix the linter:
https://github.com/pytorch/xla/blob/66acfebff8acc244984f2782cdf178ad07f1ac32/CONTRIBUTING.md#c-style-guide
https://github.com/pytorch/xla/blob/66acfebff8acc244984f2782cdf178ad07f1ac32/CONTRIBUTING.md#python-style-guide

**Comment by lsy323** [comment]
@mlevesquedion could you please also paste the stablehlo text, probably just a snippet, in the PR description to record the composite format?

**Review by lsy323 — APPROVED** [review]
LGTM, pending on fixing linter and passing CI.

**Comment by mlevesquedion** [comment]
Thanks for the review! Sorry I forgot to run the lints. I added an example to the PR description.

**Pull request merged**
