### PR TITLE
Pin expecttest version (#6221)

### PR DESCRIPTION
**Pull request by zpcore**
Cherry pick the pin update to resolve xl-ml test failure.

### CODE REVIEW

**Comment by JackCaoG** [comment]
this only helps the TPU CI through, it won't fix xlml test. they used a different config file I believe.

**Review by JackCaoG — APPROVED** [review]

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Comment by zpcore** [comment]
> this only helps the TPU CI through, it won't fix xlml test. they used a different config file I believe.

Oh you are right, should we just drop this PR? I will fix in the xl-ml test script.

**Comment by JackCaoG** [comment]
it doesn't hurt to merge this one in, but if we don't run TPUCI on r2.2 then it doesn't really fix anything either

**Comment by zpcore** [comment]
OK, let me merge this PR. Thanks

**Pull request merged**
