### PR TITLE
Update tf submodule to 04/07/2022

### PR DESCRIPTION
**Pull request by JackCaoG**

### CODE REVIEW

**Comment by JackCaoG** [comment]
I verified that resnet worked on TPUVM with this new tf update. 

TODO: verify `optimization_barrier` still works with the patch

**Comment by JackCaoG** [comment]
so there is a bug in the bazel, when I have a cache for tf build, rebuilding with this new commit will fail with message like
```
ERROR: /usr/local/google/home/jackcao/.cache/bazel/_bazel_jackcao/f24f9e5588a9a14d59c86f3aad6558a2/external/llvm-project/mlir/BUILD.bazel:2992:11: Compiling mlir/lib/Support/IndentedOstream.cpp failed: undeclared inclusion(s) in rule '@llvm-project//mlir:Support':
this rule is missing dependency declarations for the following files included by 'mlir/lib/Support/IndentedOstream.cpp':
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/config.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/compiler/xla/xla_client:libxla_computation_client.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

I have tried to clean the bazel cache by manually deleting `~/.cache/bazel` and `bazel clean --expunge` under tf dir. Both of them does not do the trick. If I create a new VM and build from scratch, build will pass. Circle CI build also pass. I am a bit running out of ideas. I felt like there is some kind of cache still remain after all of the cleanup I do.

**Comment by JackCaoG** [comment]
@yeounoh in case you has more knowledge about how bazel works than I do.

**Review by yeounoh — APPROVED** [review]
LGTM -- also tested on 1VM to run with a new libtpu.

**Comment by JackCaoG** [comment]
@hjm-aws FYI

**Pull request merged**
