### PR TITLE
enable nn/convolution tests

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/pull/87474

### CODE REVIEW

**Comment by kshitij12345** [comment]
Failures look irrelevant. (Probably master is broken)

**Comment by JackCaoG** [comment]
@kshitij12345 can you rebase?

**Comment by kshitij12345** [comment]
Updated. However, the main PR is stalled due to a CI failure. Will ping here again, once that is ready.

**Comment by JackCaoG** [comment]
seems like it just timed out
```
test_Conv2d_backward_depthwise_xla_float64 (__main__.TestNNDeviceTypeXLA) ... 2022-10-26 19:50:49.649734: E  229827 tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module SyncTensorsGraph.30789] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
2022-10-26 20:31:55.528856: E  229662 tensorflow/compiler/xla/service/slow_operation_alarm.cc:133] The operation took 43m5.879197153s

********************************
[Compiling module SyncTensorsGraph.30789] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************

Too long with no output (exceeded 1h0m0s): context deadline exceeded
```

**Comment by kshitij12345** [comment]
@JackCaoG The CI is green (it was timing out because I hadn't pinned the PR). Also, the PyTorch PR has been merged. PTAL :)

Thanks!

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Pull request merged**
