### PR TITLE
[PERF] Adds DDP mode to imagenet and mnist tests

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This pull requests enhance test_train_mp_imagenet.py and test_train_mp_mnist.py with the ability to use torch.nn.parallel.DistributedDataParallel. So it's easier for us to benchmark it and compare with our native approach.

Test Plan:
MASTER_ADDR=localhost MASTER_PORT=6000 python test/test_train_mp_imagenet.py --ddp --fake_data MASTER_ADDR=localhost MASTER_PORT=6000 python test/test_train_mp_mnist.py --ddp --fake_data

### CODE REVIEW

**Review by will-cromar — APPROVED** [review]
LGTM. Thanks!

**Comment by alanwaketan** [comment]
Thanks, Will.

**Review by JackCaoG — APPROVED** [review]
lgtm, feel free to merge once ci is green.

**Comment by alanwaketan** [comment]
The CI failure is suspicious. Let me see if I can build xla locally.

**Comment by alanwaketan** [comment]
Okay, the CI is broken by https://github.com/pytorch/pytorch/commit/1ff52225f185e11faa421528815aaa43e79e0722. I think Ed is working on fixing it. Let's just hold landing this PR.

**Pull request merged**
