### PR TITLE
[Dist] Refactor ZeRO-1

### PR DESCRIPTION
**Pull request by hgt312**
https://github.com/pytorch/xla/pull/4648

changes:
- sync param groups to support lr schedulers
- option for delay init, that can make it easy to use with tensor parallel and lightning
- padding
- fix save/load

### CODE REVIEW

**Comment by JackCaoG** [comment]
Build seems to be failing, maybe you want to rebase

**Comment by hgt312** [comment]
still failed

**Comment by JackCaoG** [comment]
hmm, it is the 
```
2023-06-08T18:50:30.8396848Z error: command '/usr/local/bin/bazel' failed with exit code 37
```
our CI are having some issue recently, I am not sure why a python file will fail the build.

**Comment by JackCaoG** [comment]
Hey @hgt312 FYI the forked repo will not run the CI after a recent migration from circleCI to github actions. @stgpetrovic mentioned we need to set up something in our repo, we will follow up on that.

**Comment by hgt312** [comment]
@JackCaoG CI is working now, can you guys help review?

**Comment by JackCaoG** [comment]
@alanwaketan Can you take a look when you have cycle?

**Comment by alanwaketan** [comment]
@hgt312 Is this ready for review? I'm seeing you making active changes.

**Comment by hgt312** [comment]
ready now, i see CI failed with unrelated error

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by hgt312** [comment]
can you help merge this pr? @JackCaoG

**Pull request merged**
