### PR TITLE
Enable test_logical_xor

### PR DESCRIPTION
**Pull request by xuhdev**
Emancipated by https://github.com/pytorch/pytorch/pull/29591

### CODE REVIEW

**Comment by xuhdev** [comment]
@ailzhang Done!

**Comment by ailzhang** [comment]
Aha sadly this test still fails at `half` type. (XLA currently doesn't support half)

**Comment by xuhdev** [comment]
Maybe we can wait until https://github.com/pytorch/pytorch/pull/28162 is merged? There the test code has specifically skipped XLA for `half` type

**Comment by ailzhang** [comment]
> Maybe we can wait until [pytorch/pytorch#28162](https://github.com/pytorch/pytorch/pull/28162) is merged? There the test code has specifically skipped XLA for `half` type

SG! Let me put a label on this so that we come back to it later :D

**Comment by xuhdev** [comment]
Closing now, as it should give way to #1428

**Pull request closed without merging**
