### PR TITLE
Companion PR for #81762

### PR DESCRIPTION
**Pull request by Lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #3972

As per title, [81762](https://github.com/pytorch/pytorch/pull/81762)

### CODE REVIEW

**Comment by Lezcano** [comment]
@JackCaoG I removed the xfailed test, but now it keeps complaining. Any idea what could be going on here?

**Comment by JackCaoG** [comment]
FYI GHstack does not work with pt/xla lol

**Comment by JackCaoG** [comment]
I don't think you need this pr, if you rebase your pytorch pr you should see the test started passing.

**Comment by Lezcano** [comment]
Closing in favour of https://github.com/pytorch/xla/pull/3976.

**Pull request closed without merging**
